/******************************************************************************
#  Copyright (c) 2016 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#******************************************************************************/

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.8-dev at Mon Jun 27 17:22:53 2016. */

#include "radio_config_interface.pb.h"



const pb_field_t com_qualcomm_qti_radioconfiginterface_MessageTag_fields[6] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, com_qualcomm_qti_radioconfiginterface_MessageTag, type, type, 0),
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_MessageTag, id, type, 0),
    PB_FIELD2(  3, ENUM    , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_MessageTag, error, id, 0),
    PB_FIELD2(  4, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_MessageTag, token, error, 0),
    PB_FIELD2(  5, BYTES   , OPTIONAL, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_MessageTag, payload, token, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_Value128_fields[3] = {
    PB_FIELD2(  1, FIXED64 , OPTIONAL, STATIC  , FIRST, com_qualcomm_qti_radioconfiginterface_Value128, lsb, lsb, 0),
    PB_FIELD2(  2, FIXED64 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_Value128, msb, lsb, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_Plmn_fields[3] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, POINTER , FIRST, com_qualcomm_qti_radioconfiginterface_Plmn, mcc, mcc, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_Plmn, mnc, mcc, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_fields[4] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, POINTER , FIRST, com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy, plmn, plmn, &com_qualcomm_qti_radioconfiginterface_Plmn_fields),
    PB_FIELD2(  2, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy, validityTime, plmn, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy, range, validityTime, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_fields[4] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, POINTER , FIRST, com_qualcomm_qti_radioconfiginterface_MonitoringPolicy, plmn, plmn, &com_qualcomm_qti_radioconfiginterface_Plmn_fields),
    PB_FIELD2(  2, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_MonitoringPolicy, validityTime, plmn, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_MonitoringPolicy, remainingTime, validityTime, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_LtedConfig_fields[6] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, com_qualcomm_qti_radioconfiginterface_LtedConfig, osId, osId, &com_qualcomm_qti_radioconfiginterface_Value128_fields),
    PB_FIELD2(  2, STRING  , OPTIONAL, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_LtedConfig, apn, osId, 0),
    PB_FIELD2(  3, MESSAGE , REPEATED, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_LtedConfig, announcingPolicy, apn, &com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_fields),
    PB_FIELD2(  4, MESSAGE , REPEATED, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_LtedConfig, monitoringPolicy, announcingPolicy, &com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_fields),
    PB_FIELD2(  5, BYTES   , OPTIONAL, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_LtedConfig, bakPassword, monitoringPolicy, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_LtedCategory_fields[3] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, POINTER , FIRST, com_qualcomm_qti_radioconfiginterface_LtedCategory, osAppId, osAppId, 0),
    PB_FIELD2(  2, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_LtedCategory, category, osAppId, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_fields[7] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, com_qualcomm_qti_radioconfiginterface_ConfigItemMsg, item, item, 0),
    PB_FIELD2(  2, BOOL    , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_ConfigItemMsg, boolValue, item, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_ConfigItemMsg, intValue, boolValue, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_ConfigItemMsg, stringValue, intValue, 0),
    PB_FIELD2(  5, BYTES   , OPTIONAL, POINTER , OTHER, com_qualcomm_qti_radioconfiginterface_ConfigItemMsg, byteArrayValue, stringValue, 0),
    PB_FIELD2(  6, ENUM    , OPTIONAL, STATIC  , OTHER, com_qualcomm_qti_radioconfiginterface_ConfigItemMsg, errorCause, byteArrayValue, 0),
    PB_LAST_FIELD
};

const pb_field_t com_qualcomm_qti_radioconfiginterface_ConfigMsg_fields[2] = {
    PB_FIELD2(  1, MESSAGE , REPEATED, POINTER , FIRST, com_qualcomm_qti_radioconfiginterface_ConfigMsg, settings, settings, &com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy, plmn) < 65536 && pb_membersize(com_qualcomm_qti_radioconfiginterface_MonitoringPolicy, plmn) < 65536 && pb_membersize(com_qualcomm_qti_radioconfiginterface_LtedConfig, osId) < 65536 && pb_membersize(com_qualcomm_qti_radioconfiginterface_LtedConfig, announcingPolicy) < 65536 && pb_membersize(com_qualcomm_qti_radioconfiginterface_LtedConfig, monitoringPolicy) < 65536 && pb_membersize(com_qualcomm_qti_radioconfiginterface_ConfigMsg, settings) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_com_qualcomm_qti_radioconfiginterface_MessageTag_com_qualcomm_qti_radioconfiginterface_Value128_com_qualcomm_qti_radioconfiginterface_Plmn_com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_com_qualcomm_qti_radioconfiginterface_LtedConfig_com_qualcomm_qti_radioconfiginterface_LtedCategory_com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_com_qualcomm_qti_radioconfiginterface_ConfigMsg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy, plmn) < 256 && pb_membersize(com_qualcomm_qti_radioconfiginterface_MonitoringPolicy, plmn) < 256 && pb_membersize(com_qualcomm_qti_radioconfiginterface_LtedConfig, osId) < 256 && pb_membersize(com_qualcomm_qti_radioconfiginterface_LtedConfig, announcingPolicy) < 256 && pb_membersize(com_qualcomm_qti_radioconfiginterface_LtedConfig, monitoringPolicy) < 256 && pb_membersize(com_qualcomm_qti_radioconfiginterface_ConfigMsg, settings) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_com_qualcomm_qti_radioconfiginterface_MessageTag_com_qualcomm_qti_radioconfiginterface_Value128_com_qualcomm_qti_radioconfiginterface_Plmn_com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_com_qualcomm_qti_radioconfiginterface_LtedConfig_com_qualcomm_qti_radioconfiginterface_LtedCategory_com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_com_qualcomm_qti_radioconfiginterface_ConfigMsg)
#endif


