

STATSPOLLMGR := StatsPollManager
CNE_EXT := ConnectivityExt
CNESETTINGS_DBG := CNESettings



PRODUCT_PACKAGES += $(CNE_EXT)
PRODUCT_PACKAGES += $(STATSPOLLMGR)
PRODUCT_PACKAGES_DEBUG += $(CNESETTINGS_DBG)
