ifeq ($(TARGET_BOARD_PLATFORM),kona)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ENABLE_TRUSTED_UI_2_0 := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),lito)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
APP_BUFFER_CFLAGS := -DAPP_BUF_ALIGNMENT=0x1000
endif

ifeq ($(TARGET_BOARD_PLATFORM),bengal)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),msmnile)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdmshrike)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm845)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),$(TRINKET))
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),$(MSMSTEPPE))
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm710)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm660)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8998)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8998
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8996)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8996
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8937)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_THORIUM
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8953)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8953
endif
