/******************************************************************************
#  Copyright (c) 2017 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#******************************************************************************/
  /**********************************************
   *                SIM (MMGSDI)                *
   **********************************************/

  /* ---------------------------*
   *      COMMAND CALLBACKS     *
   * ---------------------------*/

  /* QCRIL_EVT_INTERNAL_MMGSDI_CARD_POWER_UP */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_CARD_POWER_UP, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_CARD_POWER_DOWN */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_CARD_POWER_DOWN, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_GET_FDN_STATUS */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_GET_FDN_STATUS, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_SET_FDN_STATUS */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_SET_FDN_STATUS, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_GET_PIN1_STATUS */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_GET_PIN1_STATUS, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_SET_PIN1_STATUS */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_SET_PIN1_STATUS, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_ACTIVATE_SUBS */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_ACTIVATE_SUBS, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_DEACTIVATE_SUBS */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_DEACTIVATE_SUBS, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_MODEM_RESTART_START */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_MODEM_RESTART_START, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_MMGSDI_MODEM_RESTART_COMPLETE */
QCRIL_LEGACY_EVENT(INTERNAL_MMGSDI_MODEM_RESTART_COMPLETE, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_INTERNAL_UIM_GET_MCC_MNC */
QCRIL_LEGACY_EVENT(INTERNAL_UIM_GET_MCC_MNC, NULL, &QCRIL_GRP_UIM_MMGSDI, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/

QCRIL_LEGACY_EVENT(RIL_REQUEST_SETUP_DATA_CALL, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES); // DATA STUB

   /**********************************************
   *                    SMS                     *
   **********************************************/

  /* ---------------------------*
   *      COMMAND CALLBACKS     *
   * ---------------------------*/

  /* QCRIL_EVT_SMS_COMMAND_CALLBACK */

  /* QCRIL_EVT_SMS_SUBSCRIPTION_PREF_INFO */

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/
#if 0 // comment as part of HIDL decouple
  /* 25 - RIL_REQUEST_SEND_SMS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SEND_SMS, qcril_sms_request_send_sms, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 26 - RIL_REQUEST_SEND_SMS_EXPECT_MORE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SEND_SMS_EXPECT_MORE, qcril_sms_request_send_sms_expect_more, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 37 - RIL_REQUEST_SMS_ACKNOWLEDGE  */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SMS_ACKNOWLEDGE, qcril_sms_request_sms_acknowledge, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 63 - RIL_REQUEST_WRITE_SMS_TO_SIM */
QCRIL_LEGACY_EVENT(RIL_REQUEST_WRITE_SMS_TO_SIM, qcril_sms_request_write_sms_to_sim, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 64 - RIL_REQUEST_DELETE_SMS_ON_SIM */
QCRIL_LEGACY_EVENT(RIL_REQUEST_DELETE_SMS_ON_SIM, qcril_sms_request_delete_sms_on_sim, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 100 - RIL_REQUEST_GET_SMSC_ADDRESS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_SMSC_ADDRESS, qcril_sms_request_get_smsc_address, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 101 - RIL_REQUEST_SET_SMSC_ADDRESS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_SMSC_ADDRESS, qcril_sms_request_set_smsc_address, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 102 - RIL_REQUEST_REPORT_SMS_MEMORY_STATUS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_REPORT_SMS_MEMORY_STATUS, qcril_sms_request_report_sms_memory_status, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 89 - RIL_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG, qcril_sms_request_gsm_get_broadcast_sms_config, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 90 - RIL_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG, qcril_sms_request_gsm_set_broadcast_sms_config, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 91 - RIL_REQUEST_GSM_SMS_BROADCAST_ACTIVATION */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GSM_SMS_BROADCAST_ACTIVATION, qcril_sms_request_gsm_sms_broadcast_activation, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 87 - RIL_REQUEST_CDMA_SEND_SMS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SEND_SMS, qcril_sms_request_cdma_send_sms, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 88 - RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE, qcril_sms_request_cdma_sms_acknowledge, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 96 - RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM, qcril_sms_request_cdma_write_sms_to_ruim, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 97 - RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM, qcril_sms_request_cdma_delete_sms_on_ruim, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 92 - RIL_REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG, qcril_sms_request_cdma_get_broadcast_sms_config, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 93 - RIL_REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG, qcril_sms_request_cdma_set_broadcast_sms_config, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 94 - RIL_REQUEST_CDMA_SMS_BROADCAST_ACTIVATION */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SMS_BROADCAST_ACTIVATION, qcril_sms_request_cdma_sms_broadcast_activation, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 108 - RIL_REQUEST_IMS_REGISTRATION_STATE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_IMS_REGISTRATION_STATE, qcril_sms_request_ims_registration_state, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 109 - RIL_REQUEST_IMS_SEND_SMS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_IMS_SEND_SMS, qcril_sms_request_ims_send_sms, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* -------------------*
   *        EVENTS      *
   * -------------------*/
  /* QCRIL_EVT_SMS_RAW_READ */
QCRIL_LEGACY_EVENT(SMS_RAW_READ, qcril_sms_request_raw_read, &QCRIL_GRP_SMS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_NAS_SIG_STRENGTH_UPDATE */
QCRIL_LEGACY_EVENT(QMI_NAS_SIG_STRENGTH_UPDATE, qcril_qmi_trigger_propagate_known_signal_strength_ind, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_NAS_PASSOVER_NW_SEL_IND */
QCRIL_LEGACY_EVENT(QMI_NAS_PASSOVER_NW_SEL_IND, qcril_qmi_nas_nw_select_dedicated_unsolicited_indicaton_event_thrd_handler, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_POST_VOICE_RTE_CHANGE_IND */
QCRIL_LEGACY_EVENT(QMI_RIL_POST_VOICE_RTE_CHANGE_IND, qcril_qmi_nas_post_voice_rte_change_ind_handler, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_ASSESS_EMRGENCY_NUMBER_LIST_DESIGNATED_COUNTRY */
QCRIL_LEGACY_EVENT(QMI_RIL_ASSESS_EMRGENCY_NUMBER_LIST_DESIGNATED_COUNTRY, qcril_qmi_nas_assess_emergency_number_list_handler, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  // QCRIL_EVT_QMI_RIL_ENFORCE_DEFERRED_MODE_PREF_SET
QCRIL_LEGACY_EVENT(QMI_RIL_ENFORCE_DEFERRED_MODE_PREF_SET, qmi_ril_nwreg_mode_pref_enforce_deferred_op_handler, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  // QCRIL_EVT_QMI_RIL_POST_OPRT_ONLINE_ACTION
QCRIL_LEGACY_EVENT(QMI_RIL_POST_OPRT_ONLINE_ACTION, qmi_ril_nwreg_post_oprt_online_action_handler, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_INIT */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_INIT, qcril_mbn_hw_update_init_hdlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_DISABLED_INIT */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_DISABLED_INIT, qcril_mbn_hw_update_disabled_init_hdlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_GET_SELECTED_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_GET_SELECTED_CONFIG, qcril_mbn_hw_query_selected_config_hndlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_DEACTIVATE_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_DEACTIVATE_CONFIG, qcril_mbn_hw_deactivate_config_hndlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_DELETE_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_DELETE_CONFIG, qcril_mbn_hw_delete_config_hndlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_LOAD_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_LOAD_CONFIG, qcril_mbn_hw_load_config_hndlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_SELECT_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_SELECT_CONFIG, qcril_mbn_hw_select_config_hndlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_HW_ACTIVATE_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_HW_ACTIVATE_CONFIG, qcril_mbn_hw_activate_config_hndlr, &QCRIL_GRP_MBN_HW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_DISALBLE_MODEM_UPDATE */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_DISALBLE_MODEM_UPDATE, qcril_mbn_sw_disable_modem_update_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_INIT */
QCRIL_LEGACY_EVENT(REQUEST_VERIFY_MBN_SW_INIT, qcril_mbn_sw_update_init_helper, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_INIT */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_INIT, qcril_mbn_sw_update_init_hdlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_GET_SELECTED_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_GET_SELECTED_CONFIG, qcril_mbn_sw_query_selected_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_GET_CONFIG_INFO */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_GET_CONFIG_INFO, qcril_mbn_sw_get_config_info_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_DEACTIVATE_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_DEACTIVATE_CONFIG, qcril_mbn_sw_deactivate_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_DELETE_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_DELETE_CONFIG, qcril_mbn_sw_delete_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_LOAD_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_LOAD_CONFIG, qcril_mbn_sw_load_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_SELECT_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_SELECT_CONFIG, qcril_mbn_sw_select_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_ACTIVATE_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_ACTIVATE_CONFIG, qcril_mbn_sw_activate_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_CLEANUP_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_CLEANUP_CONFIG, qcril_mbn_sw_cleanup_config_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_PDC_DELETE_ALL */
QCRIL_LEGACY_EVENT(QMI_RIL_PDC_DELETE_ALL, qcril_mbn_pdc_delete_all_sw_configs, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_COUNT_PENDING_CONFIGS */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_COUNT_PENDING_CONFIGS, qcril_mbn_sw_count_pending_configs_hndlr, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_REQUEST_MBN_SW_QUERY_PENDING_CONFIG */
QCRIL_LEGACY_EVENT(REQUEST_MBN_SW_QUERY_PENDING_CONFIG, qcril_mbn_pdc_query_pending_sw_config, &QCRIL_GRP_MBN_SW, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_NAS_BAR_FAKE_GCELL */
QCRIL_LEGACY_EVENT(QMI_NAS_BAR_FAKE_GCELL, qcril_qmi_nas_bar_fake_gcell, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /**********************************************
   *                    modem reset              *
   **********************************************/

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_SUSPEND_REQ */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_SUSPEND_REQ, qmi_ril_core_final_suspend_handler, &QCRIL_GRP_DEFAULT, ~(TO_BIT(QMI_RIL_GEN_OPERATIONAL_STATUS_RESUME_PENDING)|TO_BIT(QMI_RIL_GEN_OPERATIONAL_STATUS_RESUME_RETRY)|TO_BIT(QMI_RIL_GEN_OPERATIONAL_STATUS_RESUMING)));

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_SUSPEND_CON */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_SUSPEND_CON, qmi_ril_suspending_con_handler, &QCRIL_GRP_DEFAULT,  ~(TO_BIT(QMI_RIL_GEN_OPERATIONAL_STATUS_RESUME_PENDING)|TO_BIT(QMI_RIL_GEN_OPERATIONAL_STATUS_RESUME_RETRY)|TO_BIT(QMI_RIL_GEN_OPERATIONAL_STATUS_RESUMING)));

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_RIL_CORE_PRE_RESUME_REQ */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_RIL_CORE_PRE_RESUME_REQ, qmi_ril_core_pre_resume_handler, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_RESUME_REQ */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_RESUME_REQ, qmi_ril_core_final_resume_handler, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_RIL_CORE_PRE_RESUME_CON */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_RIL_CORE_PRE_RESUME_CON, qmi_ril_resuming_con_handler, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_RESUME_CON */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_RIL_CORE_FINAL_RESUME_CON, qmi_ril_resuming_con_handler, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_CHECK_IF_SERVICE_UP */
QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_CHECK_IF_SERVICE_UP, qcril_qmi_check_if_service_is_up, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_SERVICE_DOWN */
QCRIL_LEGACY_EVENT(QMI_RIL_SERVICE_DOWN, qcril_qmi_handle_event_service_down, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_MODEM_RESTART_CHECK_IF_SSR_EXCL_SERVICE_UP */
//QCRIL_LEGACY_EVENT(QMI_RIL_MODEM_RESTART_CHECK_IF_SSR_EXCL_SERVICE_UP, qcril_qmi_check_if_ssr_excluded_service_is_up, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_SSR_EXCL_SERVICE_DOWN */
//QCRIL_LEGACY_EVENT(QMI_RIL_SSR_EXCL_SERVICE_DOWN, qcril_qmi_handle_event_ssr_excluded_service_down, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* -------------------*
   *        EVENTS      *
   * -------------------*/
  /* QCRIL_EVT_QMI_RIL_SEND_UNSOL_RADIO_STATE_CHANGED */
QCRIL_LEGACY_EVENT(QMI_RIL_SEND_UNSOL_RADIO_STATE_CHANGED, qcril_qmi_nas_send_unsol_radio_state_changed, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_CONNECTED_EMEGENCY_CALL_END */
QCRIL_LEGACY_EVENT(QMI_RIL_CONNECTED_EMEGENCY_CALL_END, qcril_qmi_nas_connected_emergency_call_end_hdlr, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_NW_SCAN */
QCRIL_LEGACY_EVENT(QMI_REQUEST_NW_SCAN, NULL, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_NW_SELECT */
QCRIL_LEGACY_EVENT(QMI_REQUEST_NW_SELECT, NULL, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_EMBMS_ENABLE_DATA_REQ */
QCRIL_LEGACY_EVENT(QMI_RIL_EMBMS_ENABLE_DATA_REQ, NULL, &QCRIL_GRP_EMBMS, QMI_RIL_ALLOWED_IN_ALL_STATES); // DATA STUB


  /* ---------------------------*
   *      RESPONSE HANDLERS     *
   * ---------------------------*/

  /* ---------------------------*
   *      INDICATION HANDLERS   *
   * ---------------------------*/

#if 0
  /* QCRIL_EVT_QMI_VOICE_BURST_STOP_CONT_DTMF */
  /* QCRIL_EVT_QMI_VOICE_BURST_STOP_CONT_DTMF */
QCRIL_LEGACY_EVENT(QMI_VOICE_BURST_STOP_CONT_DTMF, NULL, &QCRIL_GRP_VOICE, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* QCRIL_EVT_QMI_VOICE_GET_WAITING_CALL */
QCRIL_LEGACY_EVENT(QMI_VOICE_GET_WAITING_CALL, qcril_qmi_voice_waiting_call_handler, &QCRIL_GRP_VOICE, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_VOICE_AM_LCH_COMPLETE */
QCRIL_LEGACY_EVENT(QMI_VOICE_AM_LCH_COMPLETE, qcril_qmi_voice_am_lch_complete_handler, &QCRIL_GRP_VOICE, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_NAS_HANDLE_INDICATIONS */
//QCRIL_LEGACY_EVENT(QMI_NAS_HANDLE_INDICATIONS, qcril_qmi_nas_unsolicited_indication_cb_helper, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_DMS_HANDLE_INDICATIONS */
QCRIL_LEGACY_EVENT(QMI_DMS_HANDLE_INDICATIONS, qcril_qmi_dms_unsolicited_indication_cb_helper, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_SMS_HANDLE_INDICATIONS */
//QCRIL_LEGACY_EVENT(QMI_SMS_HANDLE_INDICATIONS, qcril_qmi_sms_unsolicited_indication_cb_helper, &QCRIL_GRP_SMS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QCRIL_EVT_PBM_CARD_ERROR */
QCRIL_LEGACY_EVENT(QCRIL_EVT_PBM_CARD_ERROR, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);


#ifdef QMI_RIL_UTF
  /* QCRIL_EVT_QMI_DSD_HANDLE_INDICATIONS */
QCRIL_LEGACY_EVENT(QMI_DSD_HANDLE_INDICATIONS, qcril_qmi_dsd_unsolicited_indication_cb_helper, &QCRIL_GRP_NAS, QMI_RIL_ALLOWED_IN_ALL_STATES);

#endif
  /* QCRIL_EVT_QMI_DMS_HANDLE_ASYNC_CB */
QCRIL_LEGACY_EVENT(QMI_DMS_HANDLE_ASYNC_CB, qcril_qmi_dms_async_cb_helper, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_LTE_HANDLE_COMM_CALLBACKS */
QCRIL_LEGACY_EVENT(QMI_LTE_HANDLE_COMM_CALLBACKS, qcril_qmi_lte_direct_disc_command_cb_helper, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_LTE_HANDLE_INDICATIONS */
QCRIL_LEGACY_EVENT(QMI_LTE_HANDLE_INDICATIONS, qcril_qmi_lte_direct_disc_unsol_ind_cb_helper, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/

  /**********************************************
   *                    eMBMS                   *
   **********************************************/

  /* QCRIL_EVT_QMI_RIL_EMBMS_SEND_UNSOL_RADIO_STATE */
QCRIL_LEGACY_EVENT(QMI_RIL_EMBMS_SEND_UNSOL_RADIO_STATE, qcril_qmi_nas_embms_send_radio_state_helper, &QCRIL_GRP_OEM_HOOK, QMI_RIL_ALLOWED_IN_ALL_STATES);










  /**********************************************
   *                    QTuner (RFPE)           *
   **********************************************/


  /**********************************************
   *           CM                               *
   **********************************************/

  /* ---------------------------*
   *      COMMAND CALLBACKS     *
   * ---------------------------*/


  /**********************************************
   *           CM - Phone Services              *
   **********************************************/

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/

#if 0
  /* 45 - RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE, qcril_qmi_nas_query_network_selection_mode, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 46 - RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC, qcril_qmi_nas_set_network_selection_automatic, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 47 - RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 48 - RIL_REQUEST_QUERY_AVAILABLE_NETWORKS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_AVAILABLE_NETWORKS, qcril_qmi_nas_query_available_networks, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* RIL_REQUEST_CANCEL_QUERY_AVAILABLE_NETWORKS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CANCEL_QUERY_AVAILABLE_NETWORKS, qcril_qmi_nas_cancel_query_available_networks, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 58 - RIL_REQUEST_RESET_RADIO - Deprecated per ril.h */

  /* 65 - RIL_REQUEST_SET_BAND_MODE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_BAND_MODE, qcril_qmi_nas_set_band_mode, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 66 - RIL_REQUEST_QUERY_AVAILABLE_BAND_MODE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_AVAILABLE_BAND_MODE, qcril_qmi_nas_query_available_band_mode, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 73 - RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE, qcril_qmi_nas_request_set_preferred_network_type, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 74 - RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE, qcril_qmi_nas_request_get_preferred_network_type, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 77 - RIL_REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE, qcril_qmi_nas_set_subscription_source, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 106 - RIL_REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE, qcril_qmi_nas_get_subscription_source, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 78 - RIL_REQUEST_CDMA_SET_ROAMING_PREFERENCE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SET_ROAMING_PREFERENCE, qcril_qmi_nas_request_set_roaming_preference, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 79 - RIL_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE, qcril_qmi_nas_request_query_roaming_preference, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 103 - RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE, qcril_qmi_nas_exit_emergency_callback_mode, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);


  /* 109 - RIL_REQUEST_SET_UICC_SUBSCRIPTION */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_UICC_SUBSCRIPTION, qcril_qmi_nas_set_uicc_subscription, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* 111 - RIL_REQUEST_SET_INITIAL_ATTACH_APN*/
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_INITIAL_ATTACH_APN, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

#if 0
  /* 123 - RIL_REQUEST_ALLOW_DATA */
QCRIL_LEGACY_EVENT(RIL_REQUEST_ALLOW_DATA, qcril_qmi_nas_request_allow_data, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 129 - RIL_REQUEST_SHUTDOWN */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SHUTDOWN, qcril_qmi_nas_request_shutdown, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* RIL_REQUEST_GET_RADIO_CAPABILITY */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_RADIO_CAPABILITY, qcril_qmi_nas_get_radio_capability, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* RIL_REQUEST_SET_RADIO_CAPABILITY */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_RADIO_CAPABILITY, qcril_qmi_nas_set_radio_capability, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* 134 - RIL_REQUEST_SET_LTE_BAND_PREF */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_LTE_BAND_PREF, qcril_qmi_nas_set_lte_band_pref, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

#if 0
/* 142 - RIL_REQUEST_START_NETWORK_SCAN */
QCRIL_LEGACY_EVENT(RIL_REQUEST_START_NETWORK_SCAN, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

/* 143 - RIL_REQUEST_STOP_NETWORK_SCAN */
QCRIL_LEGACY_EVENT(RIL_REQUEST_STOP_NETWORK_SCAN, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

#if 0
QCRIL_LEGACY_EVENT(RIL_REQUEST_ENABLE_5G, qcril_qmi_nas_request_enable_5g, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_ENABLE_5G_ONLY, qcril_qmi_nas_request_enable_5g_only, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_DISABLE_5G, qcril_qmi_nas_request_disable_5g, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_5G_STATUS, qcril_qmi_nas_request_query_5g_status, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_ENDC_DCNR, qcril_qmi_nas_request_query_endc_dcnr, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_NR_BEARER_ALLOCATION, qcril_qmi_nas_request_query_nr_bearer_allocation, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_NR_SIGNAL_STRENGTH, qcril_qmi_nas_request_nr_signal_strength, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_UPPERLAYER_IND_INFO, qcril_qmi_nas_request_query_upperlayer_ind_info, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_EVENT(RIL_REQUEST_QUERY_5G_CONFIG_INFO, qcril_qmi_nas_request_query_5g_config_info, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* -------------------*
   *        EVENTS      *
   * -------------------*/

  /* QCRIL_EVT_CM_UPDATE_FDN_STATUS */
QCRIL_LEGACY_EVENT(CM_UPDATE_FDN_STATUS, qcril_qmi_nas_dms_event_update_fdn_status, &QCRIL_GRP_CM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_CM_CARD_APP_STATUS_CHANGED */
QCRIL_LEGACY_EVENT(CM_CARD_APP_STATUS_CHANGED, qcril_qmi_nas_event_app_status_update, &QCRIL_GRP_CM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_CM_ACTIVATE_PROVISION_STATUS */
QCRIL_LEGACY_EVENT(CM_ACTIVATE_PROVISION_STATUS, NULL, &QCRIL_GRP_CM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_CM_DEACTIVATE_PROVISION_STATUS */
QCRIL_LEGACY_EVENT(CM_DEACTIVATE_PROVISION_STATUS, NULL, &QCRIL_GRP_CM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /**********************************************
   *       CM - Serving System Management       *
   **********************************************/

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/

#if 0
  /* 104 - RIL_REQUEST_VOICE_RADIO_TECH */
QCRIL_LEGACY_EVENT(RIL_REQUEST_VOICE_RADIO_TECH, qcril_qmi_nas_request_radio_tech, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* 109 - RIL_REQUEST_GET_DC_RT_INFO */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_DC_RT_INFO, qcril_qmi_nas_request_get_dc_rt_info, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

#if 0
  /* 19 - RIL_REQUEST_SIGNAL_STRENGTH */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SIGNAL_STRENGTH, qcril_qmi_nas_request_signal_strength, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 20 - RIL_REQUEST_VOICE_REGISTRATION_STATE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_VOICE_REGISTRATION_STATE, qcril_qmi_nas_request_registration_state, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 21 - RIL_REQUEST_DATA_REGISTRATION_STATE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_DATA_REGISTRATION_STATE, qcril_qmi_nas_request_data_registration_state, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 22 - RIL_REQUEST_OPERATOR */
QCRIL_LEGACY_EVENT(RIL_REQUEST_OPERATOR, qcril_qmi_nas_request_operator, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 61 - RIL_REQUEST_SCREEN_STATE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SCREEN_STATE, qcril_qmi_nas_request_screen_state, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 138 - RIL_REQUEST_SEND_DEVICE_STATE
     Introduced in RIL Version 15 */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SEND_DEVICE_STATE, qcril_qmi_nas_request_send_device_state, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 139 - RIL_REQUEST_SET_UNSOLICITED_RESPONSE_FILTER
     Introduced in RIL Version 15 */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_UNSOLICITED_RESPONSE_FILTER, qcril_qmi_nas_request_set_unsol_response_filter, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 75 - RIL_REQUEST_GET_NEIGHBORING_CELL_IDS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_NEIGHBORING_CELL_IDS, qcril_qmi_nas_get_neighboring_cell_ids, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 76 - RIL_REQUEST_SET_LOCATION_UPDATES */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_LOCATION_UPDATES, qcril_qmi_nas_set_location_updates, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* QCRIL_EVT_RIL_REQUEST_GET_CELL_INFO_LIST */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_CELL_INFO_LIST, qcril_qmi_nas_get_cell_info_list_ncl, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);


#if 0
  /* QCRIL_EVT_RIL_REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* -------------------*
   *        EVENTS      *
   * -------------------*/

  /* QCRIL_EVT_QMI_RIL_POLL_CELL_INFO_LIST */
QCRIL_LEGACY_EVENT(QMI_RIL_POLL_CELL_INFO_LIST, qcril_qmi_nas_poll_cell_info_list, &QCRIL_GRP_CELL_INFO, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_CELL_INFO_LIST_CHANGED_IND */
QCRIL_LEGACY_EVENT(QMI_RIL_CELL_INFO_LIST_CHANGED_IND, qcril_qmi_nas_cell_info_list_changed, &QCRIL_GRP_CELL_INFO, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /**********************************************
   *             CM - Call Services             *
   **********************************************/

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/


  /* -------------------*
   *        EVENTS      *
   * -------------------*/


  /**********************************************
   *           CM - In Band Services            *
   **********************************************/

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/



  /* -------------------*
   *        EVENTS      *
   * -------------------*/


  /**********************************************
   *          CM - Supplemental Services        *
   **********************************************/

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/


  /* -------------------*
   *        EVENTS      *
   * -------------------*/


  /**********************************************
   *          CM - Stats Services               *
   **********************************************/


   /**********************************************
   *                  Other                     *
   **********************************************/

  /* -------------------*
   *     RIL_REQUESTS   *
   * -------------------*/

  /* 38 - RIL_REQUEST_GET_IMEI */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_IMEI, qcril_qmi_nas_dms_request_imei, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 39 - RIL_REQUEST_GET_IMEISV */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_IMEISV, qcril_qmi_nas_dms_request_imeisv, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

#if 0
  /* 53 - RIL_REQUEST_SET_MUTE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_SET_MUTE, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 54 - RIL_REQUEST_GET_MUTE */
QCRIL_LEGACY_EVENT(RIL_REQUEST_GET_MUTE, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* 59 - RIL_REQUEST_OEM_HOOK_RAW */
QCRIL_LEGACY_EVENT(RIL_REQUEST_OEM_HOOK_RAW, NULL, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 60 - RIL_REQUEST_OEM_HOOK_STRINGS */
QCRIL_LEGACY_EVENT(RIL_REQUEST_OEM_HOOK_STRINGS, qcril_other_request_oem_hook_strings, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* 86 - RIL_REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY, qcril_qmi_nas_cdma_validate_and_write_key, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);

#if 0
  /* 99 - RIL_REQUEST_CDMA_SUBSCRIPTION */
QCRIL_LEGACY_EVENT(RIL_REQUEST_CDMA_SUBSCRIPTION, qcril_qmi_nas_request_cdma_subscription, &QCRIL_GRP_ANDROID_RIL_REQ, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif

  /* QCRIL_EVT_PBM_CARD_ERROR */
QCRIL_LEGACY_EVENT(PBM_CARD_ERROR, NULL, &QCRIL_GRP_PBM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_PBM_CARD_INSERTED */
QCRIL_LEGACY_EVENT(PBM_CARD_INSERTED, NULL, &QCRIL_GRP_PBM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_PBM_CARD_INIT_COMPLETED */
QCRIL_LEGACY_EVENT(PBM_CARD_INIT_COMPLETED, NULL, &QCRIL_GRP_PBM, QMI_RIL_ALLOWED_IN_ALL_STATES);


  /* QCRIL_EVT_QMI_REQUEST_EMBMS_ENABLE */
QCRIL_LEGACY_EVENT(QMI_REQUEST_EMBMS_ENABLE, NULL, &QCRIL_GRP_EMBMS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_EMBMS_DISABLE */
QCRIL_LEGACY_EVENT(QMI_REQUEST_EMBMS_DISABLE, NULL, &QCRIL_GRP_EMBMS, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_INIT_ATTACH_APN */
QCRIL_LEGACY_EVENT(QMI_REQUEST_INIT_ATTACH_APN, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_OEM_BASE */
QCRIL_LEGACY_EVENT(OEM_BASE, NULL, &QCRIL_GRP_OEM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_OEM_MAX */
QCRIL_LEGACY_EVENT(OEM_MAX, NULL, &QCRIL_GRP_OEM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_NONE */
QCRIL_LEGACY_EVENT(NONE, NULL, &QCRIL_GRP_NONE, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QMI_RIL_OEM_HOOK_QMI_TUNNELING_SERVICE_VT */
QCRIL_LEGACY_EVENT(QMI_RIL_OEM_HOOK_QMI_TUNNELING_SERVICE_VT, NULL, &QCRIL_GRP_OEM_HOOK, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_POWER_RADIO */
QCRIL_LEGACY_EVENT(QMI_REQUEST_POWER_RADIO, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_SET_SYS_SEL_PREF */
QCRIL_LEGACY_EVENT(QMI_REQUEST_SET_SYS_SEL_PREF, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_MODIFY_INITIATE */
QCRIL_LEGACY_EVENT(QMI_REQUEST_MODIFY_INITIATE, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_MODIFY_CONFIRM */
QCRIL_LEGACY_EVENT(QMI_REQUEST_MODIFY_CONFIRM, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_VOICE_BURST_START_CONT_DTMF */
QCRIL_LEGACY_EVENT(QMI_VOICE_BURST_START_CONT_DTMF, NULL, &QCRIL_GRP_VOICE, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_VOICE_PENDING_MNG_CALLS_REQ_FINISHED */
QCRIL_LEGACY_EVENT(QMI_VOICE_PENDING_MNG_CALLS_REQ_FINISHED, NULL, &QCRIL_GRP_VOICE, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_DISABLE_LTE_TUNE_AWAY */
QCRIL_LEGACY_EVENT(QMI_REQUEST_DISABLE_LTE_TUNE_AWAY, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_SHUTDOWN */
QCRIL_LEGACY_EVENT(QMI_REQUEST_SHUTDOWN, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_SET_SUBS_MODE */
QCRIL_LEGACY_EVENT(QMI_REQUEST_SET_SUBS_MODE, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_ALLOW_DATA */
QCRIL_LEGACY_EVENT(QMI_REQUEST_ALLOW_DATA, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_ALLOW_DATA_WAIT_FOR_CARD_READY */
QCRIL_LEGACY_EVENT(QMI_REQUEST_ALLOW_DATA_WAIT_FOR_CARD_READY, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_ENABLE_LTE_TUNE_AWAY */
QCRIL_LEGACY_EVENT(QMI_REQUEST_ENABLE_LTE_TUNE_AWAY, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_REQUEST_NEIGHBOR_CELL_INFO */
QCRIL_LEGACY_EVENT(QMI_REQUEST_NEIGHBOR_CELL_INFO, NULL, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* -------------------*
   *      CALLBACKS     *
   * -------------------*/

  /* -------------------*
   *        EVENTS      *
   * -------------------*/
  /* QCRIL_EVT_QMI_RIL_PDC_LOAD_CONFIGURATION */
QCRIL_LEGACY_EVENT(QMI_RIL_PDC_LOAD_CONFIGURATION, qcril_qmi_pdc_load_configuration, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_PDC_SELECT_CONFIGURATION */
QCRIL_LEGACY_EVENT(QMI_RIL_PDC_SELECT_CONFIGURATION, qcril_qmi_pdc_select_configuration, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_PDC_LIST_CONFIGURATION */
QCRIL_LEGACY_EVENT(QMI_RIL_PDC_LIST_CONFIGURATION, qcril_qmi_pdc_list_configuration_event_hdlr, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_RIL_PDC_DEACTIVATE_CONFIGURATION */
QCRIL_LEGACY_EVENT(QMI_RIL_PDC_DEACTIVATE_CONFIGURATION, qcril_qmi_pdc_deactivate_configuration, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_PROV_FM_START_STATUS */
QCRIL_LEGACY_EVENT(QMI_PROV_FM_START_STATUS, qcril_qmi_nas_prov_fm_start_status_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_PROV_FM_APPLY_STATUS */
QCRIL_LEGACY_EVENT(QMI_PROV_FM_APPLY_STATUS, qcril_qmi_nas_prov_fm_apply_status_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_PROV_ACTIVATE_SUB_STATUS */
QCRIL_LEGACY_EVENT(QMI_PROV_ACTIVATE_SUB_STATUS, qcril_qmi_nas_prov_activate_sub_status_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_PROV_DEACTIVATE_SUB_STATUS */
QCRIL_LEGACY_EVENT(QMI_PROV_DEACTIVATE_SUB_STATUS, qcril_qmi_nas_prov_deactivate_sub_status_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_PROV_STATUS_CHANGED */
QCRIL_LEGACY_EVENT(QMI_PROV_STATUS_CHANGED, qcril_qmi_nas_prov_status_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_RIL_REQUEST_MANUAL_PROVISIONING */
QCRIL_LEGACY_EVENT(RIL_REQUEST_MANUAL_PROVISIONING, qcril_qmi_prov_manual_provisioning_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_QMI_PROV_UPDATE_ICCID */
QCRIL_LEGACY_EVENT(QMI_PROV_UPDATE_ICCID, qcril_qmi_prov_update_iccid_hndlr, &QCRIL_GRP_PROV, QMI_RIL_ALLOWED_IN_ALL_STATES);

#ifndef QMI_RIL_UTF
  /* QCRIL_EVT_QMI_RIL_PDC_PARSE_DIFF_RESULT */
QCRIL_LEGACY_EVENT(QMI_RIL_PDC_PARSE_DIFF_RESULT, qcril_qmi_pdc_parse_diff_result, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

#endif

  /* -------------------*
   *     UNSOLICITED    *
   * -------------------*/

  /* QCRIL_EVT_RADIO_CONFIG_SOCKET_REQ_SET_CONFIG */
QCRIL_LEGACY_EVENT(RADIO_CONFIG_SOCKET_REQ_SET_CONFIG, qcril_qmi_radio_config_dispatch_set_request, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_RADIO_CONFIG_SOCKET_REQ_GET_CONFIG */
QCRIL_LEGACY_EVENT(RADIO_CONFIG_SOCKET_REQ_GET_CONFIG, qcril_qmi_radio_config_dispatch_get_request, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_INITIALIZE */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_INITIALIZE, qcril_qmi_lte_direct_disc_initialize, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_GET_DEVICE_CAPABILITY */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_GET_DEVICE_CAPABILITY, qcril_qmi_lte_direct_disc_get_device_capability, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_TERMINATE */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_TERMINATE, qcril_qmi_lte_direct_disc_terminate, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_GET_SERVICE_STATUS */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_GET_SERVICE_STATUS, qcril_qmi_lte_direct_disc_get_service_status, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_PUBLISH */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_PUBLISH, qcril_qmi_lte_direct_disc_publish, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_CANCEL_PUBLISH */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_CANCEL_PUBLISH, qcril_qmi_lte_direct_disc_cancel_publish, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_SUBSCRIBE */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_SUBSCRIBE, qcril_qmi_lte_direct_disc_subscribe, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_LTE_DIRECT_DISC_REQ_CANCEL_SUBSCRIBE */
QCRIL_LEGACY_EVENT(LTE_DIRECT_DISC_REQ_CANCEL_SUBSCRIBE, qcril_qmi_lte_direct_disc_cancel_subscribe, &QCRIL_GRP_LTED, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /**********************************************
   *                    PBM                     *
   **********************************************/

  /* -------------------*
   *        EVENTS      *
   * -------------------*/
  /* QCRIL_EVT_PBM_GET_PB_CAPACITY */
QCRIL_LEGACY_EVENT(PBM_GET_PB_CAPACITY, qcril_qmi_pbm_get_pb_capacity_hndlr, &QCRIL_GRP_PBM, QMI_RIL_ALLOWED_IN_ALL_STATES);

  /* QCRIL_EVT_PBM_ASYNC_CALLBACK */
QCRIL_LEGACY_EVENT(PBM_ASYNC_CALLBACK, NULL, &QCRIL_GRP_PBM, QMI_RIL_ALLOWED_IN_ALL_STATES);

QCRIL_LEGACY_EVENT(CLEAN_UP_MODULE, qmi_ril_other_cleanup_module_hndlr, &QCRIL_GRP_DEFAULT, QMI_RIL_ALLOWED_IN_ALL_STATES);


  /* -------------------*
   *     RIL UNSOL INDICATIONS   *
   * -------------------*/

QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_RADIO_STATE_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);

QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_CALL_STATE_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_NEW_SMS, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
//QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_NEW_SMS_STATUS_REPORT, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_NEW_SMS_ON_SIM, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_ON_USSD, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_ON_USSD_REQUEST, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_NITZ_TIME_RECEIVED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_SIGNAL_STRENGTH, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_DATA_CALL_LIST_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_SUPP_SVC_NOTIFICATION, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_SIM_SMS_STORAGE_FULL, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CALL_RING, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_CDMA_NEW_SMS, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
//QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_NEW_BROADCAST_SMS, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CDMA_RUIM_SMS_STORAGE_FULL, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESTRICTED_STATE_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CDMA_CALL_WAITING, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CDMA_OTA_PROVISION_STATUS, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CDMA_INFO_REC, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_OEM_HOOK_RAW, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RINGBACK_TONE, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESEND_INCALL_MUTE, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CDMA_SUBSCRIPTION_SOURCE_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CDMA_PRL_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RIL_CONNECTED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
#if 0
QCRIL_LEGACY_INDICATION(RIL_UNSOL_VOICE_RADIO_TECH_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
#endif
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CELL_INFO_LIST, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_SRVCC_STATE_NOTIFY, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_HARDWARE_CONFIG_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_DC_RT_INFO_CHANGED, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_RADIO_CAPABILITY, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_ON_SS, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_STK_CC_ALPHA_NOTIFY, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_LCEDATA_RECV, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_PCO_DATA, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_MODEM_RESTART, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_CARRIER_INFO_IMSI_ENCRYPTION, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_NETWORK_SCAN_RESULT, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
QCRIL_LEGACY_INDICATION(RIL_UNSOL_KEEPALIVE_STATUS, &QCRIL_GRP_ANDROID_RIL_UNSOL, QMI_RIL_ALLOWED_IN_ALL_STATES);
