// ============================================================================
// Copyright (c) 2019 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
// ============================================================================
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IHavenTokenTestApp_OP_runPFMTests 0

static inline int32_t
IHavenTokenTestApp_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IHavenTokenTestApp_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IHavenTokenTestApp_runPFMTests(Object self)
{
  return Object_invoke(self, IHavenTokenTestApp_OP_runPFMTests, 0, 0);
}



