/******************************************************************************
#  Copyright (c) 2013, 2019 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
  ---------------------------------------------------------------------------

  @file    ril_utf_test_list_qmi_ril.cpp
  @brief   RIL UTF test case function pointer table

  DESCRIPTION
  An array of function pointer type
  All the test case names should be in this table in order to be called
  All test case declarations should go to ril_utf_test_qmi_ril.h
  All test case definitions should go to ril_utf_test_qmi_ril.cpp
  ---------------------------------------------------------------------------
******************************************************************************/
#include "ril_utf_test_qmi_ril.h"
#ifdef RIL_UTF_L_MASTER
#include "ril_utf_test_qmi_ril_L.h"
#endif

func_ptr_t qmi_ril_test_table[] =
{
  // DB test cases
  ril_utf_db_001,
  ril_utf_test_nv_reset_config_001,
#if 0
  // MBN TESTS
  ril_utf_test_mbn_msim_success,
  ril_utf_test_mbn_msim_success_with_iccid_only,
  ril_utf_test_mbn_msim_with_only_card_0_active,
  ril_utf_test_mbn_msim_with_only_card_1_active,
  ril_utf_test_mbn_no_sim_without_hw_mbn_init,
  ril_utf_test_mbn_no_sim_with_hw_mbn_init,
  ril_utf_test_mbn_one_sim_001,
  ril_utf_test_mbn_hw_get_config_fail,
  ril_utf_test_mbn_hw_get_config_ind_with_no_config_id,
  ril_utf_test_mbn_hw_deactivate_config_fail,
  ril_utf_test_mbn_hw_delete_config_fail,
  ril_utf_test_mbn_hw_load_config_fail,
  ril_utf_test_mbn_hw_set_config_fail,
  ril_utf_test_mbn_hw_activate_config_fail,
  ril_utf_test_mbn_1st_sw_get_config_fail,
  ril_utf_test_mbn_1st_sw_get_config_info_fail,
  ril_utf_test_mbn_1st_sw_get_config_info_ind_with_different_version,
  ril_utf_test_mbn_1st_sw_get_config_info_ind_with_different_minor_version,
  ril_utf_test_mbn_1st_sw_get_config_info_ind_with_different_same_version,
  ril_utf_test_mbn_1st_sw_deactivate_config_fail,
  ril_utf_test_mbn_1st_sw_2nd_delete_config_fail,
  ril_utf_test_mbn_1st_sw_load_config_fail,
  ril_utf_test_mbn_1st_sw_set_config_fail,
  ril_utf_test_mbn_2nd_sw_get_config_fail,
  ril_utf_test_mbn_2nd_sw_get_config_info_fail,
  ril_utf_test_mbn_2nd_sw_deactivate_config_fail,
  ril_utf_test_mbn_2nd_sw_2nd_delete_config_fail,
  ril_utf_test_mbn_2nd_sw_load_config_fail,
  ril_utf_test_mbn_2nd_sw_set_config_fail,
  ril_utf_test_mbn_2nd_sw_activate_config_fail,
  ril_utf_test_mbn_nova_sim_with_11_digit_iin,
  ril_utf_test_mbn_nova_sim_with_mcc_mnc,
  ril_utf_test_mbn_msim_wild,
  ril_utf_test_mbn_msim_mcc_mnc_list,
  ril_utf_test_mbn_msim_capability_with_mcc_mnc,
  ril_utf_test_mbn_msim_capability_with_iccid,
  ril_utf_test_mbn_msim_disable_modem_update_fail,
  ril_utf_test_mbn_no_mbn_config,
  ril_utf_test_mbn_no_hw_mbn_file,
  ril_utf_test_mbn_no_sw_mbn_file,
  ril_utf_test_mbn_copy_not_complete,

  // SSR TESTS
  ril_utf_ssr_001,
  ril_utf_ssr_002,
#endif

  // Voice/IMS test cases
  ril_utf_test_mo_call_001,           // CS Voice call
  ril_utf_test_mo_call_002,
  ril_utf_test_mo_call_003,
  ril_utf_test_mo_call_004,
  ril_utf_test_mo_call_005,
  ril_utf_test_mo_call_006,
  ril_utf_test_mo_call_007,
  ril_utf_test_mo_call_008,
  ril_utf_test_mo_call_009,
  ril_utf_test_mt_call_001,
  ril_utf_test_mt_call_002,
  ril_utf_test_mt_call_reject_001,
  ril_utf_test_mo_call_redir_num,
  ril_utf_test_mo_call_speech_codec_ind, // SPEECH_CODEC_INFO_IND for CS call
  ril_utf_test_cs_call_number_handle_in_conn_party_num_tlv,
  ril_utf_test_mo_call_fail_001,
  ril_utf_test_mo_call_fail_002,
  ril_utf_test_mo_call_fail_003,
  ril_utf_test_mo_call_fail_004,
  ril_utf_test_mo_call_fail_005,
  ril_utf_test_mo_call_fail_006,
  ril_utf_test_hangup_fail_001,
  //ril_utf_test_timeout_dial_001,     // Takes 74 seconds to execute!
  ril_utf_setup_answer_001,
  ril_utf_setup_answer_002,
  ril_utf_test_mo_call_dial_modified_to_dial,
  ril_utf_mo_call_with_handover_ind,
  ril_utf_test_voice_call_converted_ss_in_alpha_null_case, // CALL_CONTROL - DIAL converted to SS
  ril_utf_test_mute_001,
  ril_utf_test_set_unsol_cell_info_list_rate_001,

  ril_utf_ims_mo_call_001,  // IMS calls
  ril_utf_ims_mo_call_002,
  ril_utf_ims_mo_call_003,
  ril_utf_ims_mo_call_004,
  ril_utf_ims_mo_call_005,
  ril_utf_ims_mo_call_006,
  ril_utf_ims_mo_call_007,
  ril_utf_ims_mo_call_008,
  ril_utf_ims_mo_call_009,
  ril_utf_ims_mo_call_010,
  ril_utf_ims_mo_call_011,
  ril_utf_ims_mo_call_012,
  //ril_utf_ims_mo_call_013,
  ril_utf_ims_mt_call_001,
  ril_utf_ims_mt_call_002,
  ril_utf_ims_mt_call_003,
  ril_utf_ims_mt_call_004,
  ril_utf_ims_mt_call_005,
  ril_utf_ims_mt_call_006,
  ril_utf_ims_mt_call_007,
  ril_utf_ims_mt_call_008,
  ril_utf_ims_mt_call_009,
  ril_utf_ims_callfailcauseresponse_001,
  ril_utf_ims_callfailcauseresponse_002,
  ril_utf_ims_callfailcauseresponse_003,
  ril_utf_ims_callfailcauseresponse_004,
  ril_utf_ims_callfailcauseresponse_005,
  ril_utf_ims_call_fail_cause,
  ril_utf_ims_call_fail_cause_001,
  ril_utf_ims_call_fail_cause_q850_error_001,
  ril_utf_ims_call_fail_cause_q850_error_002,
  ril_utf_ims_call_fail_cause_q850_error_003,
  ril_utf_ims_call_fail_cause_q850_error_004,
  ril_utf_ims_mo_conf_uri_call_001,
  ril_utf_ims_mo_conf_uri_call_002,
  ril_utf_ims_mo_conf_uri_call_003,
  ril_utf_ims_conf_info_ind_001,
  ril_utf_ims_conf_info_ind_002,
  ril_utf_ims_conf_info_ind_003,
  ril_utf_ims_mt_vt_call_001,
  ril_utf_ims_mt_vt_call_002,
  ril_utf_ims_mt_vt_call_003,
  ril_utf_ims_mt_vt_call_004,
  ril_utf_ims_mt_vt_call_005,
  ril_utf_ims_mt_vt_call_006,
  ril_utf_ims_mt_vt_call_007,
  ril_utf_ims_mt_call_voip_caller_name,  // VoIP caller name
  ril_utf_test_add_participant_failure,     // add_participant failure case
  ril_utf_ims_sups_notification_ind_001,
  ril_utf_ims_sups_notification_ind_002,
  ril_utf_ims_voice_privacy_ind_002,
  ril_utf_ims_vice_dialog_info_001,
  ril_utf_ims_auto_rejected_incoming_call_end_ind_001,
  ril_utf_ims_tty_ind_001,
  ril_utf_ims_mo_precond_vt,
  ril_utf_ims_mo_precond_volte,
  ril_utf_ims_mo_precond_vt_tx,
  ril_utf_ims_mo_precond_vt_rx,
  ril_utf_ims_mt_precond_vt,
  ril_utf_ims_mt_precond_volte,
  ril_utf_ims_mt_precond_vt_tx,
  ril_utf_ims_mt_precond_vt_rx,
  ril_utf_ims_mt_long_number_001, // Long number TLV handling
  ril_utf_ims_mo_long_number_001,
  ril_utf_ims_mo_emergency_dial_001,
  ril_utf_ims_mo_emergency_dial_002,
  ril_utf_ims_mo_emergency_dial_003,
  // SRVCC/DRVCC
  ril_utf_ims_srvcc_mo_call_001,
  ril_utf_ims_srvcc_mo_call_002,
  ril_utf_ims_srvcc_mo_call_003,
  ril_utf_ims_drvcc_mo_call_001,
  // Conf call SRVCC with mid-call support
  ril_utf_ims_srvcc_conf_call_001,
  ril_utf_ims_srvcc_conf_call_002,
  // Conf call SRVCC without mid-call support
  ril_utf_ims_srvcc_conf_call_003,
  ril_utf_ims_srvcc_conf_call_004,
  ril_utf_ims_srvcc_conf_call_005,
  // VOIP over IWLAN
  ril_utf_ims_wlan_mo_call_001,
  ril_utf_ims_wlan_mo_call_002,
  ril_utf_ims_wlan_mo_vt_call_001,
  ril_utf_ims_wlan_mo_vt_tx_call_001,
  ril_utf_ims_voice_info_change_001,
  ril_utf_ims_multi_identity_lines_001,
  ril_utf_ims_multi_identity_lines_002,
  ril_utf_ims_multi_identity_lines_003,
  ril_utf_ims_multi_identity_lines_004,
  // SUPP_SVC_STATUS
  ril_utf_ims_supp_service_status_001,
  ril_utf_ims_supp_service_status_002,
  ril_utf_ims_supp_service_status_003,
  ril_utf_ims_supp_service_status_004,
  ril_utf_ims_supp_service_status_005,
  ril_utf_ims_supp_service_status_006,
  ril_utf_ims_supp_service_status_007,
  ril_utf_ims_supp_service_status_008,
  //ril_utf_ims_supp_service_status_009,
  ril_utf_ims_supp_service_status_010,
  // CLIP
  ril_utf_ims_get_clip_001,
  ril_utf_ims_get_clip_002,
  ril_utf_ims_get_clip_003,
  // COLP
  ril_utf_ims_get_colp_001,
  ril_utf_ims_get_colp_002,
  ril_utf_ims_get_colp_003,
  ril_utf_ims_get_colp_004,
  // CLIR
  ril_utf_ims_get_clir_success,
  ril_utf_ims_get_clir_error,
  ril_utf_get_clir_error,
  // COLR
  ril_utf_ims_colr_success,
  ril_utf_ims_colr_failure,
  // CLIP
  ril_utf_clip_testcase_001,
  ril_utf_clip_testcase_002,
  ril_utf_clip_testcase_003,
  // FACILITY_LOCK
  ril_utf_facility_lock_testcase_001,
  ril_utf_facility_lock_testcase_002,
  ril_utf_facility_lock_testcase_003,
  ril_utf_facility_lock_testcase_004,
  ril_utf_facility_lock_testcase_005,
  ril_utf_facility_lock_testcase_006,
  ril_utf_facility_lock_testcase_007,
  // CALL WAITING
  ril_utf_set_call_waiting_001,
  ril_utf_set_call_waiting_002,
  ril_utf_set_call_waiting_003,
  ril_utf_query_call_waiting_001,
  ril_utf_query_call_waiting_002,
  ril_utf_query_call_waiting_003,
  // TTY
  ril_utf_ril_set_tty_mode_001,
  // TIR
  ril_utf_ims_mt_call_with_tir_mode_001,
  ril_utf_ims_mt_call_with_tir_mode_002,
  ril_utf_ril_set_tty_mode_002,
  ril_utf_ril_get_tty_mode_001,
  ril_utf_ril_get_tty_mode_002,
  ril_utf_ims_set_tty_mode,
  ril_utf_test_dtmf_001,
  ril_utf_test_dtmf_002,
  ril_utf_test_dtmf_003,
  ril_utf_test_dtmf_004,
  ril_utf_test_cdma_burst_dtmf_001,
  ril_utf_test_cdma_burst_dtmf_002,
  ril_utf_test_get_preferred_voice_privacy_001,
  ril_utf_test_get_preferred_voice_privacy_002,
  ril_utf_test_set_preferred_voice_privacy_001,
  ril_utf_test_set_preferred_voice_privacy_002,
  ril_utf_test_set_supp_service_notifications_001,
  ril_utf_test_set_supp_service_notifications_002,
  ril_utf_test_explicit_call_transfer_001,
  ril_utf_test_set_barring_password_001,
  ril_utf_test_set_barring_password_002,
  ril_utf_test_set_barring_password_003,
  ril_utf_test_set_barring_password_004,
  ril_utf_ims_set_supp_svc_notification_001,
  ril_utf_ims_ussd_failed_notification_001,
  ril_utf_ims_ussd_failed_notification_002,
  ril_utf_ims_explicit_call_transfer_001,
  ril_utf_ims_explicit_call_transfer_002,
  ril_utf_ims_explicit_call_transfer_003,
  ril_utf_ims_explicit_call_transfer_004,
  ril_utf_ims_explicit_call_transfer_005,
  ril_utf_ims_explicit_call_transfer_006,
  ril_utf_ims_deflect_call_001,
  ril_utf_ims_deflect_call_002,
  ril_utf_ims_dtmf_001,
  ril_utf_ims_dtmf_002,
  ril_utf_ims_mo_volte_call_sip_uri_001,
  ril_utf_ims_mo_volte_call_sip_uri_002,
  ril_utf_ims_mo_call_001_L,
  ril_utf_ims_mo_call_b2b_001_L,
  ril_utf_ims_mo_conf_001,
  ril_utf_ims_mo_conf_002,
  ril_utf_ims_mo_conf_003,
  ril_utf_ims_mo_conf_004,
  ril_utf_ims_mo_conf_005,
  ril_utf_ims_mo_conf_006,
  ril_utf_ims_mo_conf_001_L,
  ril_utf_ims_mo_conf_002_L,
  ril_utf_ims_mo_conf_003_L,
  ril_utf_ims_mo_conf_004_L,
  ril_utf_ims_mo_conf_005_L,
  ril_utf_ims_mt_call_001_L,
  ril_utf_ims_mo_multi_001_L,
  ril_utf_ims_mo_mt_call_001_L,
  ril_utf_ims_dial_fail_L,
//  ril_utf_ims_no_srv_dial_fail_L,
  ril_utf_ims_sups_notification_ind_L,
  ril_utf_ims_mt_call_mid_call_update_001_L,
  ril_utf_ims_add_participant,
  ril_utf_ims_vt_emergency_call,
  ril_utf_ims_em_vt_connected_as_em_voip,
  ril_utf_ims_em_vt_connected_as_em_cs,
  ril_utf_ims_mo_volte_alert_cap,
  ril_utf_ims_mo_reject_low_battery,
  ril_utf_ims_mt_reject_low_battery,
  ril_utf_ims_mo_call_end_fallback_to_cs,
  ril_utf_ims_mo_call_end_low_battery,
  ril_utf_ims_mo_call_peer_info_001,
  ril_utf_ims_mo_call_peer_info_002,
  ril_utf_ims_modem_silent_redial_001_L,
  ril_utf_ims_modem_silent_redial_002_L,
  ril_utf_ims_mo_call_end_ho_not_feasible,
  ril_utf_ims_alternate_emergency_call_001,
  ril_utf_ims_alternate_emergency_call_002,
  ril_utf_ims_conf_participant_status_001,    // UNSOL_PARTICIPANT_STATUS_INFO test cases
  ril_utf_ims_conf_participant_status_002,
  ril_utf_ims_end_call_err_malformed_001,
  ril_utf_ims_end_call_err_malformed_002,
  ril_utf_ims_mo_call_called_party_alerting,
  ril_utf_ims_mo_call_end_imm_orig,
  ril_utf_test_voice_call_converted_ussd_in_alpha_null_case,
  ril_utf_test_wrong_fail_cause_001,
  ril_utf_ims_mo_call_end_reason_text, // End Reason Text
  ril_utf_ims_mt_reject_cases,
  ril_utf_ims_em_vt_downgrade_em_voip,
  ril_utf_ims_vt_downgrade_voip,
  ril_utf_ims_mo_vt_nodir_media_paused_L,
  ril_utf_ims_mo_call_silent_redial_w_orig_fail,
  ril_utf_ims_encrypted_call_001,      // Encrypted VoLTE call test cases
  ril_utf_ims_encrypted_call_002,      // Encrypted VoLTE call test cases
  ril_utf_ims_encrypted_call_003,      // Encrypted VoLTE call test cases
  ril_utf_ims_mo_precond_vt_L,                    // VT Preconditions
  ril_utf_ims_mo_precond_vt_media_paused_L,       // VT Preconditions
  ril_utf_ims_mo_precond_vt_retry_needed_L,       // VT Preconditions
  ril_utf_ims_mo_precond_voice_audio_suspended_L, // VT Preconditions
  ril_utf_ims_mo_volte_hold_001,
  ril_utf_ims_mo_volte_hold_002,
  ril_utf_ims_mo_volte_hold_003,
  ril_utf_ims_mo_volte_hold_004,
  ril_utf_ims_mo_volte_hold_005,
  ril_utf_ims_mo_volte_hold_006,
  ril_utf_ims_mo_volte_resume_001,
  ril_utf_ims_mo_volte_resume_002,
  ril_utf_ims_mo_volte_resume_003,
  ril_utf_ims_mo_volte_resume_004,
  ril_utf_ims_mo_volte_resume_005,
  ril_utf_ims_mo_volte_vice_call_pull_001,
  ril_utf_ims_mo_volte_display_text_001,
  ril_utf_ims_mo_volte_dial_retries_001,
  ril_utf_ims_mo_volte_additional_call_info_001,
  ril_utf_ims_mo_volte_upgrade_vt_001,
  ril_utf_ims_mo_volte_upgrade_vt_002,
  ril_utf_ims_mo_volte_upgrade_vt_003,
  ril_utf_ims_mo_volte_upgrade_vt_004,
  ril_utf_ims_mo_volte_upgrade_vt_005,
  ril_utf_ims_mo_volte_upgrade_vt_006,
  ril_utf_ims_mo_volte_upgrade_vt_tx_001,
  ril_utf_ims_mo_volte_upgrade_vt_rx_001,
  ril_utf_ims_mo_volte_upgrade_rtt_001,
  ril_utf_ims_cancel_modify_call_001,
  ril_utf_ims_cancel_modify_call_002,
  ril_utf_ims_mo_volte_remote_upgrade_vt_001,
  ril_utf_ims_mo_volte_remote_upgrade_vt_002,
  ril_utf_ims_mo_volte_remote_upgrade_vt_003,
  ril_utf_ims_mo_volte_remote_upgrade_vt_004,
  ril_utf_ims_mo_volte_remote_upgrade_vt_005,
  ril_utf_ims_mo_volte_remote_upgrade_vt_006,
  ril_utf_ims_mo_vt_downgrade_volte_001,
  ril_utf_ims_mo_vt_downgrade_volte_002,
  ril_utf_ims_mo_vt_downgrade_vt_tx_001,
  ril_utf_ims_mo_vt_downgrade_vt_rx_001,
  ril_utf_ims_mo_vt_downgrade_vt_nodir_001,
  ril_utf_ims_mo_vt_remote_downgrade_volte_001,
  ril_utf_ims_mo_vt_remote_downgrade_volte_002,
  ril_utf_ims_mo_vt_remote_downgrade_vt_tx_001,
  ril_utf_ims_mo_vt_remote_downgrade_vt_rx_001,
  ril_utf_ims_mo_vt_remote_downgrade_vt_nodir_001,
  ril_utf_ims_volte_conf_call_upgrade_vt_001,
  ril_utf_ims_volte_conf_call_remote_upgrade_vt_001,
  ril_utf_ims_vt_conf_call_downgrade_voip_001,

  ril_utf_ims_mt_call_display_text_001,
  ril_utf_ims_mt_call_child_number_001,
  ril_utf_ims_mt_call_child_number_002,

  ril_utf_ims_mo_volte_handover_001,
  ril_utf_ims_mo_volte_handover_002,

  ril_utf_ims_set_call_waiting_001,
  ril_utf_ims_set_call_waiting_002,
  ril_utf_ims_set_call_waiting_003,
  ril_utf_ims_query_call_waiting_001,
  ril_utf_ims_query_call_waiting_002,
  ril_utf_ims_query_call_waiting_003,
  ril_utf_ims_query_call_waiting_004,
  ril_utf_query_call_forward_status_001,
  ril_utf_query_call_forward_status_002,
  ril_utf_query_call_forward_status_003,
  ril_utf_query_call_forward_status_004,
  ril_utf_query_call_forward_status_005,
  ril_utf_ims_query_call_forward_status_001,
  ril_utf_ims_query_call_forward_status_002,
  ril_utf_ims_query_call_forward_status_003,
  ril_utf_ims_query_call_forward_status_004,
  ril_utf_ims_query_call_forward_status_005,
  ril_utf_ims_query_call_forward_status_006,
  ril_utf_ims_query_call_forward_status_007,
  ril_utf_set_call_forward_status,
  ril_utf_ims_call_forwarding_status,
  ril_utf_ims_timer_call_forwarding_status,
  ril_utf_ims_set_call_forward_status_001,
  ril_utf_ims_set_call_forward_status_002,
  ril_utf_ims_set_call_forward_status_003,
  ril_utf_ims_set_call_forward_status_004,
  ril_utf_ims_set_call_forward_status_005,
  ril_utf_ims_set_call_forward_status_006,
  ril_utf_ims_set_call_forward_status_007,

  ril_utf_test_send_ussd_001,                 // USSD test cases
  ril_utf_test_send_ussd_002,
  ril_utf_test_send_ussd_003,
  ril_utf_test_send_ussd_004,
  ril_utf_test_send_ussd_005,
  ril_utf_test_send_ussd_006,
  ril_utf_test_send_ussd_007,
  ril_utf_test_send_ussd_008,

  ril_utf_ims_set_and_get_wifi_call_pref,

  ril_utf_test_last_call_failcause,
  ril_utf_test_hangup_001,             // HANGUP_FOREGROUND_RESUME_BACKGROUND to resume HELD call
  ril_utf_test_mo_call_hangup_before_cc_in_prog,
  ril_utf_test_mo_call_hangup_before_dial_resp,
  ril_utf_test_reject_cause_21_501,
  ril_utf_test_reject_cause_21_001,   // Passes if persist.vendor.radio.reject_cause_21 == 0
  ril_utf_test_reject_cause_21_002,
  ril_utf_test_reject_cause_21_003,
  ril_utf_test_reject_cause_21_503,
  ril_utf_test_reject_cause_21_004,
  ril_utf_test_reject_cause_21_504,
  ril_utf_test_hangup_waiting_or_background_001,
  ril_utf_test_hangup_waiting_or_background_002,
  // CDMA Voice call test cases
  ril_utf_test_cdma_mo_call_remote_name,
  ril_utf_test_cdma_mt_call_001,
  ril_utf_test_cdma_info_rec_001,
  ril_utf_test_cdma_mo_call_and_eme_call_001,
  ril_utf_test_cdma_mo_call_and_eme_call_002,
  ril_utf_test_cdma_mo_call_and_eme_call_003,
  ril_utf_test_cdma_otasp_001,
  ril_utf_test_supp_srv_notify_001,
  ril_utf_test_supp_srv_notify_002,
  ril_utf_test_uus_info_ind_001,
  ril_utf_test_voice_privacy_001,

  ril_utf_stk_cc_dial_modified_to_ss_001,
  ril_utf_stk_cc_dial_modified_to_ss_002,
  ril_utf_stk_cc_dial_modified_to_ss_003,
  ril_utf_stk_cc_set_call_forward_ss_modified_to_ss_001,
  ril_utf_stk_cc_set_call_forward_ss_modified_to_ss_002,
  ril_utf_stk_cc_set_call_forward_ss_modified_to_ussd_001,
  ril_utf_stk_cc_set_call_forward_ss_modified_to_ussd_002,
  ril_utf_stk_cc_query_clip_ss_modified_to_ussd_001,
  ril_utf_stk_cc_query_clip_ss_modified_to_ussd_002,
  ril_utf_stk_cc_send_ussd_ussd_modified_to_ss_001,

  ril_utf_test_set_local_call_hold_001,
  ril_utf_oemhook_unsol_cdma_burst_dtmf_001,
  ril_utf_oemhook_unsol_cdma_cont_dtmf_001,
  ril_utf_oemhook_unsol_nss_release_001,
  ril_utf_oemhook_unsol_extended_dbm_intl_001,

#if 0
  ril_utf_ims_wifi_calling_status_success,    // Get/set wifi calling status
  ril_utf_ims_wifi_calling_status_failure,

  //Ims Config items
//  ril_utf_ims_set_and_get_voip_config_items_L,
  ril_utf_ims_set_and_get_user_config_items_L,
  ril_utf_ims_set_and_get_sip_config_items_L,
//  ril_utf_ims_set_and_get_reg_mgr_extended_config_items_L,
//  ril_utf_ims_set_and_get_client_provisioning_config_items_L,
  ril_utf_ims_set_and_get_qipcall_config_items_L,
  ril_utf_ims_set_and_get_sms_config_items_L,
  ril_utf_ims_set_and_get_presence_config_items_L,
#endif

#if 0
  ril_utf_test_mo_call_screen_state_change,
  ril_utf_ims_mo_call_screen_state_change_L,
  ril_utf_ims_mt_call_srvcc_screen_state_change_L,
  ril_utf_ims_mt_call_screen_state_change_L,
  ril_utf_ssr_active_mo_volte,         // SSR when IMS call active
  ril_utf_ssr_active_mo_cs_call,       // SSR when CS call active
#endif
//csvt decommitted  ril_utf_mo_csvt_call_L,                     // CSVT
//csvt decommitted  ril_utf_mt_csvt_call_L,                     // CSVT
  // SSR when CS/IMS/CSVT calls
//csvt  //ril_utf_ssr_active_mo_csvt,

/// THE FOLLOWING TESTS CAUSE TOO MUCH DELAY TO BE RUN AS IS ///
/// THE FOLLOWING TESTS CAUSE TOO MUCH DELAY TO BE RUN AS IS ///
  /*
  ril_utf_test_mo_call_no_origination_indication,
  ril_utf_test_mo_call_no_origination_indication_for_70_secs,
  ril_utf_test_mo_call_no_dial_resp_for_70_secs,
  ril_utf_test_mo_call_no_origination_indication_for_74_secs,
  ril_utf_test_mo_call_no_dial_resp_for_74_secs,
  ril_utf_test_mo_call_delay_in_origination_indication,
  ril_utf_test_mo_call_delay_in_dial_resp,
  */
///  END OF TESTS THAT CAUSE LARGE TIME DELAY //////

  // Message waiting indication
  ril_utf_ims_mwi_ind_01,
  ril_utf_ims_mwi_ind_02,
  ril_utf_ims_mwi_ind_03,

  // Emergency Callback mode
  ril_utf_ims_emergency_call_001,
  ril_utf_ims_emergency_call_002,
  ril_utf_ims_emergency_call_003,
  ril_utf_ims_exit_ecbm_001,

  ril_utf_test_ims_sub_config_001,
  ril_utf_test_ims_sub_config_002,
  ril_utf_test_ims_sub_config_003,

#ifdef RIL_UTF_L_MASTER
#if 0
  // MSIM test cases
  ril_utf_msim_dsds_001,
  ril_utf_msim_dsds_secondary_001,
  ril_utf_msim_wcdma_default_allow_data_true,
  ril_utf_msim_wcdma_default_allow_data_true_fail,
  ril_utf_msim_wcdma_default_allow_data_false,
  ril_utf_msim_wcdma_default_allow_data_true_then_false,
  ril_utf_msim_wcdma_default_allow_data_false_then_true,
  ril_utf_msim_wcdma_default_allow_data_true_then_true,
  ril_utf_msim_wcdma_default_indication_first_allow_data_true,
  ril_utf_msim_wcdma_on_demand_allow_data_true,
  ril_utf_msim_wcdma_on_demand_allow_data_true_fail,
  ril_utf_msim_wcdma_on_demand_allow_data_false,
  ril_utf_msim_wcdma_on_demand_allow_data_true_then_false,
  ril_utf_msim_wcdma_on_demand_allow_data_false_then_true,
  ril_utf_msim_wcdma_on_demand_allow_data_true_then_true,
  ril_utf_msim_wcdma_on_demand_indication_first_allow_data_true,
  ril_utf_msim_1x_default_allow_data_true,
  ril_utf_msim_1x_default_allow_data_false,
  ril_utf_msim_1x_on_demand_allow_data_true,
  ril_utf_msim_1x_on_demand_allow_data_false,
  ril_utf_msim_1x_on_demand_indication_first_allow_data_ture_1,
  ril_utf_msim_1x_on_demand_indication_first_allow_data_ture_2,
  ril_utf_msim_1x_on_demand_indication_first_allow_data_ture_3,
  ril_utf_msim_1x_on_demand_indication_first_allow_data_ture_4,
  ril_utf_msim_oos_default_allow_data_true,
  ril_utf_msim_oos_default_allow_data_false,
  ril_utf_msim_oos_on_demand_allow_data_true,
  ril_utf_msim_oos_on_demand_allow_data_false,
#endif
#endif
  // SMS TESTS
  ril_utf_sms_mo_001,
  ril_utf_sms_mt_001,
  ril_utf_sms_mt_002, //(causes utf to hang occasionally)
  ril_utf_sms_mt_003,
  ril_utf_sms_mt_004,

  ril_utf_sms_delete_sms_on_sim_001,
  ril_utf_sms_delete_cdma_sms_on_ruim_001,
  ril_utf_sms_verify_single_page_gsm_cmas,
  ril_utf_sms_verify_single_page_lte_cmas,
  ril_utf_sms_verify_single_page_lte_cmas_with_wac,
  ril_utf_sms_verify_multi_page_gsm_cmas,
  ril_utf_sms_verify_multi_page_lte_cmas,
// OEM hook tests
//  ril_utf_oem_testcase_001,

  // IMS SMS TESTS
  ril_utf_ims_mo_3gpp_sms_001,
  ril_utf_ims_mo_3gpp_sms_002,
  ril_utf_ims_mo_3gpp_sms_003,
  ril_utf_ims_mt_3gpp_sms_001,
  ril_utf_ims_mt_3gpp_sms_002,
  ril_utf_ims_mt_3gpp_sms_003,
  ril_utf_ims_mt_3gpp_sms_004,
  ril_utf_ims_mt_3gpp_sms_005,

  // Other SMS Module Tests
  ril_utf_get_smsc_address_001,
  ril_utf_gsm_sms_broadcast_activation_001,
  ril_utf_cdma_sms_broadcast_activation_001,
  ril_utf_report_sms_memory_status_001,
  ril_utf_get_gsm_broadcast_config_001,
  ril_utf_set_gsm_broadcast_config_001,
  ril_utf_get_cdma_broadcast_config_001,
  ril_utf_set_cdma_broadcast_config_001,
  ril_utf_write_sms_to_sim_001,
  ril_utf_unsol_sms_memory_full_001,
  ril_utf_unsol_sms_memory_full_002,

  qmi_ril_test_proactive_call_control_Voice_001,
  //qmi_ril_test_proactive_call_control_WMS_001,
  ril_utf_test_nw_state_chg_001,

#ifndef RIL_UTF_L_MASTER
  // Test case for new feature AUTOM
  ril_utf_feature_autom_001,

// RETROSPECTIVE GERRITS TEST FOR BOULDER, SD
  ril_utf_retro_gerrit_355643_001,
  ril_utf_retro_gerrit_355643_002,
  ril_utf_retro_gerrit_355643_003,
  ril_utf_retro_gerrit_355643_004,
  ril_utf_retro_gerrit_253102_001,
  ril_utf_retro_gerrit_253102_002,
  ril_utf_retro_gerrit_260696_001,
  ril_utf_retro_gerrit_318335_001,
//csvt  //ril_utf_retro_gerrit_368730_001,
//csvt  ril_utf_retro_gerrit_368730_002,
  ril_utf_retro_gerrit_284454_001,
  ril_utf_retro_gerrit_347631_001,
  ril_utf_retro_gerrit_338798_001,
  ril_utf_retro_gerrit_338798_002,
  ril_utf_retro_gerrit_334432_001,
  ril_utf_retro_gerrit_334432_002,
  ril_utf_retro_gerrit_219098_001,
#endif
  ril_utf_retro_gerrit_391289_001,
  ril_utf_retro_gerrit_391289_002,
//  ril_utf_retro_gerrit_275073_001,
  ril_utf_retro_gerrit_275073_002,
  ril_utf_retro_gerrit_338792_001,
  ril_utf_retro_gerrit_312517_001,

  ril_utf_retro_gerrit_355735_001, //TODO: why does this take 1 sec to run?

  //NAS Tests
  ril_utf_test_system_selection_preference,
  ril_utf_test_oem_request_cdma_set_subscription_source_testcase_1,
  ril_utf_test_oem_request_cdma_set_subscription_source_testcase_2,
  ril_utf_test_cdma_set_subscription_source_1,
  ril_utf_test_cdma_set_subscription_source_2,
  ril_utf_test_cdma_set_subscription_source_3,
  ril_utf_test_cdma_set_subscription_source_4,
  ril_utf_test_cdma_get_subscription_source_1,
  ril_utf_test_cdma_get_subscription_source_2,
  ril_utf_test_cdma_get_subscription_source_3,
  ril_utf_test_cdma_get_subscription_source_4,
  ril_utf_test_cdma_set_roaming_preference_1,
  ril_utf_test_cdma_set_roaming_preference_2,
  ril_utf_test_cdma_set_roaming_preference_3,
//  ril_utf_test_cdma_set_roaming_preference_4,
  ril_utf_test_cdma_query_roaming_preference_1,
  ril_utf_test_cdma_query_roaming_preference_2,
  ril_utf_test_cdma_query_roaming_preference_3,
  ril_utf_test_cdma_query_roaming_preference_4,
  ril_utf_test_consecutive_set_preferred_network_type_testcase_1,
  ril_utf_test_consecutive_set_preferred_network_type_testcase_2,
  ril_utf_test_set_preferred_network_type_resp_failure,
#ifdef UTF_DELAY_TEST_CASE //This test case execution will take 60sec as QCRIL will wait for IND and send Failure response to ATel from Timer Handler
  ril_utf_test_set_preferred_network_type_without_ind,
#endif
  ril_utf_test_get_preferred_network_type,
  ril_utf_test_get_preferred_network_type_failure,
  ril_utf_test_voice_radio_tech_testcase_1,
  ril_utf_test_voice_radio_tech_testcase_2,
  ril_utf_test_voice_radio_tech_testcase_3,
  ril_utf_test_voice_radio_tech_testcase_4,
  ril_utf_test_voice_radio_tech_testcase_5,
  ril_utf_test_voice_radio_tech_testcase_6,
  ril_utf_test_voice_radio_tech_testcase_7,
#ifdef RIL_UTF_L_MASTER
//  ril_utf_test_voice_radio_tech_testcase_8,
#endif
  ril_utf_test_voice_radio_tech_testcase_9,
  ril_utf_test_voice_radio_tech_testcase_10,
  ril_utf_test_voice_radio_tech_testcase_11,
  ril_utf_test_voice_radio_tech_testcase_12,
  ril_utf_test_voice_radio_tech_testcase_13,
  ril_utf_test_voice_radio_tech_testcase_14,
  ril_utf_test_voice_radio_tech_testcase_15,
  ril_utf_test_voice_radio_tech_testcase_16,
#ifdef RIL_UTF_L_MASTER
  ril_utf_test_voice_radio_tech_testcase_17,
  ril_utf_test_voice_radio_tech_testcase_18,
  ril_utf_test_voice_radio_tech_testcase_19,
  ril_utf_test_voice_radio_tech_testcase_20,
#endif
  ril_utf_test_voice_radio_tech_testcase_21,
#ifdef RIL_UTF_L_MASTER
//  ril_utf_test_voice_radio_tech_testcase_22,
//  ril_utf_test_voice_radio_tech_testcase_23,
  ril_utf_test_voice_radio_tech_testcase_24,
  ril_utf_test_voice_radio_tech_testcase_25,
  ril_utf_test_voice_radio_tech_testcase_26,
  ril_utf_test_voice_radio_tech_testcase_27,
  ril_utf_test_voice_radio_tech_testcase_28_1,
  ril_utf_test_voice_radio_tech_testcase_28_2,
  ril_utf_test_voice_radio_tech_testcase_28_3,
  ril_utf_test_voice_radio_tech_testcase_28_4,
  ril_utf_test_voice_radio_tech_testcase_29_1,
  ril_utf_test_voice_radio_tech_testcase_29_2,
  ril_utf_test_voice_radio_tech_testcase_29_3,
  ril_utf_test_voice_radio_tech_testcase_29_4,
  ril_utf_test_voice_radio_tech_testcase_30,
  ril_utf_test_voice_radio_tech_testcase_31,
  ril_utf_test_voice_radio_tech_testcase_32_1,
  ril_utf_test_voice_radio_tech_testcase_32_2,
  ril_utf_test_voice_radio_tech_testcase_33_1,
  ril_utf_test_voice_radio_tech_testcase_33_2,
  ril_utf_test_voice_radio_tech_testcase_34,
  ril_utf_test_voice_radio_tech_testcase_35,
  ril_utf_test_voice_radio_tech_testcase_36,
  ril_utf_test_voice_radio_tech_testcase_37,
  ril_utf_test_voice_radio_tech_testcase_38,
  ril_utf_test_voice_radio_tech_testcase_39,
  //ril_utf_test_voice_radio_tech_testcase_40,
  ril_utf_test_voice_radio_tech_testcase_41,
#ifndef QMI_RIL_HAL_UTF
  ril_utf_test_voice_radio_tech_testcase_42,
  ril_utf_test_voice_radio_tech_testcase_43,
  ril_utf_test_voice_radio_tech_testcase_44,
  ril_utf_test_voice_radio_tech_testcase_45,
  ril_utf_test_voice_radio_tech_testcase_46,
  ril_utf_test_voice_radio_tech_testcase_47,
#endif
#endif
  ril_utf_test_voice_registration_state_testcase_1,
  ril_utf_test_voice_registration_state_testcase_2,
  ril_utf_test_voice_registration_state_testcase_3,
  ril_utf_test_voice_registration_state_testcase_4,
  ril_utf_test_voice_registration_state_testcase_5,
//  ril_utf_test_voice_registration_state_testcase_6,
  ril_utf_test_voice_registration_state_testcase_7,
  ril_utf_test_voice_registration_state_testcase_8,
  ril_utf_test_voice_registration_state_testcase_9,
  ril_utf_test_voice_registration_state_testcase_10,
//  ril_utf_test_voice_registration_state_testcase_11,
  ril_utf_test_voice_registration_state_testcase_12,
  ril_utf_test_voice_registration_state_testcase_13,
  ril_utf_test_voice_registration_state_testcase_14,
  ril_utf_test_voice_registration_state_testcase_15,
//  ril_utf_test_voice_registration_state_testcase_16,
  ril_utf_test_voice_registration_state_testcase_17,
  ril_utf_test_voice_registration_state_testcase_18,
  ril_utf_test_voice_registration_state_testcase_19,
  ril_utf_test_voice_registration_state_testcase_20,
//  ril_utf_test_voice_registration_state_testcase_21,
  ril_utf_test_voice_registration_state_testcase_22,
  ril_utf_test_voice_registration_state_testcase_23,
  ril_utf_test_voice_registration_state_testcase_24,
  ril_utf_test_voice_registration_state_testcase_25,
//  ril_utf_test_voice_registration_state_testcase_26,
  ril_utf_test_voice_registration_state_testcase_27,
  ril_utf_test_voice_registration_state_testcase_28,
  ril_utf_test_voice_registration_state_testcase_29,
  ril_utf_test_voice_registration_state_testcase_30,
  ril_utf_test_voice_registration_state_testcase_31,
  ril_utf_test_voice_registration_state_testcase_32,
  ril_utf_test_voice_registration_state_testcase_33,
  ril_utf_test_voice_registration_state_testcase_34,
  ril_utf_test_voice_registration_state_testcase_35,
  ril_utf_test_voice_registration_state_testcase_36,
  ril_utf_test_voice_registration_state_testcase_37,
  ril_utf_test_voice_registration_state_testcase_38,
  ril_utf_test_voice_registration_state_testcase_39,
  ril_utf_test_voice_registration_state_testcase_40,
  ril_utf_test_voice_registration_state_testcase_41,
  ril_utf_test_voice_registration_state_testcase_42,
  ril_utf_test_voice_registration_state_testcase_43,
//  ril_utf_test_voice_registration_state_testcase_44,
//  ril_utf_test_voice_registration_state_testcase_45,
//  ril_utf_test_data_registration_state_testcase_1,
  ril_utf_test_data_registration_state_testcase_2,
  ril_utf_test_data_registration_state_testcase_3,
  ril_utf_test_data_registration_state_testcase_4,
  ril_utf_test_data_registration_state_testcase_5,
  ril_utf_test_data_registration_state_testcase_6,
  ril_utf_test_data_registration_state_testcase_7,
  ril_utf_test_data_registration_state_testcase_8,
  //ril_utf_test_data_registration_state_testcase_9,
  ril_utf_test_data_registration_state_testcase_10,
  //ril_utf_test_data_registration_state_testcase_11,
  //ril_utf_test_data_registration_state_testcase_12,
  ril_utf_test_data_registration_state_testcase_13,
  ril_utf_test_data_registration_state_testcase_14,
  ril_utf_test_data_registration_state_testcase_15,
  ril_utf_test_data_registration_state_testcase_16,
  ril_utf_test_data_registration_state_testcase_17,
  ril_utf_test_data_registration_state_testcase_18,
  ril_utf_test_operator_name_testcase_1,
  ril_utf_test_operator_name_testcase_2,
  ril_utf_test_operator_name_testcase_3,
  ril_utf_test_operator_name_testcase_4,
  ril_utf_test_operator_name_testcase_5,
  ril_utf_test_operator_name_testcase_6,
//  ril_utf_test_operator_name_testcase_7,
//  ril_utf_test_operator_name_testcase_8,
//  ril_utf_test_operator_name_testcase_9,
  ril_utf_test_operator_name_testcase_10,
  ril_utf_test_operator_name_testcase_11,
  ril_utf_test_operator_name_testcase_12,
  ril_utf_test_operator_name_testcase_13,
  ril_utf_test_operator_name_testcase_14,
  ril_utf_test_operator_name_testcase_15,
  ril_utf_test_operator_name_testcase_16,
  ril_utf_test_operator_name_testcase_17,
  ril_utf_test_operator_name_testcase_18,
  ril_utf_test_operator_name_testcase_19,
  ril_utf_test_operator_name_testcase_20,
  ril_utf_test_operator_name_testcase_21,
  ril_utf_test_operator_name_testcase_22,
  ril_utf_test_operator_name_testcase_23,
  ril_utf_test_operator_name_testcase_24,
  ril_utf_test_operator_name_testcase_25,
  ril_utf_test_operator_name_testcase_26,
  ril_utf_test_operator_name_testcase_27,

  // these tests need a different boot test case because they are operation mode sglte
  ril_utf_test_operator_name_testcase_28,
  ril_utf_test_operator_name_testcase_29,
  ril_utf_test_operator_name_testcase_30,
  ril_utf_test_operator_name_testcase_31,
  ril_utf_test_operator_name_testcase_32,
  ril_utf_test_operator_name_testcase_33,
  ril_utf_test_operator_name_testcase_34,
  ril_utf_test_operator_name_testcase_35,
  ril_utf_test_operator_name_testcase_36,
  ril_utf_test_operator_name_testcase_37,

  ril_utf_test_operator_name_testcase_38,
  ril_utf_test_operator_name_testcase_39,
  ril_utf_test_operator_name_testcase_40,
  ril_utf_test_operator_name_testcase_41,
  ril_utf_test_operator_name_testcase_42,
  ril_utf_test_operator_name_testcase_43,
  ril_utf_test_operator_name_testcase_44,
  ril_utf_test_operator_name_testcase_45,
  ril_utf_test_operator_name_testcase_46,
  ril_utf_test_operator_name_testcase_47,
  ril_utf_test_operator_name_testcase_48,
  ril_utf_test_operator_name_testcase_49,
  ril_utf_test_operator_name_testcase_50,
  ril_utf_test_query_network_scan_testcase_1,
  ril_utf_test_query_network_scan_testcase_2,
  ril_utf_test_query_network_scan_testcase_3,
#ifndef QMI_RIL_HAL_UTF
  ril_utf_test_query_network_scan_testcase_4, //This test case is not applicable for qcril-hal as RAT_ON=legacy is not supported
#endif
  ril_utf_test_query_network_scan_testcase_5,
  ril_utf_test_query_network_scan_testcase_6,
  ril_utf_test_signal_strength_testcase_1,
  ril_utf_test_signal_strength_testcase_2,
//  ril_utf_test_signal_strength_testcase_3,
//  ril_utf_test_signal_strength_testcase_4,
  ril_utf_test_signal_strength_testcase_5,
  ril_utf_test_signal_strength_testcase_6,
  ril_utf_test_signal_strength_testcase_7,
  ril_utf_test_signal_strength_testcase_8,
//  ril_utf_test_signal_strength_testcase_9,
//  ril_utf_test_signal_strength_testcase_10,
  ril_utf_test_signal_strength_testcase_11,
  ril_utf_test_signal_strength_testcase_12,
  ril_utf_test_signal_strength_testcase_13,
  ril_utf_test_signal_strength_testcase_14,
//  ril_utf_test_signal_strength_testcase_15,
//  ril_utf_test_signal_strength_testcase_16,
  ril_utf_test_signal_strength_testcase_17,
  ril_utf_test_signal_strength_testcase_18,
  ril_utf_test_signal_strength_testcase_19,
  ril_utf_test_signal_strength_testcase_20,
  ril_utf_test_signal_strength_testcase_21,
  ril_utf_test_signal_strength_testcase_22,
  ril_utf_test_signal_strength_testcase_23,
  ril_utf_test_signal_strength_testcase_24,
//  ril_utf_test_signal_strength_testcase_25,
//  ril_utf_test_signal_strength_testcase_26,
  ril_utf_test_signal_strength_testcase_27,
  ril_utf_test_signal_strength_testcase_28,
  ril_utf_test_signal_strength_testcase_29,
  ril_utf_test_signal_strength_testcase_30,
  ril_utf_test_signal_strength_testcase_31,

  ril_utf_test_carrier_aggregation_ind_001,

  ril_utf_test_ims_registration_state_testcase_1,
  ril_utf_test_ims_registration_state_testcase_2,
  ril_utf_test_ims_registration_state_testcase_3,
  ril_utf_test_ims_registration_state_testcase_4,
  ril_utf_test_ims_registration_state_testcase_5,
  ril_utf_test_ims_registration_state_testcase_6,
  ril_utf_test_ims_registration_state_testcase_7,

  ril_utf_ims_registration_state_001,
  ril_utf_ims_registration_state_002,
  ril_utf_test_imsa_geolocation_001,          // IMS GEO LOCATION test cases
  ril_utf_test_imsa_geolocation_002,
  ril_utf_test_imsa_geolocation_003,
  ril_utf_ims_reg_state_change_001,           // IMS Reg state change test cases
  ril_utf_ims_reg_state_change_002,
  ril_utf_ims_reg_state_change_003,
  ril_utf_ims_reg_state_change_004,
  ril_utf_ims_reg_state_change_005,
  ril_utf_ims_reg_state_change_006,
  ril_utf_ims_reg_state_change_007,
  ril_utf_ims_reg_state_change_008,
  ril_utf_ims_reg_state_change_009,
  ril_utf_ims_srv_status_update_001,           // IMS SRV STATUS req/indications
  ril_utf_ims_srv_status_update_002,
  ril_utf_ims_srv_status_update_003,
  ril_utf_ims_srv_status_update_004,
  ril_utf_ims_set_service_status_001,
  ril_utf_ims_set_service_status_002,
  ril_utf_ims_set_service_status_003,
  ril_utf_ims_set_service_status_004,
  ril_utf_ims_set_service_status_005,
  ril_utf_ims_set_service_status_006,
  ril_utf_ims_set_service_status_007,
  ril_utf_ims_set_service_status_008,
  ril_utf_ims_set_service_status_009,
  ril_utf_ims_set_service_status_010,
  ril_utf_ims_set_service_status_011,
  ril_utf_ims_set_service_status_012,
  ril_utf_ims_set_service_status_013,
  ril_utf_ims_set_service_status_014,
  ril_utf_ims_set_service_status_015,
  ril_utf_ims_set_service_status_016,
  ril_utf_ims_service_enable_config_ind_001,
  ril_utf_ims_config_set_ims_config_001,
  ril_utf_ims_config_set_ims_config_002,
  ril_utf_ims_config_get_ims_config_001,
  ril_utf_ims_config_codec_dynamic_config_001,
  ril_utf_ims_config_codec_dynamic_config_002,
  ril_utf_ims_config_codec_dynamic_config_003,
  ril_utf_ims_config_codec_dynamic_config_004,
  ril_utf_ims_config_voice_dynamic_config_001,
  ril_utf_ims_config_voice_dynamic_config_002,
  ril_utf_ims_config_voice_dynamic_config_003,
  ril_utf_ims_config_voice_dynamic_config_004,
  ril_utf_ims_config_reg_mgr_new_config_001,
  ril_utf_ims_config_reg_mgr_new_config_002,
  ril_utf_ims_config_reg_mgr_new_config_003,
  ril_utf_ims_config_reg_mgr_new_config_004,
  ril_utf_ims_config_sms_new_config_001,
  ril_utf_ims_config_sms_new_config_002,
  ril_utf_ims_config_sms_new_config_003,
  ril_utf_ims_config_sms_new_config_004,
  ril_utf_ims_config_rtp_dynamic_config_001,
  ril_utf_ims_config_rtp_dynamic_config_002,
  ril_utf_ims_config_rtp_dynamic_config_003,
  ril_utf_ims_config_ims_service_enable_config_001,
  ril_utf_ims_config_ims_service_enable_config_002,
  ril_utf_ims_config_ims_service_enable_config_003,
  ril_utf_ims_config_sip_new_config_001,
  ril_utf_ims_config_sip_new_config_002,
  ril_utf_ims_config_sip_new_config_003,
  ril_utf_ims_config_presence_new_config_001,
  ril_utf_ims_config_presence_new_config_002,
  ril_utf_ims_config_presence_new_config_003,
  ril_utf_ims_config_ims_new_config_001,
  ril_utf_ims_config_ims_new_config_002,
  ril_utf_ims_config_ims_new_config_003,
  ril_utf_ims_config_emer_dynamic_config_001,
  ril_utf_ims_config_emer_dynamic_config_002,
  ril_utf_ims_config_emer_dynamic_config_003,
  ril_utf_ims_config_video_dynamic_config_001,
  ril_utf_ims_config_video_dynamic_config_002,
  ril_utf_ims_config_video_dynamic_config_003,
  ril_utf_ims_config_rcs_new_config_001,
  ril_utf_ims_config_rcs_new_config_002,
  ril_utf_ims_config_rcs_new_config_003,
  ril_utf_ims_config_concurrency_config_001,
  ril_utf_ims_config_concurrency_config_003,
  ril_utf_ims_config_handover_config_001,
  ril_utf_ims_config_handover_config_002,
  ril_utf_ims_config_handover_config_003,
  ril_utf_test_imsa_send_rtt_message,
  ril_utf_test_imsa_send_rtt_message_fail,
  //ril_utf_test_imsa_send_rtt_message_fail_empty,
  ril_utf_test_imsa_send_rtt_message_fail_length,
  ril_utf_test_imsa_unsol_rtt_message,
  ril_utf_ims_block_status_ind_001,
  ril_utf_ims_block_status_ind_002,

  ril_utf_ims_service_enable_config_ind_old_002,
  ril_utf_ims_config_ims_service_enable_config_old_001,

#if 0 // to replace with new IMS SMS test cases
  ril_utf_test_ims_send_sms_testcase_1,
  ril_utf_test_ims_send_sms_testcase_2,
  ril_utf_test_ims_send_sms_testcase_3,
  ril_utf_test_ims_send_sms_testcase_4,
  ril_utf_test_ims_send_sms_testcase_5,
  ril_utf_test_ims_send_sms_testcase_6,
  ril_utf_test_ims_send_sms_testcase_7,
  ril_utf_test_ims_send_sms_testcase_8,
  ril_utf_test_multisim_config_testcase_1,
#endif
#if 0
#ifndef RIL_UTF_L_MASTER
  ril_utf_test_set_uicc_subscription_testcase_1,
  ril_utf_test_set_uicc_subscription_testcase_2,
#endif
#ifdef UTF_UIM_SUPPORT
  ril_utf_test_set_uicc_subscription_testcase_3,
#endif
  ril_utf_test_screen_state_1,
  ril_utf_test_screen_state_2,
#endif

  // UIM TESTS that are currently disabled.
  // Need to revisit and try to fix them is possible
#ifndef QMI_RIL_HAL_UTF
  ril_utf_test_get_card_status_1_1_1,
  ril_utf_test_get_card_status_1_1_2,
  ril_utf_test_get_card_status_1_1_3,
  ril_utf_test_get_card_status_1_1_4,
  ril_utf_test_get_card_status_1_1_5,
  ril_utf_test_get_card_status_1_1_6,
  ril_utf_test_get_card_status_1_1_7,
  ril_utf_test_get_card_status_1_1_8,
  /*ril_utf_test_get_card_status_1_1_9,
  ril_utf_test_get_card_status_1_3_1,
  ril_utf_test_get_card_status_1_3_2,
  ril_utf_test_get_card_status_1_3_3,
  ril_utf_test_get_card_status_1_3_4,
  ril_utf_test_get_card_status_1_3_5,
  ril_utf_test_get_card_status_1_3_6,
  ril_utf_test_get_card_status_1_3_7,
  ril_utf_test_get_card_status_1_3_8,
  ril_utf_test_get_card_status_1_3_9,*/
#endif

  //UIM Tests
  ril_utf_test_send_status_command_testcase_1,
  ril_utf_test_refresh_init_full_fcn_non_prov_1,
  ril_utf_test_get_card_status_1,
  ril_utf_test_open_logical_channel_request_1,

  ril_utf_test_set_lte_tune_away_testcase_1,
  ril_utf_test_set_lte_tune_away_testcase_2,
  ril_utf_test_set_lte_tune_away_testcase_3,
  ril_utf_test_set_lte_tune_away_testcase_4,
#if 0
  // APN TESTS
  ril_utf_test_lte_apn_detach_then_attach,
  ril_utf_test_lte_apn_no_reattach_needed,
  ril_utf_test_lte_apn_detach_error,
  ril_utf_test_lte_apn_attach_error,
  ril_utf_test_lte_apn_lte_ps_mode_detach_no_service_domain,
  ril_utf_test_lte_apn_detach_two_indications,
  ril_utf_test_lte_apn_multiple_set_init_attach_apn_requests,
  //ril_utf_test_lte_apn_detach_no_indication, // takes 80 seconds to execute
  //ril_utf_test_lte_apn_attach_no_indication, // takes 80 seconds to execute
  //ril_utf_test_lte_apn_detach_delayed_indication, // takes 80 seconds to execute
  //ril_utf_test_lte_apn_attach_delayed_indication, // takes 80 seconds to execute
  ril_utf_test_lte_apn_empty_apn_name_gerrit_1075551,
#endif
  // eMBMS test cases
#ifdef RIL_UTF_L_MASTER
  ril_utf_test_embms_get_sib_plmn_001,
  ril_utf_test_embms_get_sib_plmn_002,
  ril_utf_test_embms_get_sib_plmn_003,
  ril_utf_test_embms_get_sib_plmn_004,
  ril_utf_test_embms_get_sib_plmn_005,
  ril_utf_test_embms_get_sib_plmn_006,
  ril_utf_test_embms_get_sib_plmn_007,
  ril_utf_test_embms_enable_disable_001,
  ril_utf_test_gerrit_1270060_001,
  ril_utf_test_get_activity_info_001,
#endif
#if 0
  ril_utf_test_sglte_property,
  ril_utf_test_set_lte_band_pref_001, //RIL_REQUEST_SET_LTE_BAND_PREF request not supported
  ril_utf_test_set_lte_band_pref_002,
  ril_utf_test_set_lte_band_pref_003,
  ril_utf_test_set_lte_band_pref_004,
#endif
#ifdef RIL_UTF_L_MASTER
  // Lte Direct Discovery test cases
  ril_utf_lte_direct_disc_get_device_capability_001,
  ril_utf_lte_direct_disc_get_service_status_001,
  ril_utf_lte_direct_disc_publish_001,
  ril_utf_lte_direct_disc_subscribe_001,
  ril_utf_lte_direct_disc_terminate_001,

  ril_utf_test_shutdown_001,
  ril_utf_test_shutdown_002,
  ril_utf_test_shutdown_003,
#endif
  ril_ut_test_enable_5g_inclusive_01,
  ril_utf_test_enable_modem_on,
  ril_utf_test_enable_modem_off,
  ril_utf_test_enable_modem_timeout,
  ril_ut_test_get_modem_stack_status_on,
  ril_ut_test_get_modem_stack_status_off,
  ril_utf_test_query_network_selection_mode_1,
  ril_utf_test_query_network_selection_mode_2,
  ril_utf_test_set_band_mode,
  ril_utf_test_get_available_band_modes,
  ril_utf_test_device_identity,
  ril_utf_test_get_base_band_version,
  ril_utf_test_emergency_list_unsol_1,
  ril_utf_test_emergency_list_unsol_2,
  ril_utf_test_consecutive_set_get_preferred_network_type_testcase_1,
  ril_utf_test_consecutive_set_get_preferred_network_type_testcase_2,
  ril_ut_test_network_scan_001,
  ril_ut_test_network_scan_002,
  ril_ut_test_network_scan_003,
  ril_ut_test_network_scan_004,
  ril_ut_test_network_scan_005,
  ril_ut_test_network_scan_006,
  ril_ut_test_network_scan_007,
  ril_ut_test_get_neighboring_cell_ids_001,
  ril_ut_test_get_neighboring_cell_ids_002,
  ril_ut_test_get_neighboring_cell_ids_003,
  ril_ut_test_get_neighboring_cell_ids_004,
  ril_ut_test_get_cell_info_list_001,

  ril_utf_test_card_status_change,
  NULL // used to mark the end of the table
};
