/******************************************************************************
#  Copyright (c) 2016 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#******************************************************************************/

/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.8-dev at Mon Jun 27 17:22:53 2016. */

#ifndef _PB_RADIO_CONFIG_INTERFACE_PB_H_
#define _PB_RADIO_CONFIG_INTERFACE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _com_qualcomm_qti_radioconfiginterface_MessageType {
    com_qualcomm_qti_radioconfiginterface_MessageType_RADIO_CONFIG_MSG_UNKNOWN = 0,
    com_qualcomm_qti_radioconfiginterface_MessageType_RADIO_CONFIG_MSG_REQUEST = 1,
    com_qualcomm_qti_radioconfiginterface_MessageType_RADIO_CONFIG_MSG_RESPONSE = 2,
    com_qualcomm_qti_radioconfiginterface_MessageType_RADIO_CONFIG_MSG_INDICATION = 3
} com_qualcomm_qti_radioconfiginterface_MessageType;

typedef enum _com_qualcomm_qti_radioconfiginterface_MessageId {
    com_qualcomm_qti_radioconfiginterface_MessageId_RADIO_CONFIG_UNKNOWN = 0,
    com_qualcomm_qti_radioconfiginterface_MessageId_RADIO_CONFIG_SET_CONFIG = 1,
    com_qualcomm_qti_radioconfiginterface_MessageId_RADIO_CONFIG_GET_CONFIG = 2,
    com_qualcomm_qti_radioconfiginterface_MessageId_RADIO_CONFIG_UNSOL_PSK_EXPIRED = 1000
} com_qualcomm_qti_radioconfiginterface_MessageId;

typedef enum _com_qualcomm_qti_radioconfiginterface_Error {
    com_qualcomm_qti_radioconfiginterface_Error_RADIO_CONFIG_ERR_SUCCESS = 0,
    com_qualcomm_qti_radioconfiginterface_Error_RADIO_CONFIG_ERR_GENERIC_FAILURE = 1,
    com_qualcomm_qti_radioconfiginterface_Error_RADIO_CONFIG_ERR_NOT_SUPPORTED = 2,
    com_qualcomm_qti_radioconfiginterface_Error_RADIO_CONFIG_ERR_INVALID_PARAMETER = 3
} com_qualcomm_qti_radioconfiginterface_Error;

typedef enum _com_qualcomm_qti_radioconfiginterface_ConfigItem {
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_NONE = 0,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_LTE_RSRP_LOW = 1,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_LTE_RSRP_MID = 2,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_LTE_RSRP_HIGH = 3,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_WIFI_RSSI_THRESHOLD_LOW = 4,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_WIFI_RSSI_THRESHOLD_HIGH = 5,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_WIFI_SINR_THRESHOLD_LOW = 6,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IN_CALL_WIFI_SINR_THRESHOLD_HIGH = 7,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_LTE_RSRP_LOW = 8,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_LTE_RSRP_MID = 9,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_LTE_RSRP_HIGH = 10,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_WIFI_RSSI_THRESHOLD_LOW = 11,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_WIFI_RSSI_THRESHOLD_HIGH = 12,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_WIFI_SINR_THRESHOLD_LOW = 13,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_IDLE_WIFI_SINR_THRESHOLD_HIGH = 14,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_ECIO_1X_THRESHOLD_LOW = 15,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_ECIO_1X_THRESHOLD_HIGH = 16,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_SET_LTED_CONFIG = 100,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_GET_LTED_CONFIG = 101,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_SET_LTED_CATEGORY = 102,
    com_qualcomm_qti_radioconfiginterface_ConfigItem_CONFIG_ITEM_GET_LTED_CATEGORY = 103
} com_qualcomm_qti_radioconfiginterface_ConfigItem;

typedef enum _com_qualcomm_qti_radioconfiginterface_ConfigFailureCause {
    com_qualcomm_qti_radioconfiginterface_ConfigFailureCause_CONFIG_NO_ERR = 0,
    com_qualcomm_qti_radioconfiginterface_ConfigFailureCause_CONFIG_GENERIC_ERR = 1,
    com_qualcomm_qti_radioconfiginterface_ConfigFailureCause_CONFIG_ITEM_NOT_PRESENT = 2
} com_qualcomm_qti_radioconfiginterface_ConfigFailureCause;

/* Struct definitions */
typedef struct _com_qualcomm_qti_radioconfiginterface_ConfigItemMsg {
    com_qualcomm_qti_radioconfiginterface_ConfigItem item;
    bool has_boolValue;
    bool boolValue;
    bool has_intValue;
    uint32_t intValue;
    char *stringValue;
    pb_bytes_array_t *byteArrayValue;
    bool has_errorCause;
    com_qualcomm_qti_radioconfiginterface_ConfigFailureCause errorCause;
} com_qualcomm_qti_radioconfiginterface_ConfigItemMsg;

typedef struct _com_qualcomm_qti_radioconfiginterface_LtedCategory {
    char *osAppId;
    bool has_category;
    uint32_t category;
} com_qualcomm_qti_radioconfiginterface_LtedCategory;

typedef struct _com_qualcomm_qti_radioconfiginterface_MessageTag {
    com_qualcomm_qti_radioconfiginterface_MessageType type;
    com_qualcomm_qti_radioconfiginterface_MessageId id;
    bool has_error;
    com_qualcomm_qti_radioconfiginterface_Error error;
    bool has_token;
    uint32_t token;
    pb_bytes_array_t *payload;
} com_qualcomm_qti_radioconfiginterface_MessageTag;

typedef struct _com_qualcomm_qti_radioconfiginterface_Plmn {
    char *mcc;
    char *mnc;
} com_qualcomm_qti_radioconfiginterface_Plmn;

typedef struct _com_qualcomm_qti_radioconfiginterface_Value128 {
    bool has_lsb;
    uint64_t lsb;
    bool has_msb;
    uint64_t msb;
} com_qualcomm_qti_radioconfiginterface_Value128;

typedef struct _com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy {
    struct _com_qualcomm_qti_radioconfiginterface_Plmn *plmn;
    bool has_validityTime;
    uint32_t validityTime;
    bool has_range;
    uint32_t range;
} com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy;

typedef struct _com_qualcomm_qti_radioconfiginterface_ConfigMsg {
    size_t settings_count;
    struct _com_qualcomm_qti_radioconfiginterface_ConfigItemMsg *settings;
} com_qualcomm_qti_radioconfiginterface_ConfigMsg;

typedef struct _com_qualcomm_qti_radioconfiginterface_MonitoringPolicy {
    struct _com_qualcomm_qti_radioconfiginterface_Plmn *plmn;
    bool has_validityTime;
    uint32_t validityTime;
    bool has_remainingTime;
    uint32_t remainingTime;
} com_qualcomm_qti_radioconfiginterface_MonitoringPolicy;

typedef struct _com_qualcomm_qti_radioconfiginterface_LtedConfig {
    bool has_osId;
    com_qualcomm_qti_radioconfiginterface_Value128 osId;
    char *apn;
    size_t announcingPolicy_count;
    struct _com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy *announcingPolicy;
    size_t monitoringPolicy_count;
    struct _com_qualcomm_qti_radioconfiginterface_MonitoringPolicy *monitoringPolicy;
    pb_bytes_array_t *bakPassword;
} com_qualcomm_qti_radioconfiginterface_LtedConfig;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_item_tag 1
#define com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_boolValue_tag 2
#define com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_intValue_tag 3
#define com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_stringValue_tag 4
#define com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_byteArrayValue_tag 5
#define com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_errorCause_tag 6
#define com_qualcomm_qti_radioconfiginterface_LtedCategory_osAppId_tag 1
#define com_qualcomm_qti_radioconfiginterface_LtedCategory_category_tag 2
#define com_qualcomm_qti_radioconfiginterface_MessageTag_type_tag 1
#define com_qualcomm_qti_radioconfiginterface_MessageTag_id_tag 2
#define com_qualcomm_qti_radioconfiginterface_MessageTag_error_tag 3
#define com_qualcomm_qti_radioconfiginterface_MessageTag_token_tag 4
#define com_qualcomm_qti_radioconfiginterface_MessageTag_payload_tag 5
#define com_qualcomm_qti_radioconfiginterface_Plmn_mcc_tag 1
#define com_qualcomm_qti_radioconfiginterface_Plmn_mnc_tag 2
#define com_qualcomm_qti_radioconfiginterface_Value128_lsb_tag 1
#define com_qualcomm_qti_radioconfiginterface_Value128_msb_tag 2
#define com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_plmn_tag 1
#define com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_validityTime_tag 2
#define com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_range_tag 3
#define com_qualcomm_qti_radioconfiginterface_ConfigMsg_settings_tag 1
#define com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_plmn_tag 1
#define com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_validityTime_tag 2
#define com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_remainingTime_tag 3
#define com_qualcomm_qti_radioconfiginterface_LtedConfig_osId_tag 1
#define com_qualcomm_qti_radioconfiginterface_LtedConfig_apn_tag 2
#define com_qualcomm_qti_radioconfiginterface_LtedConfig_announcingPolicy_tag 3
#define com_qualcomm_qti_radioconfiginterface_LtedConfig_monitoringPolicy_tag 4
#define com_qualcomm_qti_radioconfiginterface_LtedConfig_bakPassword_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_MessageTag_fields[6];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_Value128_fields[3];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_Plmn_fields[3];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_AnnouncingPolicy_fields[4];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_MonitoringPolicy_fields[4];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_LtedConfig_fields[6];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_LtedCategory_fields[3];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_ConfigItemMsg_fields[7];
extern const pb_field_t com_qualcomm_qti_radioconfiginterface_ConfigMsg_fields[2];

/* Maximum encoded size of messages (where known) */
#define com_qualcomm_qti_radioconfiginterface_Value128_size 18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
