//=============================================================================
//                          C H R O M A T I X
//
//   DESCRIPTION
//   Auto-Generated by Chromatix tool defining camera tunable parameters.
//
// Copyright (c) 2016-2017 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
//=============================================================================

/* Header Version Info */
{
   0x0310, /* Chromatix Version */
   1, /* Revision */
   /* Chromatix App Version */
   {
      6, /* Major */
      14, /* Minor */
      2, /* Revision */
      2, /* Build */
   },
   HEADER_POST_PROC, /* Header Type */
   0, /* Is Compressed */
   0, /* Is Mono */
   0, /* Is Video */
   0, /* Reserved Align */
   MODE_UNKNOWN, /* Chromatix Mode */
   0, /* Target ID */
   0, /* Chromatix ID */
   /* Reserved */
   {
      0, 0, 0, 0
   }
},

/******************************************************************************/
// Feature name: Radial Noise Reduction( RNR1 ) Parameters.
//
// Variable name: hysteresis_point[MAX_HYSTERESIS_LIGHT_REGIONS].
// Hysteresis Point is used to control Sampling Ratio parameter for RNR to reduce the oscillations.
//
// Variable name: sigma_lut[MAX_SIGMA_TABLES][RNR_LUT_SIZE].
// This LUT is used to describe the spatial varying noise property based
//   on pixel’s distance to the image center. This LUT should be calibrated from Chromatix tool.
// Data range: 1 to 5. Values outside this range indicate there may be problems in the calibration.
//
// Variable name: Sampling Factor.
// Downsample/Upsampling factor.
// Data range: Possible values are 2, 4, or 8.
// Effect: Larger value means stronger noise reduction.
// Default value: 2 for region 1-2, 4 for region 3-4, 8 for region 5-6
//
// Variable name: Center Noise Sigma.
// This parameter is multiplied with sigma_lut to determine the noise threshold for each position.
// This parameter is to be interpolated between different regions.
// Data range: 0 to 100. 0 means turning RNR off.
// Effect: larger value means stronger noise reduction.
// Default value: 1, 1.5, 2, 2.5, 4, 4.5 for region 1-6
//
// Variable name: Center Noise Weight
// This parameter determines RNR strength at image center.
// Data range: 0 to 1.0.
// Effect: larger value means less noise reduction at image center.
// Default value: 1.0 (no noise reduction in image center).
//
// Variable name: Noise Reduction Order or weight order.
// This variable controls RNR strength at off-center positions.
// Data range: 0 to 20
// Effect: larger value means stronger noise reduction at image corner.
// Default value: 1.0
/*******************************************************************************/

/* RNR1 */
{
   1, /* Enable */
   1, /* Control Enable */
   1, /* Control Method - 1 = Gain, 0 = Lux Index */
   164, /* Sigma LUT Size */
   /* Hysteresis Triggers */
   {
      /* Normal Light */
      {
         10.60000f, /* Gain Start */
         11.80000f, /* Gain End */
         350, /* Lux Index Start */
         380, /* Lux Index End */
      },
      /* Bright Light Light */
      {
         2.600000f, /* Gain Start */
         3.000000f, /* Gain End */
         200, /* Lux Index Start */
         210, /* Lux Index End */
      },
   },
   /* Sigma LUT Triggers */
   {
      /* Normal Light */
      {
         10.60000f, /* Gain Start */
         11.80000f, /* Gain End */
         350, /* Lux Index Start */
         380, /* Lux Index End */
      },
      /* Bright Light Light */
      {
         2.600000f, /* Gain Start */
         3.000000f, /* Gain End */
         200, /* Lux Index Start */
         210, /* Lux Index End */
      },
   },
   /* Sigma LUTs */
   {
      /* Sigma LUT1 */
      {
         1.000000f, 1.000638f, 1.001420f, 1.002345f, 1.003370f, 1.004443f, 1.005516f, 1.006613f, 1.007828f, 1.009196f,
         1.010723f, 1.012413f, 1.014315f, 1.016459f, 1.018807f, 1.021264f, 1.023683f, 1.026101f, 1.028507f, 1.030893f,
         1.033246f, 1.035510f, 1.037609f, 1.039516f, 1.041405f, 1.043337f, 1.045288f, 1.047168f, 1.048898f, 1.050624f,
         1.052473f, 1.054491f, 1.056644f, 1.058953f, 1.061375f, 1.063886f, 1.066587f, 1.069485f, 1.072479f, 1.075396f,
         1.078181f, 1.080796f, 1.083210f, 1.085426f, 1.087504f, 1.089611f, 1.091884f, 1.094444f, 1.097366f, 1.100694f,
         1.104368f, 1.108230f, 1.112215f, 1.116248f, 1.120190f, 1.123942f, 1.127528f, 1.131074f, 1.134740f, 1.138672f,
         1.142976f, 1.147717f, 1.152814f, 1.158062f, 1.163200f, 1.168120f, 1.172706f, 1.176841f, 1.180542f, 1.183859f,
         1.186825f, 1.189519f, 1.192038f, 1.194680f, 1.197627f, 1.200909f, 1.204449f, 1.208231f, 1.212260f, 1.216434f,
         1.220760f, 1.225196f, 1.229594f, 1.233876f, 1.237995f, 1.242211f, 1.246719f, 1.251642f, 1.257015f, 1.262736f,
         1.268675f, 1.274601f, 1.280313f, 1.285749f, 1.290830f, 1.295471f, 1.299806f, 1.304248f, 1.309093f, 1.314515f,
         1.320547f, 1.327106f, 1.334032f, 1.341116f, 1.348118f, 1.354875f, 1.361227f, 1.366929f, 1.372007f, 1.376671f,
         1.381069f, 1.385336f, 1.389615f, 1.394050f, 1.398727f, 1.403718f, 1.409082f, 1.414865f, 1.421064f, 1.427708f,
         1.434838f, 1.442321f, 1.449895f, 1.457323f, 1.464435f, 1.471226f, 1.477821f, 1.484360f, 1.490861f, 1.497389f,
         1.504139f, 1.511286f, 1.519120f, 1.527792f, 1.537271f, 1.547399f, 1.557929f, 1.568630f, 1.579357f, 1.590007f,
         1.600247f, 1.609756f, 1.618391f, 1.626035f, 1.632710f, 1.638703f, 1.644282f, 1.649623f, 1.654841f, 1.660052f,
         1.665385f, 1.671093f, 1.677272f, 1.683799f, 1.690445f, 1.697131f, 1.703647f, 1.709880f, 1.715671f, 1.720793f,
         1.725019f, 1.728262f, 1.730576f, 1.732170f
      },
      /* Sigma LUT2 */
      {
         1.000000f, 1.000638f, 1.001420f, 1.002345f, 1.003370f, 1.004443f, 1.005516f, 1.006613f, 1.007828f, 1.009196f,
         1.010723f, 1.012413f, 1.014315f, 1.016459f, 1.018807f, 1.021264f, 1.023683f, 1.026101f, 1.028507f, 1.030893f,
         1.033246f, 1.035510f, 1.037609f, 1.039516f, 1.041405f, 1.043337f, 1.045288f, 1.047168f, 1.048898f, 1.050624f,
         1.052473f, 1.054491f, 1.056644f, 1.058953f, 1.061375f, 1.063886f, 1.066587f, 1.069485f, 1.072479f, 1.075396f,
         1.078181f, 1.080796f, 1.083210f, 1.085426f, 1.087504f, 1.089611f, 1.091884f, 1.094444f, 1.097366f, 1.100694f,
         1.104368f, 1.108230f, 1.112215f, 1.116248f, 1.120190f, 1.123942f, 1.127528f, 1.131074f, 1.134740f, 1.138672f,
         1.142976f, 1.147717f, 1.152814f, 1.158062f, 1.163200f, 1.168120f, 1.172706f, 1.176841f, 1.180542f, 1.183859f,
         1.186825f, 1.189519f, 1.192038f, 1.194680f, 1.197627f, 1.200909f, 1.204449f, 1.208231f, 1.212260f, 1.216434f,
         1.220760f, 1.225196f, 1.229594f, 1.233876f, 1.237995f, 1.242211f, 1.246719f, 1.251642f, 1.257015f, 1.262736f,
         1.268675f, 1.274601f, 1.280313f, 1.285749f, 1.290830f, 1.295471f, 1.299806f, 1.304248f, 1.309093f, 1.314515f,
         1.320547f, 1.327106f, 1.334032f, 1.341116f, 1.348118f, 1.354875f, 1.361227f, 1.366929f, 1.372007f, 1.376671f,
         1.381069f, 1.385336f, 1.389615f, 1.394050f, 1.398727f, 1.403718f, 1.409082f, 1.414865f, 1.421064f, 1.427708f,
         1.434838f, 1.442321f, 1.449895f, 1.457323f, 1.464435f, 1.471226f, 1.477821f, 1.484360f, 1.490861f, 1.497389f,
         1.504139f, 1.511286f, 1.519120f, 1.527792f, 1.537271f, 1.547399f, 1.557929f, 1.568630f, 1.579357f, 1.590007f,
         1.600247f, 1.609756f, 1.618391f, 1.626035f, 1.632710f, 1.638703f, 1.644282f, 1.649623f, 1.654841f, 1.660052f,
         1.665385f, 1.671093f, 1.677272f, 1.683799f, 1.690445f, 1.697131f, 1.703647f, 1.709880f, 1.715671f, 1.720793f,
         1.725019f, 1.728262f, 1.730576f, 1.732170f
      },
      /* Sigma LUT3 */
      {
         1.000000f, 1.000638f, 1.001420f, 1.002345f, 1.003370f, 1.004443f, 1.005516f, 1.006613f, 1.007828f, 1.009196f,
         1.010723f, 1.012413f, 1.014315f, 1.016459f, 1.018807f, 1.021264f, 1.023683f, 1.026101f, 1.028507f, 1.030893f,
         1.033246f, 1.035510f, 1.037609f, 1.039516f, 1.041405f, 1.043337f, 1.045288f, 1.047168f, 1.048898f, 1.050624f,
         1.052473f, 1.054491f, 1.056644f, 1.058953f, 1.061375f, 1.063886f, 1.066587f, 1.069485f, 1.072479f, 1.075396f,
         1.078181f, 1.080796f, 1.083210f, 1.085426f, 1.087504f, 1.089611f, 1.091884f, 1.094444f, 1.097366f, 1.100694f,
         1.104368f, 1.108230f, 1.112215f, 1.116248f, 1.120190f, 1.123942f, 1.127528f, 1.131074f, 1.134740f, 1.138672f,
         1.142976f, 1.147717f, 1.152814f, 1.158062f, 1.163200f, 1.168120f, 1.172706f, 1.176841f, 1.180542f, 1.183859f,
         1.186825f, 1.189519f, 1.192038f, 1.194680f, 1.197627f, 1.200909f, 1.204449f, 1.208231f, 1.212260f, 1.216434f,
         1.220760f, 1.225196f, 1.229594f, 1.233876f, 1.237995f, 1.242211f, 1.246719f, 1.251642f, 1.257015f, 1.262736f,
         1.268675f, 1.274601f, 1.280313f, 1.285749f, 1.290830f, 1.295471f, 1.299806f, 1.304248f, 1.309093f, 1.314515f,
         1.320547f, 1.327106f, 1.334032f, 1.341116f, 1.348118f, 1.354875f, 1.361227f, 1.366929f, 1.372007f, 1.376671f,
         1.381069f, 1.385336f, 1.389615f, 1.394050f, 1.398727f, 1.403718f, 1.409082f, 1.414865f, 1.421064f, 1.427708f,
         1.434838f, 1.442321f, 1.449895f, 1.457323f, 1.464435f, 1.471226f, 1.477821f, 1.484360f, 1.490861f, 1.497389f,
         1.504139f, 1.511286f, 1.519120f, 1.527792f, 1.537271f, 1.547399f, 1.557929f, 1.568630f, 1.579357f, 1.590007f,
         1.600247f, 1.609756f, 1.618391f, 1.626035f, 1.632710f, 1.638703f, 1.644282f, 1.649623f, 1.654841f, 1.660052f,
         1.665385f, 1.671093f, 1.677272f, 1.683799f, 1.690445f, 1.697131f, 1.703647f, 1.709880f, 1.715671f, 1.720793f,
         1.725019f, 1.728262f, 1.730576f, 1.732170f
      },
   },
   /* Region Data */
   {
      /* Region 1 */
      {
         /* Trigger */
         {
            1.000000f, /* Gain Start */
            1.990000f, /* Gain End */
            250, /* Lux Index Start */
            262, /* Lux Index End */
         },
         4, /* Sampling Factor */
         1.000000f, /* Center Noise Sigma */
         1.000000f, /* Center Noise Weight */
         2.000000f, /* Weight Order */
      },
      /* Region 2 */
      {
         /* Trigger */
         {
            2.000000f, /* Gain Start */
            3.990000f, /* Gain End */
            285, /* Lux Index Start */
            297, /* Lux Index End */
         },
         4, /* Sampling Factor */
         1.000000f, /* Center Noise Sigma */
         1.000000f, /* Center Noise Weight */
         2.500000f, /* Weight Order */
      },
      /* Region 3 */
      {
         /* Trigger */
         {
            4.000000f, /* Gain Start */
            7.990000f, /* Gain End */
            305, /* Lux Index Start */
            317, /* Lux Index End */
         },
         4, /* Sampling Factor */
         1.000000f, /* Center Noise Sigma */
         1.000000f, /* Center Noise Weight */
         3.000000f, /* Weight Order */
      },
      /* Region 4 */
      {
         /* Trigger */
         {
            8.000000f, /* Gain Start */
            15.99000f, /* Gain End */
            380, /* Lux Index Start */
            392, /* Lux Index End */
         },
         4, /* Sampling Factor */
         1.000000f, /* Center Noise Sigma */
         1.000000f, /* Center Noise Weight */
         3.500000f, /* Weight Order */
      },
      /* Region 5 */
      {
         /* Trigger */
         {
            16.00000f, /* Gain Start */
            27.99000f, /* Gain End */
            395, /* Lux Index Start */
            407, /* Lux Index End */
         },
         4, /* Sampling Factor */
         1.000000f, /* Center Noise Sigma */
         1.000000f, /* Center Noise Weight */
         4.000000f, /* Weight Order */
      },
      /* Region 6 */
      {
         /* Trigger */
         {
            28.00000f, /* Gain Start */
            32.00000f, /* Gain End */
            420, /* Lux Index Start */
            432, /* Lux Index End */
         },
         4, /* Sampling Factor */
         1.000000f, /* Center Noise Sigma */
         1.000000f, /* Center Noise Weight */
         4.500000f, /* Weight Order */
      },
   },
},

/******************************************************************************/
// Feature name : Chroma Artifact Correction2.
// Applicable operation mode: Snapshot.
//
// Variable name: control_CAC2.
// Control with gain or lux_index.
// Default Value: 0.
// Data range: 0 (Lux Index) or 1 ( Gain ).
// Constraints: None.
// Effect: Use gain or lux_index for control.
//
// variable name: cac2_enable.
// CAC2 Enable Flag per region.
//
// Variable name: y_spot_thr_low //6uQ6
// The lower bound of bright spot threshold in bright spot detection.
//   Bright spot threshold is defined on brightness difference between one pixel and its surrounding pixels
//   for luma spot detection.
// Default value: 0.
// Data range: 0 to 63.
// Effect: By decreasing the threshold, more points will be detected.
//
// Variable name: y_spot_thr_up //6uQ6
// The upper bound of bright spot threshold in bright spot detection.
//   Bright spot threshold is defined as brightness difference between one pixel and its surrounding pixels.
// Note: This parameter is not used in CAC3.
// Default value: 30.
// Data range: 0 to 63.
// Effect: By decreasing the threshold, more points will be detected.
//
// Variable name: y_spot_thr_weight //6uQ6
// Dynamic control parameter for determining the final value of bright spot threshold (y_spot_thr) in the range [y_spot_thr_low, y_spot_thr_up).
//   y_spot_thr = (y_spot_thr_up - y_spot_thr_low)*y_spot_thr_weight/64 + y_spot_thr_low.
// Note: This parameter is not used in CAC3.
// Default value: 20.
// Data range: 0 to 63.
//
// Variable name: y_saturation_thr //8uQ0
// The brightness saturation threshold in bright spot detection.
// Default value: 240.
// Data range : 200 to 255.
// Effect: By decreasing the threshold, more points will be detected.
//
// Variable name: c_saturation_thr //7uQ0
// The color saturation threshold in color spot detection.
// Default value: 10.
// Data range : 0 to 63.
// Effect: For one pixel, if its color saturation is less than c_saturation_thr,
//   it won’t be detected as 'Color Artifacts' and will not be corrected.
//
// Variable name: c_spot_thr //8uQ0
// The color spot threshold on color difference between one pixel and its surrounding pixels
//   in color spot detection.
// Default value: 10.
// Data range : 0 to 63.
// Effect: For one pixel, if its color difference is less than c_spot_thr,
//   it won’t be detected as 'Color Artifacts' and will not be corrected.
//   This parameter is not used for 8994 SW CAC.
/*******************************************************************************/

/* CAC2 */
{
   0, /* Control Enable */
   0, /* Control Method - 1 = Gain, 0 = Lux Index */
   /* Region Data */
   {
      /* Region 1 */
      {
         1, /* Enable CAC2 for this region */
         /* Trigger */
         {
            1.000000f, /* Gain Start */
            1.200000f, /* Gain End */
            250, /* Lux Index Start */
            262, /* Lux Index End */
         },
         0, /* Y Spot Threshold Low */
         30, /* Y Spot Threshold Up */
         240, /* Y Saturation Threshold */
         10, /* C Saturation Threshold */
         20, /* Y Spot Threshold Weight */
         10, /* Unused for now */
      },
      /* Region 2 */
      {
         1, /* Enable CAC2 for this region */
         /* Trigger */
         {
            2.960000f, /* Gain Start */
            3.552000f, /* Gain End */
            285, /* Lux Index Start */
            297, /* Lux Index End */
         },
         0, /* Y Spot Threshold Low */
         30, /* Y Spot Threshold Up */
         240, /* Y Saturation Threshold */
         10, /* C Saturation Threshold */
         20, /* Y Spot Threshold Weight */
         10, /* Unused for now */
      },
      /* Region 3 */
      {
         0, /* Enable CAC2 for this region */
         /* Trigger */
         {
            4.920000f, /* Gain Start */
            5.904000f, /* Gain End */
            305, /* Lux Index Start */
            317, /* Lux Index End */
         },
         0, /* Y Spot Threshold Low */
         30, /* Y Spot Threshold Up */
         240, /* Y Saturation Threshold */
         10, /* C Saturation Threshold */
         20, /* Y Spot Threshold Weight */
         10, /* Unused for now */
      },
      /* Region 4 */
      {
         0, /* Enable CAC2 for this region */
         /* Trigger */
         {
            8.000000f, /* Gain Start */
            9.600000f, /* Gain End */
            380, /* Lux Index Start */
            392, /* Lux Index End */
         },
         0, /* Y Spot Threshold Low */
         30, /* Y Spot Threshold Up */
         240, /* Y Saturation Threshold */
         10, /* C Saturation Threshold */
         20, /* Y Spot Threshold Weight */
         10, /* Unused for now */
      },
      /* Region 5 */
      {
         0, /* Enable CAC2 for this region */
         /* Trigger */
         {
            20.00000f, /* Gain Start */
            24.00000f, /* Gain End */
            395, /* Lux Index Start */
            407, /* Lux Index End */
         },
         0, /* Y Spot Threshold Low */
         30, /* Y Spot Threshold Up */
         240, /* Y Saturation Threshold */
         10, /* C Saturation Threshold */
         20, /* Y Spot Threshold Weight */
         10, /* Unused for now */
      },
      /* Region 6 */
      {
         0, /* Enable CAC2 for this region */
         /* Trigger */
         {
            32.00000f, /* Gain Start */
            38.40000f, /* Gain End */
            420, /* Lux Index Start */
            432, /* Lux Index End */
         },
         0, /* Y Spot Threshold Low */
         30, /* Y Spot Threshold Up */
         240, /* Y Saturation Threshold */
         10, /* C Saturation Threshold */
         20, /* Y Spot Threshold Weight */
         10, /* Unused for now */
      },
   },
},

/******************************************************************************/
// Variable name : stillmore_enable
//  True: enable StillMore feature
//  False: otherwise
// Feature : Parameters for StillMore feature
//
// Variable name : seemore_LTM_enable
//  True: enable LTM brightening
//  False: otherwise
// Feature : Parameters for SeeMore feature
//
// Variable name : seemore_TNR_enable
//  True: enable temporal noise reduction
//  False: otherwise
// Feature : Parameters for SeeMore feature
//
// Variable name : control_mod
// Description: 0(lux index) or 1(Gain) to control stillmore/seemore features
//
// Variable name : stillmore_hyst_trigger/seemore_hyst_trigger
// Description : Hysteresis trigger to enable StillMore/SeeMore feature. trigger >= trigger_end,
//  will enable the feature, else will be disabled and once enabled, feature will be enabled
//  until trigger < trigger_start.
//  stillmore_hyst_trigger for stillmore feature & seemore_hyst_trigger for seemore features
//
// Variable name : mod_trigger
// Description : trigger point for each region
//
// Variable name : still_brIntensity
// Controls amount of brightening.
// Data range: 0 ~ 1.
// Larger value means brighter output.
// Feature : Parameters for StillMore feature
//
// Variable name : still_brColor
// Controls amount of color after brightening.
// Data range: 0 ~ 1.
// Larger value means more colorful output.
// Feature : Parameters for StillMore feature
//
// Variable name : see_brIntensity
//  Controls amount of brightening.
// Data range: 0 ~ 1.
//  Larger value means brighter output.
//  NOTE: only takes effect when enableLTM == true.
// Feature : Parameters for SeeMore feature
//
// Variable name : see_brColor
//  Controls amount of color after brightening.
// Data range: 0 ~ 1.
//  Larger value means more colorful output.
//  NOTE: only takes effect when enableLTM == true.
// Feature : Parameters for SeeMore feature
//
// Variable name : ext_data
// Description: Extended data for reserve and future usage
/******************************************************************************/

/* Advanced Software */
{
   0, /* Stillmore Enable */
   0, /* Seemore LTM Enable */
   0, /* Seemore TNR Enable */
   0, /* Control Method - 1 = Gain, 0 = Lux Index */
   /* Still More Hyst Trigger */
   {
      0.990000f, /* Gain Start */
      1.000000f, /* Gain End */
      100, /* Lux Index Start */
      110, /* Lux Index End */
   },
   /* See More Hyst Trigger */
   {
      0.990000f, /* Gain Start */
      1.000000f, /* Gain End */
      100, /* Lux Index Start */
      110, /* Lux Index End */
   },
   /* Data */
   {
      /* Region 1 */
      {
         /* Trigger */
         {
            1.000000f, /* Gain Start */
            1.200000f, /* Gain End */
            250, /* Lux Index Start */
            262, /* Lux Index End */
         },
         /* Still More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* See More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* Ext Data */
         {
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
         },
      },
      /* Region 2 */
      {
         /* Trigger */
         {
            2.960000f, /* Gain Start */
            3.552000f, /* Gain End */
            285, /* Lux Index Start */
            297, /* Lux Index End */
         },
         /* Still More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* See More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* Ext Data */
         {
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
         },
      },
      /* Region 3 */
      {
         /* Trigger */
         {
            4.920000f, /* Gain Start */
            5.904000f, /* Gain End */
            305, /* Lux Index Start */
            317, /* Lux Index End */
         },
         /* Still More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* See More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* Ext Data */
         {
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
         },
      },
      /* Region 4 */
      {
         /* Trigger */
         {
            8.000000f, /* Gain Start */
            9.600000f, /* Gain End */
            380, /* Lux Index Start */
            392, /* Lux Index End */
         },
         /* Still More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* See More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* Ext Data */
         {
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
         },
      },
      /* Region 5 */
      {
         /* Trigger */
         {
            22.00000f, /* Gain Start */
            26.40000f, /* Gain End */
            395, /* Lux Index Start */
            407, /* Lux Index End */
         },
         /* Still More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* See More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* Ext Data */
         {
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
         },
      },
      /* Region 6 */
      {
         /* Trigger */
         {
            36.00000f, /* Gain Start */
            43.20000f, /* Gain End */
            420, /* Lux Index Start */
            432, /* Lux Index End */
         },
         /* Still More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* See More Data */
         {
            0.200000f, /* Brighten Intensity */
            0.200000f, /* Brighten Color */
         },
         /* Ext Data */
         {
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
            0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
         },
      },
   },
},
/* Software HDR */
{
   0, /* Enable */
   24, /* Contrast Control */
   5, /* Hdr Chroma Sat Wgt */
   80, /* Hdr Chroma Sat Clamp */
   10, /* Hdr Chroma Sat Shift */
   /* HDR Mod Frame Exposure Values */
   {
      0, /* Hdr Mod Frame Exposure Vals0 */
      -6, /* Hdr Mod Frame Exposure Vals1 */
      6, /* Hdr Mod Frame Exposure Vals2 */
   },
   /* Reserved */
   {
      0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
   }
},
/* Ext Data */
{
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
   0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
},

/******************************************************************/
