/******************************************************************************
#  Copyright (c) 2019 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#******************************************************************************/
#pragma once

#include <memory>
#include <android/hardware/radio/1.4/IRadio.h>
#include <android/hardware/radio/1.4/IRadioResponse.h>
#include <android/hardware/radio/1.4/IRadioIndication.h>
#include <android/hardware/radio/1.4/types.h>
#include <telephony/ril.h>
#include <ril_internal.h>
#include <ril_service.h>
#include <utils/SystemClock.h>
#include <inttypes.h>
#include <RadioContext.h>
#include <request/LinkCapIndMessage.h>
#include <modules/nas/NasSetSignalStrengthCriteria.h>
#include <modules/nas/NasModule.h>
#include <ril_service_1_3.h>
#include "MessageCommon.h"

#include "interfaces/nas/RilUnsolEmergencyListIndMessage.h"

using namespace android::hardware::radio;
using namespace android::hardware::radio::V1_0;
using namespace android::hardware::radio::deprecated::V1_0;
using ::android::hardware::Return;
using ::android::hardware::hidl_string;
using ::android::hardware::hidl_vec;
using ::android::hardware::hidl_array;
using ::android::hardware::hidl_bitfield;
using ::android::hardware::Void;
using android::CommandInfo;
using android::RequestInfo;
using android::requestToString;
using android::sp;
using rildata::DataCallFailCause_t;

union CellInfoUnion_1_4 {
    V1_2::CellInfoGsm gsm;
    V1_2::CellInfoCdma cdma;
    V1_2::CellInfoWcdma wcdma;
    V1_2::CellInfoTdscdma tdscdma;
    V1_4::CellInfoLte lte;
    V1_4::CellInfoNr nr;

    CellInfoUnion_1_4() {}
    ~CellInfoUnion_1_4() {}
};

vector<hidl_string> convertAddrStringToHidlStringVector(const string &addr);

hidl_string convertHidlStringVectorToAddrString(const vector<string> &addr);

V1_4::PdpProtocolType convertStringToPdpProtocolType(const string &type);

string convertPdpProtocolTypeToString(const V1_4::PdpProtocolType protocol);

V1_4::DataCallFailCause convertDcFailCauseToHidlDcFailCause(const DataCallFailCause_t &cause);

class RadioImpl_1_4 : virtual public RadioImpl_1_3, public V1_4::IRadio {
    sp<V1_4::IRadioResponse> mRadioResponseV1_4;
    sp<V1_4::IRadioIndication> mRadioIndicationV1_4;

protected:
    Return<void> setResponseFunctions_nolock(
        const ::android::sp<IRadioResponse>& radioResponseParam,
        const ::android::sp<IRadioIndication>& radioIndicationParam);

public:
    using RadioContext = RadioContextClass<RadioImpl_1_4>;

    RadioImpl_1_4(qcril_instance_id_e_type instance);

    virtual Module* getRilServiceModule() override;

    virtual void createRilServiceModule() override;

    virtual void clearCallbacks();

    Return<void> setResponseFunctions(
        const ::android::sp<IRadioResponse>& radioResponseParam,
        const ::android::sp<IRadioIndication>& radioIndicationParam);

    std::shared_ptr<RadioContext> getContext(int32_t serial);

    virtual void dataCallListChanged(RadioIndicationType indType, hidl_vec<V1_4::SetupDataCallResult> dcResultList);

    virtual void currentPhysicalChannelConfigs(RadioIndicationType indType, hidl_vec<V1_4::PhysicalChannelConfig> physChanConfig);

    virtual void setupDataCallResponse_1_4(RadioResponseInfo responseInfo, V1_4::SetupDataCallResult dcResult);

    virtual void deactivateDataCallResponse(RadioResponseInfo responseInfo);

    virtual ::android::status_t registerAsService(const std::string &serviceName);

    static const QcrildServiceVersion &getVersion();

    virtual const char *getDescriptor() {
        return V1_4::IRadio::descriptor;
    }

    // Forward these to RadioImpl_1_3
    // This is needed because the interface files generated by the hidl compiler do not use virtual inheritance.
    // So, we need to provide a concrete implementation for all virtual methods inherited.
    Return<void> setIndicationFilter_1_2(int32_t serial, ::android::hardware::hidl_bitfield<V1_2::IndicationFilter> indicationFilter) {
        return RadioImpl_1_3::setIndicationFilter_1_2(serial, indicationFilter);
    }

    Return<void> setSignalStrengthReportingCriteria(int32_t serial, int32_t hysteresisMs, int32_t hysteresisDb, const hidl_vec<int32_t>& thresholdsDbm, V1_2::AccessNetwork ran) {
        return RadioImpl_1_3::setSignalStrengthReportingCriteria(serial, hysteresisMs, hysteresisDb, thresholdsDbm, ran);
    }

    Return<void> setLinkCapacityReportingCriteria(int32_t serial, int32_t hysteresisMs, int32_t hysteresisDlKbps, int32_t hysteresisUlKbps, const hidl_vec<int32_t>& thresholdsDownlinkKbps, const hidl_vec<int32_t>& thresholdsUplinkKbps, V1_2::AccessNetwork ran) {
        return RadioImpl_1_3::setLinkCapacityReportingCriteria(serial, hysteresisMs, hysteresisDlKbps, hysteresisUlKbps, thresholdsDownlinkKbps, thresholdsUplinkKbps, ran);
    }

    Return<void> setupDataCall_1_2(int32_t serial, V1_2::AccessNetwork accessNetwork, const V1_0::DataProfileInfo& dataProfileInfo, bool modemCognitive, bool roamingAllowed, bool isRoaming, V1_2::DataRequestReason reason, const hidl_vec<hidl_string>& addresses, const hidl_vec<hidl_string>& dnses) {
        return RadioImpl_1_3::setupDataCall_1_2(serial, accessNetwork, dataProfileInfo, modemCognitive, roamingAllowed, isRoaming, reason, addresses, dnses);
    }

    Return<void> deactivateDataCall_1_2(int32_t serial, int32_t cid, V1_2::DataRequestReason reason);

    virtual int networkScanResultInd(int slotId, int indicationType, int token, RIL_Errno e, void *response, size_t responselen) {
        return RadioImpl_1_3::networkScanResultInd(slotId, indicationType, token, e, response, responselen);
    }

    virtual int sendNetworkScanResult(std::shared_ptr<RilUnsolNetworkScanResultMessage> msg) override;

    Return<void> startNetworkScan_1_2(int32_t serial, const ::android::hardware::radio::V1_2::NetworkScanRequest& request) {
        return RadioImpl_1_3::startNetworkScan_1_2(serial, request);
    }

    Return<void> startNetworkScan_1_4(int32_t serial, const ::android::hardware::radio::V1_2::NetworkScanRequest& request);

    Return<void> getIccCardStatus(int32_t serial);

    Return<void> supplyIccPinForApp(int32_t serial, const ::android::hardware::hidl_string& pin, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::supplyIccPinForApp(serial, pin, aid);
    }

    Return<void> supplyIccPukForApp(int32_t serial, const ::android::hardware::hidl_string& puk, const ::android::hardware::hidl_string& pin, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::supplyIccPukForApp(serial, puk, pin, aid);
    }

    Return<void> supplyIccPin2ForApp(int32_t serial, const ::android::hardware::hidl_string& pin2, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::supplyIccPin2ForApp(serial, pin2, aid);
    }

    Return<void> supplyIccPuk2ForApp(int32_t serial, const ::android::hardware::hidl_string& puk2, const ::android::hardware::hidl_string& pin2, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::supplyIccPuk2ForApp(serial, puk2, pin2, aid);
    }

    Return<void> changeIccPinForApp(int32_t serial, const ::android::hardware::hidl_string& oldPin, const ::android::hardware::hidl_string& newPin, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::changeIccPinForApp(serial, oldPin, newPin, aid);
    }

    Return<void> changeIccPin2ForApp(int32_t serial, const ::android::hardware::hidl_string& oldPin2, const ::android::hardware::hidl_string& newPin2, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::changeIccPin2ForApp(serial, oldPin2, newPin2, aid);
    }

    Return<void> supplyNetworkDepersonalization(int32_t serial, const ::android::hardware::hidl_string& netPin) {
        return RadioImpl_1_3::supplyNetworkDepersonalization(serial, netPin);
    }

    Return<void> getCurrentCalls(int32_t serial) {
        return RadioImpl_1_3::getCurrentCalls(serial);
    }

    Return<void> dial(int32_t serial, const ::android::hardware::radio::V1_0::Dial& dialInfo) {
        return RadioImpl_1_3::dial(serial, dialInfo);
    }

    Return<void> getImsiForApp(int32_t serial, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::getImsiForApp(serial, aid);
    }

    Return<void> hangup(int32_t serial, int32_t gsmIndex) {
        return RadioImpl_1_3::hangup(serial, gsmIndex);
    }

    Return<void> hangupWaitingOrBackground(int32_t serial) {
        return RadioImpl_1_3::hangupWaitingOrBackground(serial);
    }

    Return<void> hangupForegroundResumeBackground(int32_t serial) {
        return RadioImpl_1_3::hangupForegroundResumeBackground(serial);
    }

    Return<void> switchWaitingOrHoldingAndActive(int32_t serial) {
        return RadioImpl_1_3::switchWaitingOrHoldingAndActive(serial);
    }

    Return<void> conference(int32_t serial) {
        return RadioImpl_1_3::conference(serial);
    }

    Return<void> rejectCall(int32_t serial) {
        return RadioImpl_1_3::rejectCall(serial);
    }

    Return<void> getLastCallFailCause(int32_t serial) {
        return RadioImpl_1_3::getLastCallFailCause(serial);
    }

    Return<void> getSignalStrength(int32_t serial) {
        return RadioImpl_1_3::getSignalStrength(serial);
    }

    Return<void> getSignalStrength_1_4(int32_t serial);

    virtual int sendSignalStrength(std::shared_ptr<RilUnsolSignalStrengthMessage> msg) override;

    Return<void> getVoiceRegistrationState(int32_t serial) {
        return RadioImpl_1_3::getVoiceRegistrationState(serial);
    }

    Return<void> getDataRegistrationState(int32_t serial);

    Return<void> getOperator(int32_t serial) {
        return RadioImpl_1_3::getOperator(serial);
    }

    Return<void> setRadioPower(int32_t serial, bool on) {
        return RadioImpl_1_3::setRadioPower(serial, on);
    }

    Return<void> sendDtmf(int32_t serial, const ::android::hardware::hidl_string& s) {
        return RadioImpl_1_3::sendDtmf(serial, s);
    }

    Return<void> sendSms(int32_t serial, const ::android::hardware::radio::V1_0::GsmSmsMessage& message) {
        return RadioImpl_1_3::sendSms(serial, message);
    }

    Return<void> sendSMSExpectMore(int32_t serial, const ::android::hardware::radio::V1_0::GsmSmsMessage& message) {
        return RadioImpl_1_3::sendSMSExpectMore(serial, message);
    }

    Return<void> setupDataCall(int32_t serial, ::android::hardware::radio::V1_0::RadioTechnology radioTechnology, const ::android::hardware::radio::V1_0::DataProfileInfo& dataProfileInfo, bool modemCognitive, bool roamingAllowed, bool isRoaming) {
        return RadioImpl_1_3::setupDataCall(serial, radioTechnology, dataProfileInfo, modemCognitive, roamingAllowed, isRoaming);
    }

    Return<void> iccIOForApp(int32_t serial, const ::android::hardware::radio::V1_0::IccIo& iccIo) {
        return RadioImpl_1_3::iccIOForApp(serial, iccIo);
    }

    Return<void> sendUssd(int32_t serial, const ::android::hardware::hidl_string& ussd) {
        return RadioImpl_1_3::sendUssd(serial, ussd);
    }

    Return<void> cancelPendingUssd(int32_t serial) {
        return RadioImpl_1_3::cancelPendingUssd(serial);
    }

    Return<void> getClir(int32_t serial) {
        return RadioImpl_1_3::getClir(serial);
    }

    Return<void> setClir(int32_t serial, int32_t status) {
        return RadioImpl_1_3::setClir(serial, status);
    }

    Return<void> getCallForwardStatus(int32_t serial, const ::android::hardware::radio::V1_0::CallForwardInfo& callInfo) {
        return RadioImpl_1_3::getCallForwardStatus(serial, callInfo);
    }

    Return<void> setCallForward(int32_t serial, const ::android::hardware::radio::V1_0::CallForwardInfo& callInfo) {
        return RadioImpl_1_3::setCallForward(serial, callInfo);
    }

    Return<void> getCallWaiting(int32_t serial, int32_t serviceClass) {
        return RadioImpl_1_3::getCallWaiting(serial, serviceClass);
    }

    Return<void> setCallWaiting(int32_t serial, bool enable, int32_t serviceClass) {
        return RadioImpl_1_3::setCallWaiting(serial, enable, serviceClass);
    }

    Return<void> acknowledgeLastIncomingGsmSms(int32_t serial, bool success, ::android::hardware::radio::V1_0::SmsAcknowledgeFailCause cause) {
        return RadioImpl_1_3::acknowledgeLastIncomingGsmSms(serial, success, cause);
    }

    Return<void> acceptCall(int32_t serial) {
        return RadioImpl_1_3::acceptCall(serial);
    }

    Return<void> deactivateDataCall(int32_t serial, int32_t cid, bool reasonRadioShutDown) {
        return RadioImpl_1_3::deactivateDataCall(serial, cid, reasonRadioShutDown);
    }

    Return<void> getFacilityLockForApp(int32_t serial, const ::android::hardware::hidl_string& facility, const ::android::hardware::hidl_string& password, int32_t serviceClass, const ::android::hardware::hidl_string& appId) {
        return RadioImpl_1_3::getFacilityLockForApp(serial, facility, password, serviceClass, appId);
    }

    Return<void> setFacilityLockForApp(int32_t serial, const ::android::hardware::hidl_string& facility, bool lockState, const ::android::hardware::hidl_string& password, int32_t serviceClass, const ::android::hardware::hidl_string& appId) {
        return RadioImpl_1_3::setFacilityLockForApp(serial, facility, lockState, password, serviceClass, appId);
    }

    Return<void> setBarringPassword(int32_t serial, const ::android::hardware::hidl_string& facility, const ::android::hardware::hidl_string& oldPassword, const ::android::hardware::hidl_string& newPassword) {
        return RadioImpl_1_3::setBarringPassword(serial, facility, oldPassword, newPassword);
    }

    Return<void> getNetworkSelectionMode(int32_t serial) {
        return RadioImpl_1_3::getNetworkSelectionMode(serial);
    }

    Return<void> setNetworkSelectionModeAutomatic(int32_t serial) {
        return RadioImpl_1_3::setNetworkSelectionModeAutomatic(serial);
    }

    Return<void> setNetworkSelectionModeManual(int32_t serial, const ::android::hardware::hidl_string& operatorNumeric) {
        return RadioImpl_1_3::setNetworkSelectionModeManual(serial, operatorNumeric);
    }

    Return<void> getAvailableNetworks(int32_t serial) {
        return RadioImpl_1_3::getAvailableNetworks(serial);
    }

    Return<void> startDtmf(int32_t serial, const ::android::hardware::hidl_string& s) {
        return RadioImpl_1_3::startDtmf(serial, s);
    }

    Return<void> stopDtmf(int32_t serial) {
        return RadioImpl_1_3::stopDtmf(serial);
    }

    Return<void> getBasebandVersion(int32_t serial) {
        return RadioImpl_1_3::getBasebandVersion(serial);
    }

    Return<void> separateConnection(int32_t serial, int32_t gsmIndex) {
        return RadioImpl_1_3::separateConnection(serial, gsmIndex);
    }

    Return<void> setMute(int32_t serial, bool enable) {
        return RadioImpl_1_3::setMute(serial, enable);
    }

    Return<void> getMute(int32_t serial) {
        return RadioImpl_1_3::getMute(serial);
    }

    Return<void> getClip(int32_t serial) {
        return RadioImpl_1_3::getClip(serial);
    }

    Return<void> getDataCallList(int32_t serial);

    Return<void> setSuppServiceNotifications(int32_t serial, bool enable) {
        return RadioImpl_1_3::setSuppServiceNotifications(serial, enable);
    }

    Return<void> writeSmsToSim(int32_t serial, const ::android::hardware::radio::V1_0::SmsWriteArgs& smsWriteArgs) {
        return RadioImpl_1_3::writeSmsToSim(serial, smsWriteArgs);
    }

    Return<void> deleteSmsOnSim(int32_t serial, int32_t index) {
        return RadioImpl_1_3::deleteSmsOnSim(serial, index);
    }

    Return<void> setBandMode(int32_t serial, ::android::hardware::radio::V1_0::RadioBandMode mode) {
        return RadioImpl_1_3::setBandMode(serial, mode);
    }

    Return<void> getAvailableBandModes(int32_t serial) {
        return RadioImpl_1_3::getAvailableBandModes(serial);
    }

    Return<void> sendEnvelope(int32_t serial, const ::android::hardware::hidl_string& command) {
        return RadioImpl_1_3::sendEnvelope(serial, command);
    }

    Return<void> sendTerminalResponseToSim(int32_t serial, const ::android::hardware::hidl_string& commandResponse) {
        return RadioImpl_1_3::sendTerminalResponseToSim(serial, commandResponse);
    }

    Return<void> handleStkCallSetupRequestFromSim(int32_t serial, bool accept) {
        return RadioImpl_1_3::handleStkCallSetupRequestFromSim(serial, accept);
    }

    Return<void> explicitCallTransfer(int32_t serial) {
        return RadioImpl_1_3::explicitCallTransfer(serial);
    }

    Return<void> setPreferredNetworkType(int32_t serial, ::android::hardware::radio::V1_0::PreferredNetworkType nwType) {
        return RadioImpl_1_3::setPreferredNetworkType(serial, nwType);
    }

    Return<void> getPreferredNetworkType(int32_t serial) {
        return RadioImpl_1_3::getPreferredNetworkType(serial);
    }

    Return<void> getNeighboringCids(int32_t serial) {
        return RadioImpl_1_3::getNeighboringCids(serial);
    }

    Return<void> setLocationUpdates(int32_t serial, bool enable) {
        return RadioImpl_1_3::setLocationUpdates(serial, enable);
    }

    Return<void> setCdmaSubscriptionSource(int32_t serial, ::android::hardware::radio::V1_0::CdmaSubscriptionSource cdmaSub) {
        return RadioImpl_1_3::setCdmaSubscriptionSource(serial, cdmaSub);
    }

    Return<void> setCdmaRoamingPreference(int32_t serial, ::android::hardware::radio::V1_0::CdmaRoamingType type) {
        return RadioImpl_1_3::setCdmaRoamingPreference(serial, type);
    }

    Return<void> getCdmaRoamingPreference(int32_t serial) {
        return RadioImpl_1_3::getCdmaRoamingPreference(serial);
    }

    Return<void> setTTYMode(int32_t serial, ::android::hardware::radio::V1_0::TtyMode mode) {
        return RadioImpl_1_3::setTTYMode(serial, mode);
    }

    Return<void> getTTYMode(int32_t serial) {
        return RadioImpl_1_3::getTTYMode(serial);
    }

    Return<void> setPreferredVoicePrivacy(int32_t serial, bool enable) {
        return RadioImpl_1_3::setPreferredVoicePrivacy(serial, enable);
    }

    Return<void> getPreferredVoicePrivacy(int32_t serial) {
        return RadioImpl_1_3::getPreferredVoicePrivacy(serial);
    }

    Return<void> sendCDMAFeatureCode(int32_t serial, const ::android::hardware::hidl_string& featureCode) {
        return RadioImpl_1_3::sendCDMAFeatureCode(serial, featureCode);
    }

    Return<void> sendBurstDtmf(int32_t serial, const ::android::hardware::hidl_string& dtmf, int32_t on, int32_t off) {
        return RadioImpl_1_3::sendBurstDtmf(serial, dtmf, on, off);
    }

    Return<void> sendCdmaSms(int32_t serial, const ::android::hardware::radio::V1_0::CdmaSmsMessage& sms) {
        return RadioImpl_1_3::sendCdmaSms(serial, sms);
    }

    Return<void> acknowledgeLastIncomingCdmaSms(int32_t serial, const ::android::hardware::radio::V1_0::CdmaSmsAck& smsAck) {
        return RadioImpl_1_3::acknowledgeLastIncomingCdmaSms(serial, smsAck);
    }

    Return<void> getGsmBroadcastConfig(int32_t serial) {
        return RadioImpl_1_3::getGsmBroadcastConfig(serial);
    }

    Return<void> setGsmBroadcastConfig(int32_t serial, const ::android::hardware::hidl_vec<::android::hardware::radio::V1_0::GsmBroadcastSmsConfigInfo>& configInfo) {
        return RadioImpl_1_3::setGsmBroadcastConfig(serial, configInfo);
    }

    Return<void> setGsmBroadcastActivation(int32_t serial, bool activate) {
        return RadioImpl_1_3::setGsmBroadcastActivation(serial, activate);
    }

    Return<void> getCdmaBroadcastConfig(int32_t serial) {
        return RadioImpl_1_3::getCdmaBroadcastConfig(serial);
    }

    Return<void> setCdmaBroadcastConfig(int32_t serial, const ::android::hardware::hidl_vec<::android::hardware::radio::V1_0::CdmaBroadcastSmsConfigInfo>& configInfo) {
        return RadioImpl_1_3::setCdmaBroadcastConfig(serial, configInfo);
    }

    Return<void> setCdmaBroadcastActivation(int32_t serial, bool activate) {
        return RadioImpl_1_3::setCdmaBroadcastActivation(serial, activate);
    }

    Return<void> getCDMASubscription(int32_t serial) {
        return RadioImpl_1_3::getCDMASubscription(serial);
    }

    Return<void> writeSmsToRuim(int32_t serial, const ::android::hardware::radio::V1_0::CdmaSmsWriteArgs& cdmaSms) {
        return RadioImpl_1_3::writeSmsToRuim(serial, cdmaSms);
    }

    Return<void> deleteSmsOnRuim(int32_t serial, int32_t index) {
        return RadioImpl_1_3::deleteSmsOnRuim(serial, index);
    }

    Return<void> getDeviceIdentity(int32_t serial) {
        return RadioImpl_1_3::getDeviceIdentity(serial);
    }

    Return<void> exitEmergencyCallbackMode(int32_t serial) {
        return RadioImpl_1_3::exitEmergencyCallbackMode(serial);
    }

    Return<void> getSmscAddress(int32_t serial) {
        return RadioImpl_1_3::getSmscAddress(serial);
    }

    Return<void> setSmscAddress(int32_t serial, const ::android::hardware::hidl_string& smsc) {
        return RadioImpl_1_3::setSmscAddress(serial, smsc);
    }

    Return<void> reportSmsMemoryStatus(int32_t serial, bool available) {
        return RadioImpl_1_3::reportSmsMemoryStatus(serial, available);
    }

    Return<void> reportStkServiceIsRunning(int32_t serial) {
        return RadioImpl_1_3::reportStkServiceIsRunning(serial);
    }

    Return<void> getCdmaSubscriptionSource(int32_t serial) {
        return RadioImpl_1_3::getCdmaSubscriptionSource(serial);
    }

    Return<void> requestIsimAuthentication(int32_t serial, const ::android::hardware::hidl_string& challenge) {
        return RadioImpl_1_3::requestIsimAuthentication(serial, challenge);
    }

    Return<void> acknowledgeIncomingGsmSmsWithPdu(int32_t serial, bool success, const ::android::hardware::hidl_string& ackPdu) {
        return RadioImpl_1_3::acknowledgeIncomingGsmSmsWithPdu(serial, success, ackPdu);
    }

    Return<void> sendEnvelopeWithStatus(int32_t serial, const ::android::hardware::hidl_string& contents) {
        return RadioImpl_1_3::sendEnvelopeWithStatus(serial, contents);
    }

    Return<void> getVoiceRadioTechnology(int32_t serial) {
        return RadioImpl_1_3::getVoiceRadioTechnology(serial);
    }

    Return<void> getCellInfoList(int32_t serial) {
        return RadioImpl_1_3::getCellInfoList(serial);
    }

    virtual int sendCellInfoListInd(int slotId, int indicationType, int token, RIL_Errno e, void *response, size_t responseLen);

    virtual int sendGetCellInfoListResponse(int slotId, int responseType, int serial, RIL_Errno e, void *response, size_t responseLen);

    Return<void> setCellInfoListRate(int32_t serial, int32_t rate) {
        return RadioImpl_1_3::setCellInfoListRate(serial, rate);
    }

    Return<void> setInitialAttachApn(int32_t serial, const ::android::hardware::radio::V1_0::DataProfileInfo& dataProfileInfo, bool modemCognitive, bool isRoaming) {
        return RadioImpl_1_3::setInitialAttachApn(serial, dataProfileInfo, modemCognitive, isRoaming);
    }

    Return<void> getImsRegistrationState(int32_t serial) {
        return RadioImpl_1_3::getImsRegistrationState(serial);
    }

    Return<void> sendImsSms(int32_t serial, const ::android::hardware::radio::V1_0::ImsSmsMessage& message) {
        return RadioImpl_1_3::sendImsSms(serial, message);
    }

    Return<void> iccTransmitApduBasicChannel(int32_t serial, const ::android::hardware::radio::V1_0::SimApdu& message) {
        return RadioImpl_1_3::iccTransmitApduBasicChannel(serial, message);
    }

    Return<void> iccOpenLogicalChannel(int32_t serial, const ::android::hardware::hidl_string& aid, int32_t p2) {
        return RadioImpl_1_3::iccOpenLogicalChannel(serial, aid, p2);
    }

    Return<void> iccCloseLogicalChannel(int32_t serial, int32_t channelId) {
        return RadioImpl_1_3::iccCloseLogicalChannel(serial, channelId);
    }

    Return<void> iccTransmitApduLogicalChannel(int32_t serial, const ::android::hardware::radio::V1_0::SimApdu& message) {
        return RadioImpl_1_3::iccTransmitApduLogicalChannel(serial, message);
    }

    Return<void> nvReadItem(int32_t serial, ::android::hardware::radio::V1_0::NvItem itemId) {
        return RadioImpl_1_3::nvReadItem(serial, itemId);
    }

    Return<void> nvWriteItem(int32_t serial, const ::android::hardware::radio::V1_0::NvWriteItem& item) {
        return RadioImpl_1_3::nvWriteItem(serial, item);
    }

    Return<void> nvWriteCdmaPrl(int32_t serial, const ::android::hardware::hidl_vec<uint8_t>& prl) {
        return RadioImpl_1_3::nvWriteCdmaPrl(serial, prl);
    }

    Return<void> nvResetConfig(int32_t serial, ::android::hardware::radio::V1_0::ResetNvType resetType) {
        return RadioImpl_1_3::nvResetConfig(serial, resetType);
    }

    Return<void> setUiccSubscription(int32_t serial, const ::android::hardware::radio::V1_0::SelectUiccSub& uiccSub) {
        return RadioImpl_1_3::setUiccSubscription(serial, uiccSub);
    }

    Return<void> setDataAllowed(int32_t serial, bool allow) {
        return RadioImpl_1_3::setDataAllowed(serial, allow);
    }

    Return<void> getHardwareConfig(int32_t serial) {
        return RadioImpl_1_3::getHardwareConfig(serial);
    }

    Return<void> requestIccSimAuthentication(int32_t serial, int32_t authContext, const ::android::hardware::hidl_string& authData, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_3::requestIccSimAuthentication(serial, authContext, authData, aid);
    }

    Return<void> setDataProfile(int32_t serial, const ::android::hardware::hidl_vec<::android::hardware::radio::V1_0::DataProfileInfo>& profiles, bool isRoaming) {
        return RadioImpl_1_3::setDataProfile(serial, profiles, isRoaming);
    }

    Return<void> requestShutdown(int32_t serial) {
        return RadioImpl_1_3::requestShutdown(serial);
    }

    Return<void> getRadioCapability(int32_t serial) {
        return RadioImpl_1_3::getRadioCapability(serial);
    }

    Return<void> setRadioCapability(int32_t serial, const ::android::hardware::radio::V1_0::RadioCapability& rc) {
        return RadioImpl_1_3::setRadioCapability(serial, rc);
    }

    Return<void> startLceService(int32_t serial, int32_t reportInterval, bool pullMode) {
        return RadioImpl_1_3::startLceService(serial, reportInterval, pullMode);
    }

    Return<void> stopLceService(int32_t serial) {
        return RadioImpl_1_3::stopLceService(serial);
    }

    Return<void> pullLceData(int32_t serial) {
        return RadioImpl_1_3::pullLceData(serial);
    }

    Return<void> getModemActivityInfo(int32_t serial) {
        return RadioImpl_1_3::getModemActivityInfo(serial);
    }

    Return<void> setAllowedCarriers(int32_t serial, bool allAllowed, const ::android::hardware::radio::V1_0::CarrierRestrictions& carriers) {
        return RadioImpl_1_3::setAllowedCarriers(serial, allAllowed, carriers);
    }

    Return<void> setAllowedCarriers_1_4(int32_t serial, const V1_4::CarrierRestrictionsWithPriority &carriers, V1_4::SimLockMultiSimPolicy multiSimPolicy);

    Return<void> getAllowedCarriers(int32_t serial) {
        return RadioImpl_1_3::getAllowedCarriers(serial);
    }

    Return<void> getAllowedCarriers_1_4(int32_t serial);

    Return<void> sendDeviceState(int32_t serial, ::android::hardware::radio::V1_0::DeviceStateType deviceStateType, bool state) {
        return RadioImpl_1_3::sendDeviceState(serial, deviceStateType, state);
    }

    Return<void> setIndicationFilter(int32_t serial, ::android::hardware::hidl_bitfield<::android::hardware::radio::V1_0::IndicationFilter> indicationFilter) {
        return RadioImpl_1_3::setIndicationFilter(serial, indicationFilter);
    }

    Return<void> setSimCardPower(int32_t serial, bool powerUp) {
        return RadioImpl_1_3::setSimCardPower(serial, powerUp);
    }

    Return<void> responseAcknowledgement() {
        return RadioImpl_1_3::responseAcknowledgement();
    }

    Return<void> setCarrierInfoForImsiEncryption(int32_t serial, const ::android::hardware::radio::V1_1::ImsiEncryptionInfo& imsiEncryptionInfo) {
        return RadioImpl_1_3::setCarrierInfoForImsiEncryption(serial, imsiEncryptionInfo);
    }

    Return<void> setSimCardPower_1_1(int32_t serial, ::android::hardware::radio::V1_1::CardPowerState powerUp) {
        return RadioImpl_1_3::setSimCardPower_1_1(serial, powerUp);
    }

    Return<void> startNetworkScan(int32_t serial, const ::android::hardware::radio::V1_1::NetworkScanRequest& request) {
        return RadioImpl_1_3::startNetworkScan(serial, request);
    }

    Return<void> stopNetworkScan(int32_t serial) {
        return RadioImpl_1_3::stopNetworkScan(serial);
    }

    void KeepAliveStatusInd(RadioIndicationType indType, const ::android::hardware::radio::V1_1::KeepaliveStatus status);
    Return<void> startKeepalive(int32_t serial, const ::android::hardware::radio::V1_1::KeepaliveRequest& keepalive);
    Return<void> stopKeepalive(int32_t serial, int32_t sessionHandle);

    void updatePcoData(RadioIndicationType indType, const ::android::hardware::radio::V1_0::PcoDataInfo pco);

    void carrierInfoForImsiEncryptionRefresh(RadioIndicationType indType);

    Return<void> enableModem(int32_t serial, bool on) {
        return RadioImpl_1_3::enableModem(serial, on);
    }

    Return<void> setSystemSelectionChannels(int32_t serial, bool specifyChannels,
            const hidl_vec<V1_1::RadioAccessSpecifier>& specifiers) {
        return RadioImpl_1_3::setSystemSelectionChannels(serial, specifyChannels, specifiers);
    }

    Return<void> getModemStackStatus(int32_t serial) {
        return RadioImpl_1_3::getModemStackStatus(serial);
    }

    Return<void> setupDataCall_1_4(int32_t serial, V1_4::AccessNetwork accessNetwork, const V1_4::DataProfileInfo& dataProfileInfo,
            bool roamingAllowed, V1_2::DataRequestReason reason, const hidl_vec<hidl_string>& addresses, const hidl_vec<hidl_string>& dnses);

    Return<void> setInitialAttachApn_1_4(int32_t serial, const V1_4::DataProfileInfo& dataProfileInfo);

    Return<void> setDataProfile_1_4(int32_t serial, const hidl_vec<V1_4::DataProfileInfo>& profiles);

    Return<void> emergencyDial(int32_t serial, const V1_0::Dial& dialInfo, hidl_bitfield<V1_4::EmergencyServiceCategory> categories,
            const hidl_vec<hidl_string>& urns, V1_4::EmergencyCallRouting routing, bool fromEmergencyDialer, bool isTesting);

    Return<void> getPreferredNetworkTypeBitmap(int32_t serial);

    Return<void> setPreferredNetworkTypeBitmap(int32_t serial, hidl_bitfield<V1_4::RadioAccessFamily> networkTypeBitmap);

    void fillDataRegistrationStateResponse(V1_4::DataRegStateResult &out, const RIL_DataRegistrationStateResponse &in);

    virtual int sendcurrentEmergencyNumberList(std::shared_ptr<RilUnsolEmergencyListIndMessage> msg);
};

void convertToHal(V1_4::NrSignalStrength &out /*, const RIL_NR_SignalStrength &in */);
