/******************************************************************************
#  Copyright (c) 2016 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
  ---------------------------------------------------------------------------

  @file    LteDirectDiscovery.pb.c
  @brief   lte direct discovery interface nano pb file

  DESCRIPTION
    lte direct discovery interface nano pb file generated
    from LteDirectDiscovery.proto
  ---------------------------------------------------------------------------
******************************************************************************/

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.8-dev at Thu Mar 17 13:00:49 2016. */

#include "LteDirectDiscovery.pb.h"



const pb_field_t LteDirectDiscovery_MsgHeader_fields[6] = {
    PB_FIELD2(  1, FIXED32 , REQUIRED, STATIC  , FIRST, LteDirectDiscovery_MsgHeader, token, token, 0),
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC  , OTHER, LteDirectDiscovery_MsgHeader, type, token, 0),
    PB_FIELD2(  3, ENUM    , REQUIRED, STATIC  , OTHER, LteDirectDiscovery_MsgHeader, id, type, 0),
    PB_FIELD2(  4, ENUM    , REQUIRED, STATIC  , OTHER, LteDirectDiscovery_MsgHeader, error, id, 0),
    PB_FIELD2(  5, BYTES   , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_MsgHeader, payload, error, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_DeviceCapability_fields[2] = {
    PB_FIELD2(  2, FIXED32 , OPTIONAL, STATIC  , FIRST, LteDirectDiscovery_DeviceCapability, capability, capability, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_Terminate_fields[2] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_Terminate, osAppId, osAppId, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_ServiceStatus_fields[3] = {
    PB_FIELD2(  2, FIXED32 , OPTIONAL, STATIC  , FIRST, LteDirectDiscovery_ServiceStatus, publishAllowed, publishAllowed, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_ServiceStatus, subscribeAllowed, publishAllowed, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_Publish_fields[7] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_Publish, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_Publish, expression, osAppId, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_Publish, expressionValidityTime, expression, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_Publish, metaData, expressionValidityTime, 0),
    PB_FIELD2(  5, ENUM    , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_Publish, discoveryType, metaData, 0),
    PB_FIELD2(  6, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_Publish, duration, discoveryType, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_CancelPublish_fields[3] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_CancelPublish, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_CancelPublish, expression, osAppId, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_Subscribe_fields[6] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_Subscribe, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_Subscribe, expression, osAppId, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_Subscribe, expressionValidityTime, expression, 0),
    PB_FIELD2(  4, ENUM    , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_Subscribe, discoveryType, expressionValidityTime, 0),
    PB_FIELD2(  5, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_Subscribe, duration, discoveryType, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_CancelSubscribe_fields[3] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_CancelSubscribe, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_CancelSubscribe, expression, osAppId, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_AuthorizationResult_fields[3] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_AuthorizationResult, osAppId, osAppId, 0),
    PB_FIELD2(  2, ENUM    , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_AuthorizationResult, result, osAppId, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_ExpressionStatus_fields[4] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_ExpressionStatus, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_ExpressionStatus, expression, osAppId, 0),
    PB_FIELD2(  3, ENUM    , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_ExpressionStatus, result, expression, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_TransmissionStatus_fields[4] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_TransmissionStatus, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_TransmissionStatus, expression, osAppId, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_TransmissionStatus, status, expression, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_ReceptionStatus_fields[4] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_ReceptionStatus, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_ReceptionStatus, expression, osAppId, 0),
    PB_FIELD2(  3, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_ReceptionStatus, status, expression, 0),
    PB_LAST_FIELD
};

const pb_field_t LteDirectDiscovery_MatchEvent_fields[7] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, LteDirectDiscovery_MatchEvent, osAppId, osAppId, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_MatchEvent, expression, osAppId, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_MatchEvent, matchedExpression, expression, 0),
    PB_FIELD2(  4, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_MatchEvent, state, matchedExpression, 0),
    PB_FIELD2(  5, FIXED32 , OPTIONAL, STATIC  , OTHER, LteDirectDiscovery_MatchEvent, metaDataIndex, state, 0),
    PB_FIELD2(  6, STRING  , OPTIONAL, CALLBACK, OTHER, LteDirectDiscovery_MatchEvent, metaData, metaDataIndex, 0),
    PB_LAST_FIELD
};


