// ============================================================================
// Copyright (c) 2016-2018 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
// ============================================================================
#ifndef __CHAVENTOKENAPP_H
#define __CHAVENTOKENAPP_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CHavenTokenApp_UID UINT32_C(78)

#endif /* __CHAVENTOKENAPP_H */
