#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2018 Qualcomm Technologies, Inc.  
// All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

#define CKeymasterApp_UID UINT32_C(121)


