/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Tue Jun 25 12:07:43 2019. */

#ifndef PB_SNS_WIGIG_PB_H_INCLUDED
#define PB_SNS_WIGIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _sns_wigig_result {
    SNS_WIGIG_RESULT_SUCCESS = 0,
    SNS_WIGIG_RESULT_FAILURE = 1
} sns_wigig_result;
#define _sns_wigig_result_MIN SNS_WIGIG_RESULT_SUCCESS
#define _sns_wigig_result_MAX SNS_WIGIG_RESULT_FAILURE
#define _sns_wigig_result_ARRAYSIZE ((sns_wigig_result)(SNS_WIGIG_RESULT_FAILURE+1))
#define sns_wigig_result_SNS_WIGIG_RESULT_SUCCESS SNS_WIGIG_RESULT_SUCCESS
#define sns_wigig_result_SNS_WIGIG_RESULT_FAILURE SNS_WIGIG_RESULT_FAILURE

typedef enum _sns_wigig_mode {
    SNS_WIGIG_MODE_SEARCH = 1,
    SNS_WIGIG_MODE_FACIAL_RECOGNITION = 2,
    SNS_WIGIG_MODE_GESTURE_DETECTION = 3,
    SNS_WIGIG_MODE_STOP = 7,
    SNS_WIGIG_MODE_CUSTOM = 15
} sns_wigig_mode;
#define _sns_wigig_mode_MIN SNS_WIGIG_MODE_SEARCH
#define _sns_wigig_mode_MAX SNS_WIGIG_MODE_CUSTOM
#define _sns_wigig_mode_ARRAYSIZE ((sns_wigig_mode)(SNS_WIGIG_MODE_CUSTOM+1))
#define sns_wigig_mode_SNS_WIGIG_MODE_SEARCH SNS_WIGIG_MODE_SEARCH
#define sns_wigig_mode_SNS_WIGIG_MODE_FACIAL_RECOGNITION SNS_WIGIG_MODE_FACIAL_RECOGNITION
#define sns_wigig_mode_SNS_WIGIG_MODE_GESTURE_DETECTION SNS_WIGIG_MODE_GESTURE_DETECTION
#define sns_wigig_mode_SNS_WIGIG_MODE_STOP SNS_WIGIG_MODE_STOP
#define sns_wigig_mode_SNS_WIGIG_MODE_CUSTOM SNS_WIGIG_MODE_CUSTOM

typedef enum _sns_wigig_msgid {
    SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_REQ = 512,
    SNS_WIGIG_MSGID_SNS_WIGIG_CHANGE_MODE_REQ = 513,
    SNS_WIGIG_MSGID_SNS_WIGIG_GET_PARAMS_REQ = 514,
    SNS_WIGIG_MSGID_SNS_WIGIG_DEBUG_REQ = 515,
    SNS_WIGIG_MSGID_SNS_WIGIG_GET_MODE_REQ = 516,
    SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_RESP = 1024,
    SNS_WIGIG_MSGID_SNS_WIGIG_GET_PARAMS_RESP = 1025,
    SNS_WIGIG_MSGID_SNS_WIGIG_DEBUG_RESP = 1026,
    SNS_WIGIG_MSGID_SNS_WIGIG_GET_MODE_RESP = 1027,
    SNS_WIGIG_MSGID_SNS_WIGIG_READY_EVENT = 1028,
    SNS_WIGIG_MSGID_SNS_WIGIG_RESET_EVENT = 1029,
    SNS_WIGIG_MSGID_SNS_WIGIG_CIR_DATA_READY_EVENT = 1030,
    SNS_WIGIG_MSGID_SNS_WIGIG_BURST_SIZE_EVENT = 1031
} sns_wigig_msgid;
#define _sns_wigig_msgid_MIN SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_REQ
#define _sns_wigig_msgid_MAX SNS_WIGIG_MSGID_SNS_WIGIG_BURST_SIZE_EVENT
#define _sns_wigig_msgid_ARRAYSIZE ((sns_wigig_msgid)(SNS_WIGIG_MSGID_SNS_WIGIG_BURST_SIZE_EVENT+1))
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_REQ SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_REQ
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_CHANGE_MODE_REQ SNS_WIGIG_MSGID_SNS_WIGIG_CHANGE_MODE_REQ
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_GET_PARAMS_REQ SNS_WIGIG_MSGID_SNS_WIGIG_GET_PARAMS_REQ
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_DEBUG_REQ SNS_WIGIG_MSGID_SNS_WIGIG_DEBUG_REQ
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_GET_MODE_REQ SNS_WIGIG_MSGID_SNS_WIGIG_GET_MODE_REQ
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_RESP SNS_WIGIG_MSGID_SNS_WIGIG_AUTO_RECOVERY_RESP
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_GET_PARAMS_RESP SNS_WIGIG_MSGID_SNS_WIGIG_GET_PARAMS_RESP
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_DEBUG_RESP SNS_WIGIG_MSGID_SNS_WIGIG_DEBUG_RESP
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_GET_MODE_RESP SNS_WIGIG_MSGID_SNS_WIGIG_GET_MODE_RESP
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_READY_EVENT SNS_WIGIG_MSGID_SNS_WIGIG_READY_EVENT
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_RESET_EVENT SNS_WIGIG_MSGID_SNS_WIGIG_RESET_EVENT
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_CIR_DATA_READY_EVENT SNS_WIGIG_MSGID_SNS_WIGIG_CIR_DATA_READY_EVENT
#define sns_wigig_msgid_SNS_WIGIG_MSGID_SNS_WIGIG_BURST_SIZE_EVENT SNS_WIGIG_MSGID_SNS_WIGIG_BURST_SIZE_EVENT

/* Struct definitions */
typedef struct _sns_wigig_auto_recovery_req {
    char dummy_field;
/* @@protoc_insertion_point(struct:sns_wigig_auto_recovery_req) */
} sns_wigig_auto_recovery_req;

typedef struct _sns_wigig_get_mode_req {
    char dummy_field;
/* @@protoc_insertion_point(struct:sns_wigig_get_mode_req) */
} sns_wigig_get_mode_req;

typedef struct _sns_wigig_get_params_req {
    char dummy_field;
/* @@protoc_insertion_point(struct:sns_wigig_get_params_req) */
} sns_wigig_get_params_req;

typedef struct _sns_wigig_ready_event {
    char dummy_field;
/* @@protoc_insertion_point(struct:sns_wigig_ready_event) */
} sns_wigig_ready_event;

typedef struct _sns_wigig_reset_event {
    char dummy_field;
/* @@protoc_insertion_point(struct:sns_wigig_reset_event) */
} sns_wigig_reset_event;

typedef struct _sns_wigig_auto_recovery_resp {
    uint32_t error;
/* @@protoc_insertion_point(struct:sns_wigig_auto_recovery_resp) */
} sns_wigig_auto_recovery_resp;

typedef struct _sns_wigig_burst_size_event {
    uint32_t burst_size;
/* @@protoc_insertion_point(struct:sns_wigig_burst_size_event) */
} sns_wigig_burst_size_event;

typedef struct _sns_wigig_change_mode_req {
    sns_wigig_mode mode;
    bool has_channel;
    uint32_t channel;
/* @@protoc_insertion_point(struct:sns_wigig_change_mode_req) */
} sns_wigig_change_mode_req;

typedef struct _sns_wigig_cir_data_ready_event {
    uint64_t timestamp;
    bool mf;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:sns_wigig_cir_data_ready_event) */
} sns_wigig_cir_data_ready_event;

typedef struct _sns_wigig_debug_req {
    uint32_t req_id;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:sns_wigig_debug_req) */
} sns_wigig_debug_req;

typedef struct _sns_wigig_debug_resp {
    uint32_t error;
    uint32_t req_id;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:sns_wigig_debug_resp) */
} sns_wigig_debug_resp;

typedef struct _sns_wigig_get_mode_resp {
    uint32_t error;
    sns_wigig_mode mode;
/* @@protoc_insertion_point(struct:sns_wigig_get_mode_resp) */
} sns_wigig_get_mode_resp;

typedef struct _sns_wigig_get_params_resp {
    uint32_t error;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:sns_wigig_get_params_resp) */
} sns_wigig_get_params_resp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define sns_wigig_auto_recovery_req_init_default {0}
#define sns_wigig_change_mode_req_init_default   {_sns_wigig_mode_MIN, false, 0}
#define sns_wigig_get_params_req_init_default    {0}
#define sns_wigig_debug_req_init_default         {0, {{NULL}, NULL}}
#define sns_wigig_get_mode_req_init_default      {0}
#define sns_wigig_auto_recovery_resp_init_default {0}
#define sns_wigig_get_params_resp_init_default   {0, {{NULL}, NULL}}
#define sns_wigig_debug_resp_init_default        {0, 0, {{NULL}, NULL}}
#define sns_wigig_get_mode_resp_init_default     {0, _sns_wigig_mode_MIN}
#define sns_wigig_ready_event_init_default       {0}
#define sns_wigig_reset_event_init_default       {0}
#define sns_wigig_cir_data_ready_event_init_default {0, 0, {{NULL}, NULL}}
#define sns_wigig_burst_size_event_init_default  {0}
#define sns_wigig_auto_recovery_req_init_zero    {0}
#define sns_wigig_change_mode_req_init_zero      {_sns_wigig_mode_MIN, false, 0}
#define sns_wigig_get_params_req_init_zero       {0}
#define sns_wigig_debug_req_init_zero            {0, {{NULL}, NULL}}
#define sns_wigig_get_mode_req_init_zero         {0}
#define sns_wigig_auto_recovery_resp_init_zero   {0}
#define sns_wigig_get_params_resp_init_zero      {0, {{NULL}, NULL}}
#define sns_wigig_debug_resp_init_zero           {0, 0, {{NULL}, NULL}}
#define sns_wigig_get_mode_resp_init_zero        {0, _sns_wigig_mode_MIN}
#define sns_wigig_ready_event_init_zero          {0}
#define sns_wigig_reset_event_init_zero          {0}
#define sns_wigig_cir_data_ready_event_init_zero {0, 0, {{NULL}, NULL}}
#define sns_wigig_burst_size_event_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define sns_wigig_auto_recovery_resp_error_tag   1
#define sns_wigig_burst_size_event_burst_size_tag 1
#define sns_wigig_change_mode_req_mode_tag       1
#define sns_wigig_change_mode_req_channel_tag    2
#define sns_wigig_cir_data_ready_event_timestamp_tag 1
#define sns_wigig_cir_data_ready_event_mf_tag    2
#define sns_wigig_cir_data_ready_event_data_tag  3
#define sns_wigig_debug_req_req_id_tag           1
#define sns_wigig_debug_req_data_tag             2
#define sns_wigig_debug_resp_error_tag           1
#define sns_wigig_debug_resp_req_id_tag          2
#define sns_wigig_debug_resp_data_tag            3
#define sns_wigig_get_mode_resp_error_tag        1
#define sns_wigig_get_mode_resp_mode_tag         2
#define sns_wigig_get_params_resp_error_tag      1
#define sns_wigig_get_params_resp_data_tag       2

/* Struct field encoding specification for nanopb */
extern const pb_field_t sns_wigig_auto_recovery_req_fields[1];
extern const pb_field_t sns_wigig_change_mode_req_fields[3];
extern const pb_field_t sns_wigig_get_params_req_fields[1];
extern const pb_field_t sns_wigig_debug_req_fields[3];
extern const pb_field_t sns_wigig_get_mode_req_fields[1];
extern const pb_field_t sns_wigig_auto_recovery_resp_fields[2];
extern const pb_field_t sns_wigig_get_params_resp_fields[3];
extern const pb_field_t sns_wigig_debug_resp_fields[4];
extern const pb_field_t sns_wigig_get_mode_resp_fields[3];
extern const pb_field_t sns_wigig_ready_event_fields[1];
extern const pb_field_t sns_wigig_reset_event_fields[1];
extern const pb_field_t sns_wigig_cir_data_ready_event_fields[4];
extern const pb_field_t sns_wigig_burst_size_event_fields[2];

/* Maximum encoded size of messages (where known) */
#define sns_wigig_auto_recovery_req_size         0
#define sns_wigig_change_mode_req_size           8
#define sns_wigig_get_params_req_size            0
/* sns_wigig_debug_req_size depends on runtime parameters */
#define sns_wigig_get_mode_req_size              0
#define sns_wigig_auto_recovery_resp_size        6
/* sns_wigig_get_params_resp_size depends on runtime parameters */
/* sns_wigig_debug_resp_size depends on runtime parameters */
#define sns_wigig_get_mode_resp_size             8
#define sns_wigig_ready_event_size               0
#define sns_wigig_reset_event_size               0
/* sns_wigig_cir_data_ready_event_size depends on runtime parameters */
#define sns_wigig_burst_size_event_size          6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SNS_WIGIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
