/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Jun 25 12:07:43 2019. */

#include "sns_wigig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sns_wigig_auto_recovery_req_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_change_mode_req_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, sns_wigig_change_mode_req, mode, mode, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, sns_wigig_change_mode_req, channel, mode, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_get_params_req_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_debug_req_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sns_wigig_debug_req, req_id, req_id, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, sns_wigig_debug_req, data, req_id, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_get_mode_req_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_auto_recovery_resp_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sns_wigig_auto_recovery_resp, error, error, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_get_params_resp_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sns_wigig_get_params_resp, error, error, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, sns_wigig_get_params_resp, data, error, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_debug_resp_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sns_wigig_debug_resp, error, error, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, sns_wigig_debug_resp, req_id, error, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, CALLBACK, OTHER, sns_wigig_debug_resp, data, req_id, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_get_mode_resp_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sns_wigig_get_mode_resp, error, error, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, sns_wigig_get_mode_resp, mode, error, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_ready_event_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_reset_event_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_cir_data_ready_event_fields[4] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, sns_wigig_cir_data_ready_event, timestamp, timestamp, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, sns_wigig_cir_data_ready_event, mf, timestamp, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, CALLBACK, OTHER, sns_wigig_cir_data_ready_event, data, mf, 0),
    PB_LAST_FIELD
};

const pb_field_t sns_wigig_burst_size_event_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sns_wigig_burst_size_event, burst_size, burst_size, 0),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
