/******************************************************************************
#  Copyright (c) 2019 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#******************************************************************************/
#pragma once

#include <memory>
#include <android/hardware/radio/1.3/IRadio.h>
#include <android/hardware/radio/1.3/IRadioResponse.h>
#include <android/hardware/radio/1.3/IRadioIndication.h>
#include <telephony/ril.h>
#include <ril_internal.h>
#include <ril_service.h>
#include <utils/SystemClock.h>
#include <inttypes.h>
#include <RadioContext.h>
#include <request/LinkCapIndMessage.h>
#include <modules/nas/NasSetSignalStrengthCriteria.h>
#include <modules/nas/NasModule.h>
#include <ril_service_1_2.h>

using namespace android::hardware::radio;
using namespace android::hardware::radio::V1_0;
using namespace android::hardware::radio::deprecated::V1_0;
using ::android::hardware::Return;
using ::android::hardware::hidl_string;
using ::android::hardware::hidl_vec;
using ::android::hardware::hidl_array;
using ::android::hardware::Void;
using android::CommandInfo;
using android::RequestInfo;
using android::requestToString;
using android::sp;

class RadioImpl_1_3 : public RadioImpl_1_2, public V1_3::IRadio {
    sp<V1_3::IRadioResponse> mRadioResponseV1_3;
    sp<V1_3::IRadioIndication> mRadioIndicationV1_3;

protected:
    Return<void> setResponseFunctions_nolock(
        const ::android::sp<IRadioResponse>& radioResponseParam,
        const ::android::sp<IRadioIndication>& radioIndicationParam);

public:
    using RadioContext = RadioContextClass<RadioImpl_1_3>;

    RadioImpl_1_3(qcril_instance_id_e_type instance);

    virtual Module* getRilServiceModule() override;

    virtual void createRilServiceModule() override;

    virtual void clearCallbacks();

    Return<void> setResponseFunctions(
        const ::android::sp<IRadioResponse>& radioResponseParam,
        const ::android::sp<IRadioIndication>& radioIndicationParam);

    std::shared_ptr<RadioContext> getContext(int32_t serial);

    virtual ::android::status_t registerAsService(const std::string &serviceName);

    static const QcrildServiceVersion &getVersion();

    virtual const char *getDescriptor() {
        return V1_3::IRadio::descriptor;
    }

    // Forward these to RadioImpl_1_2
    // This is needed because the interface files generated by the hidl compiler do not use virtual inheritance.
    // So, we need to provide a concrete implementation for all virtual methods inherited.
    Return<void> setIndicationFilter_1_2(int32_t serial, ::android::hardware::hidl_bitfield<V1_2::IndicationFilter> indicationFilter) {
        return RadioImpl_1_2::setIndicationFilter_1_2(serial, indicationFilter);
    }

    Return<void> setSignalStrengthReportingCriteria(int32_t serial, int32_t hysteresisMs, int32_t hysteresisDb, const hidl_vec<int32_t>& thresholdsDbm, V1_2::AccessNetwork ran) {
        return RadioImpl_1_2::setSignalStrengthReportingCriteria(serial, hysteresisMs, hysteresisDb, thresholdsDbm, ran);
    }

    Return<void> setLinkCapacityReportingCriteria(int32_t serial, int32_t hysteresisMs, int32_t hysteresisDlKbps, int32_t hysteresisUlKbps, const hidl_vec<int32_t>& thresholdsDownlinkKbps, const hidl_vec<int32_t>& thresholdsUplinkKbps, V1_2::AccessNetwork ran) {
        return RadioImpl_1_2::setLinkCapacityReportingCriteria(serial, hysteresisMs, hysteresisDlKbps, hysteresisUlKbps, thresholdsDownlinkKbps, thresholdsUplinkKbps, ran);
    }

    Return<void> setupDataCall_1_2(int32_t serial, V1_2::AccessNetwork accessNetwork, const V1_0::DataProfileInfo& dataProfileInfo, bool modemCognitive, bool roamingAllowed, bool isRoaming, V1_2::DataRequestReason reason, const hidl_vec<hidl_string>& addresses, const hidl_vec<hidl_string>& dnses) {
        return RadioImpl_1_2::setupDataCall_1_2(serial, accessNetwork, dataProfileInfo, modemCognitive, roamingAllowed, isRoaming, reason, addresses, dnses);
    }

    Return<void> deactivateDataCall_1_2(int32_t serial, int32_t cid, V1_2::DataRequestReason reason) {
        return RadioImpl_1_2::deactivateDataCall_1_2(serial, cid, reason);
    }

    virtual int networkScanResultInd(int slotId, int indicationType, int token, RIL_Errno e, void *response, size_t responselen) {
        return RadioImpl_1_2::networkScanResultInd(slotId, indicationType, token, e, response, responselen);
    }

    Return<void> startNetworkScan_1_2(int32_t serial, const ::android::hardware::radio::V1_2::NetworkScanRequest& request) {
        return RadioImpl_1_2::startNetworkScan_1_2(serial, request);
    }

    Return<void> getIccCardStatus(int32_t serial) {
        return RadioImpl_1_2::getIccCardStatus(serial);
    }

    Return<void> supplyIccPinForApp(int32_t serial, const ::android::hardware::hidl_string& pin, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::supplyIccPinForApp(serial, pin, aid);
    }

    Return<void> supplyIccPukForApp(int32_t serial, const ::android::hardware::hidl_string& puk, const ::android::hardware::hidl_string& pin, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::supplyIccPukForApp(serial, puk, pin, aid);
    }

    Return<void> supplyIccPin2ForApp(int32_t serial, const ::android::hardware::hidl_string& pin2, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::supplyIccPin2ForApp(serial, pin2, aid);
    }

    Return<void> supplyIccPuk2ForApp(int32_t serial, const ::android::hardware::hidl_string& puk2, const ::android::hardware::hidl_string& pin2, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::supplyIccPuk2ForApp(serial, puk2, pin2, aid);
    }

    Return<void> changeIccPinForApp(int32_t serial, const ::android::hardware::hidl_string& oldPin, const ::android::hardware::hidl_string& newPin, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::changeIccPinForApp(serial, oldPin, newPin, aid);
    }

    Return<void> changeIccPin2ForApp(int32_t serial, const ::android::hardware::hidl_string& oldPin2, const ::android::hardware::hidl_string& newPin2, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::changeIccPin2ForApp(serial, oldPin2, newPin2, aid);
    }

    Return<void> supplyNetworkDepersonalization(int32_t serial, const ::android::hardware::hidl_string& netPin) {
        return RadioImpl_1_2::supplyNetworkDepersonalization(serial, netPin);
    }

    Return<void> getCurrentCalls(int32_t serial) {
        return RadioImpl_1_2::getCurrentCalls(serial);
    }

    Return<void> dial(int32_t serial, const ::android::hardware::radio::V1_0::Dial& dialInfo) {
        return RadioImpl_1_2::dial(serial, dialInfo);
    }

    Return<void> getImsiForApp(int32_t serial, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::getImsiForApp(serial, aid);
    }

    Return<void> hangup(int32_t serial, int32_t gsmIndex) {
        return RadioImpl_1_2::hangup(serial, gsmIndex);
    }

    Return<void> hangupWaitingOrBackground(int32_t serial) {
        return RadioImpl_1_2::hangupWaitingOrBackground(serial);
    }

    Return<void> hangupForegroundResumeBackground(int32_t serial) {
        return RadioImpl_1_2::hangupForegroundResumeBackground(serial);
    }

    Return<void> switchWaitingOrHoldingAndActive(int32_t serial) {
        return RadioImpl_1_2::switchWaitingOrHoldingAndActive(serial);
    }

    Return<void> conference(int32_t serial) {
        return RadioImpl_1_2::conference(serial);
    }

    Return<void> rejectCall(int32_t serial) {
        return RadioImpl_1_2::rejectCall(serial);
    }

    Return<void> getLastCallFailCause(int32_t serial) {
        return RadioImpl_1_2::getLastCallFailCause(serial);
    }

    Return<void> getSignalStrength(int32_t serial) {
        return RadioImpl_1_2::getSignalStrength(serial);
    }

    Return<void> getVoiceRegistrationState(int32_t serial) {
        return RadioImpl_1_2::getVoiceRegistrationState(serial);
    }

    Return<void> getDataRegistrationState(int32_t serial) {
        return RadioImpl_1_2::getDataRegistrationState(serial);
    }

    Return<void> getOperator(int32_t serial) {
        return RadioImpl_1_2::getOperator(serial);
    }

    Return<void> setRadioPower(int32_t serial, bool on) {
        return RadioImpl_1_2::setRadioPower(serial, on);
    }

    Return<void> sendDtmf(int32_t serial, const ::android::hardware::hidl_string& s) {
        return RadioImpl_1_2::sendDtmf(serial, s);
    }

    Return<void> sendSms(int32_t serial, const ::android::hardware::radio::V1_0::GsmSmsMessage& message) {
        return RadioImpl_1_2::sendSms(serial, message);
    }

    Return<void> sendSMSExpectMore(int32_t serial, const ::android::hardware::radio::V1_0::GsmSmsMessage& message) {
        return RadioImpl_1_2::sendSMSExpectMore(serial, message);
    }

    Return<void> setupDataCall(int32_t serial, ::android::hardware::radio::V1_0::RadioTechnology radioTechnology, const ::android::hardware::radio::V1_0::DataProfileInfo& dataProfileInfo, bool modemCognitive, bool roamingAllowed, bool isRoaming) {
        return RadioImpl_1_2::setupDataCall(serial, radioTechnology, dataProfileInfo, modemCognitive, roamingAllowed, isRoaming);
    }

    Return<void> iccIOForApp(int32_t serial, const ::android::hardware::radio::V1_0::IccIo& iccIo) {
        return RadioImpl_1_2::iccIOForApp(serial, iccIo);
    }

    Return<void> sendUssd(int32_t serial, const ::android::hardware::hidl_string& ussd) {
        return RadioImpl_1_2::sendUssd(serial, ussd);
    }

    Return<void> cancelPendingUssd(int32_t serial) {
        return RadioImpl_1_2::cancelPendingUssd(serial);
    }

    Return<void> getClir(int32_t serial) {
        return RadioImpl_1_2::getClir(serial);
    }

    Return<void> setClir(int32_t serial, int32_t status) {
        return RadioImpl_1_2::setClir(serial, status);
    }

    Return<void> getCallForwardStatus(int32_t serial, const ::android::hardware::radio::V1_0::CallForwardInfo& callInfo) {
        return RadioImpl_1_2::getCallForwardStatus(serial, callInfo);
    }

    Return<void> setCallForward(int32_t serial, const ::android::hardware::radio::V1_0::CallForwardInfo& callInfo) {
        return RadioImpl_1_2::setCallForward(serial, callInfo);
    }

    Return<void> getCallWaiting(int32_t serial, int32_t serviceClass) {
        return RadioImpl_1_2::getCallWaiting(serial, serviceClass);
    }

    Return<void> setCallWaiting(int32_t serial, bool enable, int32_t serviceClass) {
        return RadioImpl_1_2::setCallWaiting(serial, enable, serviceClass);
    }

    Return<void> acknowledgeLastIncomingGsmSms(int32_t serial, bool success, ::android::hardware::radio::V1_0::SmsAcknowledgeFailCause cause) {
        return RadioImpl_1_2::acknowledgeLastIncomingGsmSms(serial, success, cause);
    }

    Return<void> acceptCall(int32_t serial) {
        return RadioImpl_1_2::acceptCall(serial);
    }

    Return<void> deactivateDataCall(int32_t serial, int32_t cid, bool reasonRadioShutDown) {
        return RadioImpl_1_2::deactivateDataCall(serial, cid, reasonRadioShutDown);
    }

    Return<void> getFacilityLockForApp(int32_t serial, const ::android::hardware::hidl_string& facility, const ::android::hardware::hidl_string& password, int32_t serviceClass, const ::android::hardware::hidl_string& appId) {
        return RadioImpl_1_2::getFacilityLockForApp(serial, facility, password, serviceClass, appId);
    }

    Return<void> setFacilityLockForApp(int32_t serial, const ::android::hardware::hidl_string& facility, bool lockState, const ::android::hardware::hidl_string& password, int32_t serviceClass, const ::android::hardware::hidl_string& appId) {
        return RadioImpl_1_2::setFacilityLockForApp(serial, facility, lockState, password, serviceClass, appId);
    }

    Return<void> setBarringPassword(int32_t serial, const ::android::hardware::hidl_string& facility, const ::android::hardware::hidl_string& oldPassword, const ::android::hardware::hidl_string& newPassword) {
        return RadioImpl_1_2::setBarringPassword(serial, facility, oldPassword, newPassword);
    }

    Return<void> getNetworkSelectionMode(int32_t serial) {
        return RadioImpl_1_2::getNetworkSelectionMode(serial);
    }

    Return<void> setNetworkSelectionModeAutomatic(int32_t serial) {
        return RadioImpl_1_2::setNetworkSelectionModeAutomatic(serial);
    }

    Return<void> setNetworkSelectionModeManual(int32_t serial, const ::android::hardware::hidl_string& operatorNumeric) {
        return RadioImpl_1_2::setNetworkSelectionModeManual(serial, operatorNumeric);
    }

    Return<void> getAvailableNetworks(int32_t serial) {
        return RadioImpl_1_2::getAvailableNetworks(serial);
    }

    Return<void> startDtmf(int32_t serial, const ::android::hardware::hidl_string& s) {
        return RadioImpl_1_2::startDtmf(serial, s);
    }

    Return<void> stopDtmf(int32_t serial) {
        return RadioImpl_1_2::stopDtmf(serial);
    }

    Return<void> getBasebandVersion(int32_t serial) {
        return RadioImpl_1_2::getBasebandVersion(serial);
    }

    Return<void> separateConnection(int32_t serial, int32_t gsmIndex) {
        return RadioImpl_1_2::separateConnection(serial, gsmIndex);
    }

    Return<void> setMute(int32_t serial, bool enable) {
        return RadioImpl_1_2::setMute(serial, enable);
    }

    Return<void> getMute(int32_t serial) {
        return RadioImpl_1_2::getMute(serial);
    }

    Return<void> getClip(int32_t serial) {
        return RadioImpl_1_2::getClip(serial);
    }

    Return<void> getDataCallList(int32_t serial) {
        return RadioImpl_1_2::getDataCallList(serial);
    }

    Return<void> setSuppServiceNotifications(int32_t serial, bool enable) {
        return RadioImpl_1_2::setSuppServiceNotifications(serial, enable);
    }

    Return<void> writeSmsToSim(int32_t serial, const ::android::hardware::radio::V1_0::SmsWriteArgs& smsWriteArgs) {
        return RadioImpl_1_2::writeSmsToSim(serial, smsWriteArgs);
    }

    Return<void> deleteSmsOnSim(int32_t serial, int32_t index) {
        return RadioImpl_1_2::deleteSmsOnSim(serial, index);
    }

    Return<void> setBandMode(int32_t serial, ::android::hardware::radio::V1_0::RadioBandMode mode) {
        return RadioImpl_1_2::setBandMode(serial, mode);
    }

    Return<void> getAvailableBandModes(int32_t serial) {
        return RadioImpl_1_2::getAvailableBandModes(serial);
    }

    Return<void> sendEnvelope(int32_t serial, const ::android::hardware::hidl_string& command) {
        return RadioImpl_1_2::sendEnvelope(serial, command);
    }

    Return<void> sendTerminalResponseToSim(int32_t serial, const ::android::hardware::hidl_string& commandResponse) {
        return RadioImpl_1_2::sendTerminalResponseToSim(serial, commandResponse);
    }

    Return<void> handleStkCallSetupRequestFromSim(int32_t serial, bool accept) {
        return RadioImpl_1_2::handleStkCallSetupRequestFromSim(serial, accept);
    }

    Return<void> explicitCallTransfer(int32_t serial) {
        return RadioImpl_1_2::explicitCallTransfer(serial);
    }

    Return<void> setPreferredNetworkType(int32_t serial, ::android::hardware::radio::V1_0::PreferredNetworkType nwType) {
        return RadioImpl_1_2::setPreferredNetworkType(serial, nwType);
    }

    Return<void> getPreferredNetworkType(int32_t serial) {
        return RadioImpl_1_2::getPreferredNetworkType(serial);
    }

    Return<void> getNeighboringCids(int32_t serial) {
        return RadioImpl_1_2::getNeighboringCids(serial);
    }

    Return<void> setLocationUpdates(int32_t serial, bool enable) {
        return RadioImpl_1_2::setLocationUpdates(serial, enable);
    }

    Return<void> setCdmaSubscriptionSource(int32_t serial, ::android::hardware::radio::V1_0::CdmaSubscriptionSource cdmaSub) {
        return RadioImpl_1_2::setCdmaSubscriptionSource(serial, cdmaSub);
    }

    Return<void> setCdmaRoamingPreference(int32_t serial, ::android::hardware::radio::V1_0::CdmaRoamingType type) {
        return RadioImpl_1_2::setCdmaRoamingPreference(serial, type);
    }

    Return<void> getCdmaRoamingPreference(int32_t serial) {
        return RadioImpl_1_2::getCdmaRoamingPreference(serial);
    }

    Return<void> setTTYMode(int32_t serial, ::android::hardware::radio::V1_0::TtyMode mode) {
        return RadioImpl_1_2::setTTYMode(serial, mode);
    }

    Return<void> getTTYMode(int32_t serial) {
        return RadioImpl_1_2::getTTYMode(serial);
    }

    Return<void> setPreferredVoicePrivacy(int32_t serial, bool enable) {
        return RadioImpl_1_2::setPreferredVoicePrivacy(serial, enable);
    }

    Return<void> getPreferredVoicePrivacy(int32_t serial) {
        return RadioImpl_1_2::getPreferredVoicePrivacy(serial);
    }

    Return<void> sendCDMAFeatureCode(int32_t serial, const ::android::hardware::hidl_string& featureCode) {
        return RadioImpl_1_2::sendCDMAFeatureCode(serial, featureCode);
    }

    Return<void> sendBurstDtmf(int32_t serial, const ::android::hardware::hidl_string& dtmf, int32_t on, int32_t off) {
        return RadioImpl_1_2::sendBurstDtmf(serial, dtmf, on, off);
    }

    Return<void> sendCdmaSms(int32_t serial, const ::android::hardware::radio::V1_0::CdmaSmsMessage& sms) {
        return RadioImpl_1_2::sendCdmaSms(serial, sms);
    }

    Return<void> acknowledgeLastIncomingCdmaSms(int32_t serial, const ::android::hardware::radio::V1_0::CdmaSmsAck& smsAck) {
        return RadioImpl_1_2::acknowledgeLastIncomingCdmaSms(serial, smsAck);
    }

    Return<void> getGsmBroadcastConfig(int32_t serial) {
        return RadioImpl_1_2::getGsmBroadcastConfig(serial);
    }

    Return<void> setGsmBroadcastConfig(int32_t serial, const ::android::hardware::hidl_vec<::android::hardware::radio::V1_0::GsmBroadcastSmsConfigInfo>& configInfo) {
        return RadioImpl_1_2::setGsmBroadcastConfig(serial, configInfo);
    }

    Return<void> setGsmBroadcastActivation(int32_t serial, bool activate) {
        return RadioImpl_1_2::setGsmBroadcastActivation(serial, activate);
    }

    Return<void> getCdmaBroadcastConfig(int32_t serial) {
        return RadioImpl_1_2::getCdmaBroadcastConfig(serial);
    }

    Return<void> setCdmaBroadcastConfig(int32_t serial, const ::android::hardware::hidl_vec<::android::hardware::radio::V1_0::CdmaBroadcastSmsConfigInfo>& configInfo) {
        return RadioImpl_1_2::setCdmaBroadcastConfig(serial, configInfo);
    }

    Return<void> setCdmaBroadcastActivation(int32_t serial, bool activate) {
        return RadioImpl_1_2::setCdmaBroadcastActivation(serial, activate);
    }

    Return<void> getCDMASubscription(int32_t serial) {
        return RadioImpl_1_2::getCDMASubscription(serial);
    }

    Return<void> writeSmsToRuim(int32_t serial, const ::android::hardware::radio::V1_0::CdmaSmsWriteArgs& cdmaSms) {
        return RadioImpl_1_2::writeSmsToRuim(serial, cdmaSms);
    }

    Return<void> deleteSmsOnRuim(int32_t serial, int32_t index) {
        return RadioImpl_1_2::deleteSmsOnRuim(serial, index);
    }

    Return<void> getDeviceIdentity(int32_t serial) {
        return RadioImpl_1_2::getDeviceIdentity(serial);
    }

    Return<void> exitEmergencyCallbackMode(int32_t serial) {
        return RadioImpl_1_2::exitEmergencyCallbackMode(serial);
    }

    Return<void> getSmscAddress(int32_t serial) {
        return RadioImpl_1_2::getSmscAddress(serial);
    }

    Return<void> setSmscAddress(int32_t serial, const ::android::hardware::hidl_string& smsc) {
        return RadioImpl_1_2::setSmscAddress(serial, smsc);
    }

    Return<void> reportSmsMemoryStatus(int32_t serial, bool available) {
        return RadioImpl_1_2::reportSmsMemoryStatus(serial, available);
    }

    Return<void> reportStkServiceIsRunning(int32_t serial) {
        return RadioImpl_1_2::reportStkServiceIsRunning(serial);
    }

    Return<void> getCdmaSubscriptionSource(int32_t serial) {
        return RadioImpl_1_2::getCdmaSubscriptionSource(serial);
    }

    Return<void> requestIsimAuthentication(int32_t serial, const ::android::hardware::hidl_string& challenge) {
        return RadioImpl_1_2::requestIsimAuthentication(serial, challenge);
    }

    Return<void> acknowledgeIncomingGsmSmsWithPdu(int32_t serial, bool success, const ::android::hardware::hidl_string& ackPdu) {
        return RadioImpl_1_2::acknowledgeIncomingGsmSmsWithPdu(serial, success, ackPdu);
    }

    Return<void> sendEnvelopeWithStatus(int32_t serial, const ::android::hardware::hidl_string& contents) {
        return RadioImpl_1_2::sendEnvelopeWithStatus(serial, contents);
    }

    Return<void> getVoiceRadioTechnology(int32_t serial) {
        return RadioImpl_1_2::getVoiceRadioTechnology(serial);
    }

    Return<void> getCellInfoList(int32_t serial) {
        return RadioImpl_1_2::getCellInfoList(serial);
    }

    Return<void> setCellInfoListRate(int32_t serial, int32_t rate) {
        return RadioImpl_1_2::setCellInfoListRate(serial, rate);
    }

    Return<void> setInitialAttachApn(int32_t serial, const ::android::hardware::radio::V1_0::DataProfileInfo& dataProfileInfo, bool modemCognitive, bool isRoaming) {
        return RadioImpl_1_2::setInitialAttachApn(serial, dataProfileInfo, modemCognitive, isRoaming);
    }

    Return<void> getImsRegistrationState(int32_t serial) {
        return RadioImpl_1_2::getImsRegistrationState(serial);
    }

    Return<void> sendImsSms(int32_t serial, const ::android::hardware::radio::V1_0::ImsSmsMessage& message) {
        return RadioImpl_1_2::sendImsSms(serial, message);
    }

    Return<void> iccTransmitApduBasicChannel(int32_t serial, const ::android::hardware::radio::V1_0::SimApdu& message) {
        return RadioImpl_1_2::iccTransmitApduBasicChannel(serial, message);
    }

    Return<void> iccOpenLogicalChannel(int32_t serial, const ::android::hardware::hidl_string& aid, int32_t p2) {
        return RadioImpl_1_2::iccOpenLogicalChannel(serial, aid, p2);
    }

    Return<void> iccCloseLogicalChannel(int32_t serial, int32_t channelId) {
        return RadioImpl_1_2::iccCloseLogicalChannel(serial, channelId);
    }

    Return<void> iccTransmitApduLogicalChannel(int32_t serial, const ::android::hardware::radio::V1_0::SimApdu& message) {
        return RadioImpl_1_2::iccTransmitApduLogicalChannel(serial, message);
    }

    Return<void> nvReadItem(int32_t serial, ::android::hardware::radio::V1_0::NvItem itemId) {
        return RadioImpl_1_2::nvReadItem(serial, itemId);
    }

    Return<void> nvWriteItem(int32_t serial, const ::android::hardware::radio::V1_0::NvWriteItem& item) {
        return RadioImpl_1_2::nvWriteItem(serial, item);
    }

    Return<void> nvWriteCdmaPrl(int32_t serial, const ::android::hardware::hidl_vec<uint8_t>& prl) {
        return RadioImpl_1_2::nvWriteCdmaPrl(serial, prl);
    }

    Return<void> nvResetConfig(int32_t serial, ::android::hardware::radio::V1_0::ResetNvType resetType) {
        return RadioImpl_1_2::nvResetConfig(serial, resetType);
    }

    Return<void> setUiccSubscription(int32_t serial, const ::android::hardware::radio::V1_0::SelectUiccSub& uiccSub) {
        return RadioImpl_1_2::setUiccSubscription(serial, uiccSub);
    }

    Return<void> setDataAllowed(int32_t serial, bool allow) {
        return RadioImpl_1_2::setDataAllowed(serial, allow);
    }

    Return<void> getHardwareConfig(int32_t serial) {
        return RadioImpl_1_2::getHardwareConfig(serial);
    }

    Return<void> requestIccSimAuthentication(int32_t serial, int32_t authContext, const ::android::hardware::hidl_string& authData, const ::android::hardware::hidl_string& aid) {
        return RadioImpl_1_2::requestIccSimAuthentication(serial, authContext, authData, aid);
    }

    Return<void> setDataProfile(int32_t serial, const ::android::hardware::hidl_vec<::android::hardware::radio::V1_0::DataProfileInfo>& profiles, bool isRoaming) {
        return RadioImpl_1_2::setDataProfile(serial, profiles, isRoaming);
    }

    Return<void> requestShutdown(int32_t serial) {
        return RadioImpl_1_2::requestShutdown(serial);
    }

    Return<void> getRadioCapability(int32_t serial) {
        return RadioImpl_1_2::getRadioCapability(serial);
    }

    Return<void> setRadioCapability(int32_t serial, const ::android::hardware::radio::V1_0::RadioCapability& rc) {
        return RadioImpl_1_2::setRadioCapability(serial, rc);
    }

    Return<void> startLceService(int32_t serial, int32_t reportInterval, bool pullMode) {
        return RadioImpl_1_2::startLceService(serial, reportInterval, pullMode);
    }

    Return<void> stopLceService(int32_t serial) {
        return RadioImpl_1_2::stopLceService(serial);
    }

    Return<void> pullLceData(int32_t serial) {
        return RadioImpl_1_2::pullLceData(serial);
    }

    Return<void> getModemActivityInfo(int32_t serial) {
        return RadioImpl_1_2::getModemActivityInfo(serial);
    }

    Return<void> setAllowedCarriers(int32_t serial, bool allAllowed, const ::android::hardware::radio::V1_0::CarrierRestrictions& carriers) {
        return RadioImpl_1_2::setAllowedCarriers(serial, allAllowed, carriers);
    }

    Return<void> getAllowedCarriers(int32_t serial) {
        return RadioImpl_1_2::getAllowedCarriers(serial);
    }

    Return<void> sendDeviceState(int32_t serial, ::android::hardware::radio::V1_0::DeviceStateType deviceStateType, bool state) {
        return RadioImpl_1_2::sendDeviceState(serial, deviceStateType, state);
    }

    Return<void> setIndicationFilter(int32_t serial, ::android::hardware::hidl_bitfield<::android::hardware::radio::V1_0::IndicationFilter> indicationFilter) {
        return RadioImpl_1_2::setIndicationFilter(serial, indicationFilter);
    }

    Return<void> setSimCardPower(int32_t serial, bool powerUp) {
        return RadioImpl_1_2::setSimCardPower(serial, powerUp);
    }

    Return<void> responseAcknowledgement() {
        return RadioImpl_1_2::responseAcknowledgement();
    }

    Return<void> setCarrierInfoForImsiEncryption(int32_t serial, const ::android::hardware::radio::V1_1::ImsiEncryptionInfo& imsiEncryptionInfo) {
        return RadioImpl_1_2::setCarrierInfoForImsiEncryption(serial, imsiEncryptionInfo);
    }

    Return<void> setSimCardPower_1_1(int32_t serial, ::android::hardware::radio::V1_1::CardPowerState powerUp) {
        return RadioImpl_1_2::setSimCardPower_1_1(serial, powerUp);
    }

    Return<void> startNetworkScan(int32_t serial, const ::android::hardware::radio::V1_1::NetworkScanRequest& request) {
        return RadioImpl_1_2::startNetworkScan(serial, request);
    }

    Return<void> stopNetworkScan(int32_t serial) {
        return RadioImpl_1_2::stopNetworkScan(serial);
    }

    Return<void> startKeepalive(int32_t serial, const ::android::hardware::radio::V1_1::KeepaliveRequest& keepalive) {
        return RadioImpl_1_2::startKeepalive(serial, keepalive);
    }

    Return<void> stopKeepalive(int32_t serial, int32_t sessionHandle) {
        return RadioImpl_1_2::stopKeepalive(serial, sessionHandle);
    }

    Return<void> enableModem(int32_t serial, bool on);

    Return<void> getModemStackStatus(int32_t serial);

    Return<void> setSystemSelectionChannels(int32_t serial, bool specifyChannels,
            const hidl_vec<V1_1::RadioAccessSpecifier>& specifiers);
};

